// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "ABP_Mannequin_Base.h"

void ABP_Mannequin_Base::AnimGraph() {
}

void ABP_Mannequin_Base::BlueprintThreadSafeUpdateAnimation(float DeltaTime) {
    UpdateLocationData(DeltaTime);
    UpdateRotationData();
    UpdateVelocityData();
    UpdateAccelerationData();
    UpdateWallDetectionHeuristic();
    UpdateCharacterStateData(DeltaTime);
    UpdateBlendWeightData(DeltaTime);
    UpdateRootYawOffset(DeltaTime);
    UpdateAimingData();
    UpdateJumpFallData();
    IsFirstUpdate = false;
}

void ABP_Mannequin_Base::UpdateLocationData(double DeltaTime) {
    DisplacementSinceLastUpdate = KismetMathLibrary::VSizeXY(/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=407BCD7E-4481-B4DF-E752-F18C3C6229E1) */);
    WorldLocation = /* TODO[bpr-expr]: K2Node_PropertyAccess (guid=69F30BA7-4F58-CE1F-E592-B9AF51519904) */;
    DisplacementSpeed = KismetMathLibrary::SafeDivide(DisplacementSinceLastUpdate, DeltaTime);
    if (IsFirstUpdate) {
        DisplacementSinceLastUpdate = 0f;
        DisplacementSpeed = 0f;
    }
}

void ABP_Mannequin_Base::UpdateRotationData() {
    YawDeltaSinceLastUpdate = /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=EDB40DAA-4F48-B8AA-70AF-3089FC41F79E) */;
    YawDeltaSpeed = KismetMathLibrary::SafeDivide(/* TODO[bpr-expr]: K2Node_VariableSet (guid=1985C09D-4017-CE08-6E55-0FAD8DA95C3F) */, GetDeltaSeconds());
    WorldRotation = /* TODO[bpr-expr]: K2Node_PropertyAccess (guid=5A462AA2-4C06-4515-8F3A-86B91BD689C1) */;
    AdditiveLeanAngle = /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=9C2CC5C0-4851-F541-A9A2-F3AA60402F60) */;
    if (IsFirstUpdate) {
        YawDeltaSinceLastUpdate = 0f;
        AdditiveLeanAngle = 0f;
    }
}

void ABP_Mannequin_Base::UpdateVelocityData() {
    WasMovingLastUpdate = KismetMathLibrary::Not_PreBool(KismetMathLibrary::Vector_IsZero(LocalVelocity2D));
    WorldVelocity = /* TODO[bpr-expr]: K2Node_PropertyAccess (guid=879DC1F7-42A0-04A8-D053-528AE3EF65C3) */;
    WorldVelocity2D = /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=6088915E-4062-2C02-8A06-02B387B2DF63) */;
    LocalVelocity2D = KismetMathLibrary::LessLess_VectorRotator(WorldVelocity2D, WorldRotation);
    LocalVelocityDirectionAngle = KismetAnimationLibrary::CalculateDirection(WorldRotation, WorldVelocity2D);
    LocalVelocityDirectionAngleWithOffset = /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=4804A599-4882-58E0-CFFD-8B948CE9388F) */;
    LocalVelocityDirection = SelectCardinalDirectionFromAngle(LocalVelocityDirectionAngleWithOffset, LocalVelocityDirection, CardinalDirectionDeadZone, WasMovingLastUpdate);
    LocalVelocityDirectionNoOffset = SelectCardinalDirectionFromAngle(LocalVelocityDirectionAngle, LocalVelocityDirectionNoOffset, CardinalDirectionDeadZone, WasMovingLastUpdate);
    HasVelocity = KismetMathLibrary::Not_PreBool(KismetMathLibrary::NearlyEqual_FloatFloat(KismetMathLibrary::VSizeXYSquared(LocalVelocity2D), 0f, 1e-06f));
}

void ABP_Mannequin_Base::UpdateAccelerationData() {
    WorldAcceleration2D = /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=2E786496-4D75-6547-0CB1-15B78FA4BDFC) */;
    LocalAcceleration2D = KismetMathLibrary::LessLess_VectorRotator(WorldAcceleration2D, WorldRotation);
    HasAcceleration = KismetMathLibrary::Not_PreBool(KismetMathLibrary::NearlyEqual_FloatFloat(KismetMathLibrary::VSizeXYSquared(LocalAcceleration2D), 0f, 1e-06f));
    PivotDirection2D = KismetMathLibrary::Normal(KismetMathLibrary::VLerp(PivotDirection2D, 0.5f, KismetMathLibrary::Normal(WorldAcceleration2D, 0.0001f)), 0.0001f);
    CardinalDirectionFromAcceleration = GetOppositeCardinalDirection(SelectCardinalDirectionFromAngle(KismetAnimationLibrary::CalculateDirection(WorldRotation, PivotDirection2D), TEXT("NewEnumerator0"), CardinalDirectionDeadZone, false));
}

void ABP_Mannequin_Base::SetRootYawOffset(double InRootYawOffset) {
    if (bEnableRootYawOffset) {
        RootYawOffset = KismetMathLibrary::SelectFloat(KismetMathLibrary::NormalizeAxis(InRootYawOffset), KismetMathLibrary::ClampAngle(KismetMathLibrary::NormalizeAxis(InRootYawOffset), KismetMathLibrary::BreakVector2D((IsCrouching ? RootYawOffsetAngleClampCrouched : RootYawOffsetAngleClamp)), KismetMathLibrary::BreakVector2D((IsCrouching ? RootYawOffsetAngleClampCrouched : RootYawOffsetAngleClamp))), /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=0AA63C7E-4F3D-CF9A-4AE7-42A97AFDA89C) */);
        AimYaw = /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=2494EF22-4E33-A2EF-F52D-E39BB488A664) */;
    } else {
        RootYawOffset = 0f;
        AimYaw = 0f;
    }
}

void ABP_Mannequin_Base::ProcessTurnYawCurve() {
    PreviousTurnYawCurveValue = TurnYawCurveValue;
    if (KismetMathLibrary::NearlyEqual_FloatFloat(GetCurveValue(TEXT("TurnYawWeight")), 0f, 0.0001f)) {
        TurnYawCurveValue = 0f;
        PreviousTurnYawCurveValue = 0f;
    } else {
        TurnYawCurveValue = /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=5FA689E4-4AFA-7D05-3D34-7D9A3073D237) */;
        if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=14DFB2EF-4B91-D1EB-FE16-B1B1D3572D31) */) {
            SetRootYawOffset(/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=89D7482D-44BE-E549-023B-6EA3C1C527E5) */);
        }
    }
}

void ABP_Mannequin_Base::UpdateIdleState(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    if (AnimationStateMachineLibrary::IsStateBlendingOut(AnimationStateMachineLibrary::ConvertToAnimationStateResultPure(Node), Context)) {
        TurnYawCurveValue = 0f;
    } else {
        RootYawOffsetMode = TEXT("NewEnumerator2");
        ProcessTurnYawCurve();
    }
}

void ABP_Mannequin_Base::SetUpStartState(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    StartDirection = LocalVelocityDirection;
    return;
}

void ABP_Mannequin_Base::UpdateStartState(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    if (AnimationStateMachineLibrary::IsStateBlendingOut(AnimationStateMachineLibrary::ConvertToAnimationStateResultPure(Node), Context)) {
    } else {
        RootYawOffsetMode = TEXT("NewEnumerator1");
    }
}

void ABP_Mannequin_Base::UpdateStopState(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    if (AnimationStateMachineLibrary::IsStateBlendingOut(AnimationStateMachineLibrary::ConvertToAnimationStateResultPure(Node), Context)) {
    } else {
        RootYawOffsetMode = TEXT("NewEnumerator2");
        return;
    }
}

void ABP_Mannequin_Base::SetUpPivotState(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    PivotInitialDirection = LocalVelocityDirection;
    return;
}

void ABP_Mannequin_Base::UpdatePivotState(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=DAD56547-4B17-9B96-6772-E3B2C8019C53) */) {
        LastPivotTime = /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=30F89B26-48F2-C848-DDD0-8496E568060D) */;
    }
}

void ABP_Mannequin_Base::UpdateCharacterStateData(double DeltaTime) {
}

void ABP_Mannequin_Base::UpdateBlendWeightData(double DeltaTime) {
    UpperbodyDynamicAdditiveWeight = KismetMathLibrary::SelectFloat(1f, KismetMathLibrary::FInterpTo(UpperbodyDynamicAdditiveWeight, DeltaTime, 6f, 0f), /* TODO[bpr-expr]: K2Node_CommutativeAssociativeBinaryOperator (guid=233FA0B0-4D61-98D2-9F1C-E9A6343ED5BD) */);
}

void ABP_Mannequin_Base::SelectCardinalDirectionFromAngle(double Angle, double DeadZone, uint8 CurrentDirection, bool UseCurrentDirection, uint8& Direction, uint8& Direction, uint8& Direction, uint8& Direction) {
    AbsAngle = KismetMathLibrary::Abs(Angle);
    FwdDeadZone = DeadZone;
    BwdDeadZone = /* TODO[bpr-expr]: K2Node_VariableSet (guid=E839D5BE-456F-F7F2-7077-039B9CF02662) */;
    if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=C1DAE898-44A8-032A-8F81-4FBE0872A393) */) {
        return TEXT("NewEnumerator0");
    } else {
        if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=E20F61FC-439B-6B96-EF1C-AC873251016C) */) {
            return TEXT("NewEnumerator1");
        } else {
            if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=2D439CFB-45DA-B0F3-CE1B-F7BC57690F70) */) {
                return TEXT("NewEnumerator3");
            } else {
                return TEXT("NewEnumerator2");
            }
        }
    }
    Direction = nullptr;
    Direction = nullptr;
    Direction = nullptr;
    Direction = nullptr;
    return;
}

void ABP_Mannequin_Base::UpdateAimingData() {
    AimPitch = KismetMathLibrary::NormalizeAxis(/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=1720A00F-4757-EDAD-E080-23AE5A20D609) */);
}

void ABP_Mannequin_Base::UpdateLocomotionStateMachine(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    if (IsFirstUpdate) {
    } else {
        LinkedLayerChanged = /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=2F2748F8-4963-1650-D21A-7E805C4F5233) */;
    }
    LastLinkedLayer = LinkedAnimGraphLibrary::GetLinkedAnimInstance(LinkedAnimGraphLibrary::ConvertToLinkedAnimGraphPure(/* TODO[bpr-expr]: K2Node_AnimNodeReference (guid=5356608A-43AE-836C-21C2-8D89CBA57EAC) */));
    return;
}

void ABP_Mannequin_Base::UpdateJumpFallData() {
    if (IsJumping) {
        TimeToJumpApex = /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=968D6636-4EA1-EEC0-EF89-CAA511BAC2A9) */;
    } else {
        TimeToJumpApex = 0f;
    }
}

void ABP_Mannequin_Base::UpdateRootYawOffset(double InDeltaTime) {
}

void ABP_Mannequin_Base::GetMovementComponent(UCharacterMovementComponent*& ReturnValue, UCharacterMovementComponent*& ReturnValue) {
    if (auto* AsCharacterMovementComponent = Cast<CharacterMovementComponent>(/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=E3E6699B-4189-E092-D698-6DAB38144772) */)) {
        return Cast<CharacterMovementComponent>(/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=E3E6699B-4189-E092-D698-6DAB38144772) */);
    } else {
        return nullptr;
    }
    ReturnValue = nullptr;
    ReturnValue = nullptr;
    return;
}

void ABP_Mannequin_Base::GetOppositeCardinalDirection(uint8 CurrentDirection, uint8& ReturnValue, uint8& ReturnValue, uint8& ReturnValue, uint8& ReturnValue) {
    switch (CurrentDirection) {
        case NewEnumerator0: {
            return TEXT("NewEnumerator1");
            break;
        }
        case NewEnumerator1: {
            return TEXT("NewEnumerator0");
            break;
        }
        case NewEnumerator2: {
            return TEXT("NewEnumerator3");
            break;
        }
        case NewEnumerator3: {
            return TEXT("NewEnumerator2");
            break;
        }
    }
    ReturnValue = nullptr;
    ReturnValue = nullptr;
    ReturnValue = nullptr;
    ReturnValue = nullptr;
    return;
}

bool ABP_Mannequin_Base::IsMovingPerpendicularToInitialPivot() {
    return /* TODO[bpr-expr]: K2Node_CommutativeAssociativeBinaryOperator (guid=13467538-416F-1B54-1BBE-FCA899A2559F) */;
}

void ABP_Mannequin_Base::UpdateWallDetectionHeuristic() {
    IsRunningIntoWall = /* TODO[bpr-expr]: K2Node_CommutativeAssociativeBinaryOperator (guid=CF0F6E3B-4F0A-C7A6-90FF-D1AC67E5D5AF) */;
}

bool ABP_Mannequin_Base::ShouldEnableControlRig() {
    return /* TODO[bpr-expr]: K2Node_CommutativeAssociativeBinaryOperator (guid=167027D5-40DA-961E-7593-F5BCA976FCD3) */;
}

