// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Characters/Heroes/Mannequin/Rig/ABP_Manny_PostProcess
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "AnimInstance.h"
#include "ABP_Manny_PostProcess.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class ABP_Manny_PostProcess : public AAnimInstance {
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintCallable)
    void AnimGraph();
};
