// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Weapons/Shotgun/Animations/ABP_Weap_Shotgun
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "AnimInstance.h"
#include "ABP_Weap_Shotgun.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class ABP_Weap_Shotgun : public AAnimInstance {
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintCallable)
    void AnimGraph();
};
