// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Weapons/Rifle/Animations/ABP_Weap_Rifle
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "AnimInstance.h"
#include "ABP_Weap_Rifle.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class ABP_Weap_Rifle : public AAnimInstance {
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintCallable)
    void AnimGraph();
};
