// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "ABP_ItemAnimLayersBase.h"

void ABP_ItemAnimLayersBase::AnimGraph() {
}

void ABP_ItemAnimLayersBase::UpdateIdleAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    SequencePlayerLibrary::SetSequenceWithInertialBlending(0.2f, (/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=4BD7A973-4368-EF4D-4F8E-F2818F8BFAFD) */ ? Crouch_Idle : (/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=8D29052A-4565-2962-9830-B08375727486) */ ? Idle_ADS : Idle_Hipfire)), SequencePlayerLibrary::ConvertToSequencePlayerPure(Node), Context);
    return;
}

void ABP_ItemAnimLayersBase::SetUpIdleBreakAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    SequencePlayerLibrary::SetSequence(/* TODO[bpr-expr]: K2Node_GetArrayItem (guid=5FA04E70-4C36-0A75-4BCE-99A7ECAAD717) */, SequencePlayerLibrary::ConvertToSequencePlayerPure(Node));
    // TODO[bpr-unsupported]: K2Node_MacroInstance (guid=DF96B89C-400B-3709-F1E8-4389ED233B8B) — manual port required.
    // Manual: Unrecognized BP node class 'K2Node_MacroInstance'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
}

void ABP_ItemAnimLayersBase::SetUpStartAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    SequenceEvaluatorLibrary::SetSequence((/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=86914E31-4CCA-410F-FABC-7EB0DB4FE882) */ ? nullptr : (/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=DDDCB6FB-4A6A-FDA6-AB7F-6AA4AF7A1A6B) */ ? nullptr : nullptr)), SequenceEvaluatorLibrary::ConvertToSequenceEvaluatorPure(Node));
    SequenceEvaluatorLibrary::SetExplicitTime(SequenceEvaluatorLibrary::SetSequence((/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=86914E31-4CCA-410F-FABC-7EB0DB4FE882) */ ? nullptr : (/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=DDDCB6FB-4A6A-FDA6-AB7F-6AA4AF7A1A6B) */ ? nullptr : nullptr)), SequenceEvaluatorLibrary::ConvertToSequenceEvaluatorPure(Node)), 0f);
    StrideWarpingStartAlpha = 0f;
    return;
}

void ABP_ItemAnimLayersBase::UpdateStartAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    ExplicitTime = SequenceEvaluatorLibrary::GetAccumulatedTime(SequenceEvaluatorLibrary::ConvertToSequenceEvaluatorPure(Node));
    StrideWarpingStartAlpha = KismetMathLibrary::MapRangeClamped(0f, StrideWarpingBlendInDurationScaled, 0f, 1f, /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=8476834F-46B0-02F4-9E31-29BB53615210) */);
    AnimDistanceMatchingLibrary::AdvanceTimeByDistanceMatching(LocomotionDistanceCurveName, /* TODO[bpr-expr]: K2Node_PropertyAccess (guid=782C29AD-478C-477E-56D6-7FBBE47BFEE6) */, KismetMathLibrary::MakeVector2D(KismetMathLibrary::Lerp(StrideWarpingBlendInDurationScaled, StrideWarpingStartAlpha, KismetMathLibrary::BreakVector2D(PlayRateClampStartsPivots)), KismetMathLibrary::BreakVector2D(PlayRateClampStartsPivots)), SequenceEvaluatorLibrary::ConvertToSequenceEvaluatorPure(Node), Context);
    return;
}

void ABP_ItemAnimLayersBase::UpdateCycleAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    SequencePlayerLibrary::SetSequenceWithInertialBlending(0.2f, (/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=C9F4135B-4D95-CC2A-B389-3B94951CF4BE) */ ? nullptr : (/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=E5306190-448D-42B6-2DE7-30AD3C7C638A) */ ? nullptr : nullptr)), SequencePlayerLibrary::ConvertToSequencePlayerPure(Node), Context);
    AnimDistanceMatchingLibrary::SetPlayrateToMatchSpeed(PlayRateClampCycle, SequencePlayerLibrary::SetSequenceWithInertialBlending(0.2f, (/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=C9F4135B-4D95-CC2A-B389-3B94951CF4BE) */ ? nullptr : (/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=E5306190-448D-42B6-2DE7-30AD3C7C638A) */ ? nullptr : nullptr)), SequencePlayerLibrary::ConvertToSequencePlayerPure(Node), Context), /* TODO[bpr-expr]: K2Node_PropertyAccess (guid=1DA6B199-4947-8110-FA69-DEA51A4AF585) */);
    StrideWarpingCycleAlpha = KismetMathLibrary::FInterpTo(StrideWarpingCycleAlpha, AnimExecutionContextLibrary::GetDeltaTime(Context), 10f, KismetMathLibrary::SelectFloat(0.5f, 1f, /* TODO[bpr-expr]: K2Node_PropertyAccess (guid=B75F33CB-4EE0-443E-511E-EA974D9AB18D) */));
    return;
}

void ABP_ItemAnimLayersBase::SetUpStopAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    SequenceEvaluatorLibrary::SetSequence((/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=9A75CC2D-4C55-429D-AC90-FF9D8634B649) */ ? nullptr : (/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=9165D776-4926-056F-D5B2-DBADE6361146) */ ? nullptr : nullptr)), SequenceEvaluatorLibrary::ConvertToSequenceEvaluatorPure(Node));
    if (ShouldDistanceMatchStop()) {
    } else {
        AnimDistanceMatchingLibrary::DistanceMatchToTarget(LocomotionDistanceCurveName, 0f, SequenceEvaluatorLibrary::ConvertToSequenceEvaluatorPure(Node));
        return;
    }
}

void ABP_ItemAnimLayersBase::UpdateStopAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    if (ShouldDistanceMatchStop()) {
        DistanceToMatch = GetPredictedStopDistance();
        if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=017C1F8D-4B2C-E12B-473F-62ACE22F8C25) */) {
        }
    }
}

void ABP_ItemAnimLayersBase::BlueprintThreadSafeUpdateAnimation(float DeltaTime) {
    if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=DD12A2E0-497C-8FF7-DBE1-A998F8879AC6) */) {
        UpdateBlendWeightData(DeltaTime);
        UpdateJumpFallData(DeltaTime);
        UpdateSkelControlData();
    }
}

void ABP_ItemAnimLayersBase::SetUpPivotAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    PivotStartingAcceleration = /* TODO[bpr-expr]: K2Node_PropertyAccess (guid=55092583-4822-66C1-5C64-72ACC57A3CA7) */;
    SequenceEvaluatorLibrary::SetSequence(GetDesiredPivotSequence(/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=C0BD911B-441C-EA17-8D13-A7A4A9396192) */), SequenceEvaluatorLibrary::ConvertToSequenceEvaluatorPure(Node));
    SequenceEvaluatorLibrary::SetExplicitTime(SequenceEvaluatorLibrary::SetSequence(GetDesiredPivotSequence(/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=C0BD911B-441C-EA17-8D13-A7A4A9396192) */), SequenceEvaluatorLibrary::ConvertToSequenceEvaluatorPure(Node)), 0f);
    StrideWarpingPivotAlpha = 0f;
    TimeAtPivotStop = 0f;
    LastPivotTime = 0.2f;
    return;
}

void ABP_ItemAnimLayersBase::UpdatePivotAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    SequenceEvaluator = SequenceEvaluatorLibrary::ConvertToSequenceEvaluatorPure(Node);
    ExplicitTime = SequenceEvaluatorLibrary::GetAccumulatedTime(/* TODO[bpr-expr]: K2Node_VariableSet (guid=0BD94536-4197-6D99-F9F4-8FB3CB9E8E07) */);
    if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=1B5029AD-48B8-444D-E54A-658729F952F2) */) {
        NewDesiredSequence = GetDesiredPivotSequence(/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=A4FAD74C-4F4B-BA07-88E0-B79BA83E1539) */);
        if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=402A1AE2-490A-6884-D5A7-F084182B77CD) */) {
            SequenceEvaluatorLibrary::SetSequenceWithInertialBlending(0.2f, NewDesiredSequence, SequenceEvaluator, Context);
            PivotStartingAcceleration = /* TODO[bpr-expr]: K2Node_PropertyAccess (guid=5BC80B19-41D1-63B5-085C-228A1B572F52) */;
        }
    }
}

void ABP_ItemAnimLayersBase::SetUpIdleState(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    ChooseIdleBreakDelayTime();
    ResetIdleBreakTransitionLogic();
    return;
}

void ABP_ItemAnimLayersBase::UpdateIdleState(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    if (AnimationStateMachineLibrary::IsStateBlendingOut(AnimationStateMachineLibrary::ConvertToAnimationStateResultPure(Node), Context)) {
    } else {
        ProcessIdleBreakTransitionLogic(AnimExecutionContextLibrary::GetDeltaTime(Context));
        return;
    }
}

void ABP_ItemAnimLayersBase::SetupTurnInPlaceAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    TurnInPlaceAnimTime = 0f;
    SequenceEvaluatorLibrary::SetExplicitTime(SequenceEvaluatorLibrary::ConvertToSequenceEvaluatorPure(Node), 0f);
}

void ABP_ItemAnimLayersBase::UpdateTurnInPlaceAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    SequenceEvaluatorLibrary::SetSequenceWithInertialBlending(0.2f, SelectTurnInPlaceAnimation(TurnInPlaceRotationDirection), SequenceEvaluatorLibrary::ConvertToSequenceEvaluatorPure(Node), Context);
    TurnInPlaceAnimTime = /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=5C3CC085-4376-8F6E-C2AA-2E8CCBA71808) */;
    SequenceEvaluatorLibrary::SetExplicitTime(SequenceEvaluatorLibrary::ConvertToSequenceEvaluatorPure(Node), TurnInPlaceAnimTime);
    return;
}

void ABP_ItemAnimLayersBase::SetUpTurnInPlaceRotationState(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    TurnInPlaceRotationDirection = /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=B869E4E7-4A55-3B77-5C95-BAA9868B4F13) */;
    return;
}

void ABP_ItemAnimLayersBase::SetUpTurnInPlaceRecoveryState(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    TurnInPlaceRecoveryDirection = TurnInPlaceRotationDirection;
    return;
}

void ABP_ItemAnimLayersBase::UpdateTurnInPlaceRecoveryAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    SequencePlayerLibrary::SetSequenceWithInertialBlending(0.2f, SelectTurnInPlaceAnimation(TurnInPlaceRecoveryDirection), SequencePlayerLibrary::ConvertToSequencePlayerPure(Node), Context);
    return;
}

void ABP_ItemAnimLayersBase::UpdateHipFireRaiseWeaponPose(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    SequenceEvaluatorLibrary::SetSequence((/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=E39D182B-4B68-4211-63C3-30A38176A36E) */ ? Aim_HipFirePose_Crouch : Aim_HipFirePose), SequenceEvaluatorLibrary::ConvertToSequenceEvaluatorPure(Node));
    return;
}

void ABP_ItemAnimLayersBase::GetMainAnimBPThreadSafe(ABP_Mannequin_Base*& ReturnValue, ABP_Mannequin_Base*& ReturnValue) {
    if (auto* AsABPMannequinBase = Cast<ABP_Mannequin_Base>(/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=E3E6699B-4189-E092-D698-6DAB38144772) */)) {
        return Cast<ABP_Mannequin_Base>(/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=E3E6699B-4189-E092-D698-6DAB38144772) */);
    } else {
        if (auto* AsABPItemAnimLayersBase = Cast<ABP_ItemAnimLayersBase>(/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=E3E6699B-4189-E092-D698-6DAB38144772) */)) {
            return nullptr;
        } else {
            KismetSystemLibrary::LogString(TEXT("warning: AnimInstance passed to GetMainAnimBPThreadSafe is of invalid type"), true);
            return nullptr;
        }
    }
    ReturnValue = nullptr;
    ReturnValue = nullptr;
    return;
}

void ABP_ItemAnimLayersBase::UpdateBlendWeightData(double DeltaTime) {
    if (/* TODO[bpr-expr]: K2Node_CommutativeAssociativeBinaryOperator (guid=B9FE7392-4F6F-D42F-6354-1E8154A3A234) */) {
        HipFireUpperBodyOverrideWeight = 0f;
        AimOffsetBlendWeight = 1f;
    }
}

bool ABP_ItemAnimLayersBase::CanPlayIdleBreak() {
    return /* TODO[bpr-expr]: K2Node_CommutativeAssociativeBinaryOperator (guid=CE15B2AB-440B-9DCA-8742-CF931F6651A1) */;
}

void ABP_ItemAnimLayersBase::ResetIdleBreakTransitionLogic() {
    TimeUntilNextIdleBreak = IdleBreakDelayTime;
}

void ABP_ItemAnimLayersBase::ProcessIdleBreakTransitionLogic(double DeltaTime) {
    if (CanPlayIdleBreak()) {
    }
}

void ABP_ItemAnimLayersBase::ChooseIdleBreakDelayTime() {
    IdleBreakDelayTime = KismetMathLibrary::Conv_IntToDouble(/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=9B0F795D-4CF5-4F84-042F-51B5EC456F05) */);
}

void ABP_ItemAnimLayersBase::SetUpFallLandAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    SequenceEvaluatorLibrary::SetExplicitTime(SequenceEvaluatorLibrary::ConvertToSequenceEvaluatorPure(Node), 0f);
    return;
}

void ABP_ItemAnimLayersBase::UpdateFallLandAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    AnimDistanceMatchingLibrary::DistanceMatchToTarget(JumpDistanceCurveName, /* TODO[bpr-expr]: K2Node_PropertyAccess (guid=7CDD8CF5-4EA0-AD11-B025-979BE15A5C7E) */, SequenceEvaluatorLibrary::ConvertToSequenceEvaluatorPure(Node));
    return;
}

void ABP_ItemAnimLayersBase::LandRecoveryStart(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    LandRecoveryAlpha = KismetMathLibrary::SelectFloat(/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=F5B7BA20-4DF2-0C30-BAA4-EDA67770E53C) */, KismetMathLibrary::MapRangeClamped(0f, 0.4f, 0.1f, 1f, TimeFalling), /* TODO[bpr-expr]: K2Node_PropertyAccess (guid=25B7894D-4406-8FD9-5013-60AB4423C7B0) */);
    return;
}

void ABP_ItemAnimLayersBase::UpdateJumpFallData(double DeltaTime) {
    if (/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=9C85F028-41B5-A338-53EA-1FB492DD8236) */) {
    } else {
        if (/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=9BBFD2AD-4DD2-7ABB-A48C-9295F0FD2C83) */) {
            TimeFalling = 0f;
        }
    }
}

void ABP_ItemAnimLayersBase::UpdateSkelControlData() {
    HandIK_Right_Alpha = KismetMathLibrary::FClamp(1f, 0f, /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=1B9DCC5D-4080-F7A0-1418-FC84464F32D7) */);
    HandIK_Left_Alpha = KismetMathLibrary::FClamp(1f, 0f, /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=EA87E3A8-40AF-DB22-790A-D592358C4F8E) */);
}

void ABP_ItemAnimLayersBase::ShouldEnableFootPlacement(bool& ReturnValue, bool& ReturnValue) {
    if (IsValid(/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=87AE65AC-48DA-C2D1-8B6B-5EB71F63CA75) */)) {
    }
    ReturnValue = nullptr;
    ReturnValue = nullptr;
    return;
}

void ABP_ItemAnimLayersBase::GetMovementComponent(UCharacterMovementComponent*& ReturnValue, UCharacterMovementComponent*& ReturnValue) {
    if (auto* AsCharacterMovementComponent = Cast<CharacterMovementComponent>(/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=E3E6699B-4189-E092-D698-6DAB38144772) */)) {
        return Cast<CharacterMovementComponent>(/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=E3E6699B-4189-E092-D698-6DAB38144772) */);
    } else {
        return nullptr;
    }
    ReturnValue = nullptr;
    ReturnValue = nullptr;
    return;
}

UAnimSequenceBase* ABP_ItemAnimLayersBase::GetDesiredPivotSequence(uint8 InDirection) {
    return (/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=7FEAF73C-47F4-F90E-A843-4B9BF84F9180) */ ? nullptr : (/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=E3803819-405C-D1DA-B3F3-BDB82B214D1B) */ ? nullptr : nullptr));
}

double ABP_ItemAnimLayersBase::GetPredictedStopDistance() {
    return KismetMathLibrary::VSizeXY(AnimCharacterMovementLibrary::PredictGroundMovementStopLocation(/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=46C4983B-47EE-12C8-B102-0D91D6AD5B32) */, /* TODO[bpr-expr]: K2Node_PropertyAccess (guid=31FF2A1A-4824-ED31-F647-38A239FA1B55) */, /* TODO[bpr-expr]: K2Node_PropertyAccess (guid=BEAB3BE1-4633-72DF-DBBC-B88FA1DA7202) */, /* TODO[bpr-expr]: K2Node_PropertyAccess (guid=3843FDBB-4F86-0E4D-EA61-A6A4255CAD72) */, /* TODO[bpr-expr]: K2Node_PropertyAccess (guid=72CF159A-4388-92CB-8EB9-EA9F8EA2D3DC) */, /* TODO[bpr-expr]: K2Node_PropertyAccess (guid=AE0AB3D0-4EC7-556A-CEBF-EEA4870E489C) */));
}

bool ABP_ItemAnimLayersBase::ShouldDistanceMatchStop() {
    return /* TODO[bpr-expr]: K2Node_CommutativeAssociativeBinaryOperator (guid=7576B5B4-43DB-85A8-DAF7-06BE585854B9) */;
}

void ABP_ItemAnimLayersBase::SetupIdleTransition(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    SequencePlayerLibrary::SetSequence((/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=423A81EE-4CDE-3CAF-4286-989EF0C6460C) */ ? Crouch_Idle_Entry : Crouch_Idle_Exit), SequencePlayerLibrary::ConvertToSequencePlayerPure(Node));
    return;
}

void ABP_ItemAnimLayersBase::SetLeftHandPoseOverrideWeight(const FAnimUpdateContext& Context, const FAnimNodeReference& Node) {
    LeftHandPoseOverrideWeight = KismetMathLibrary::FClamp(1f, 0f, /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=31C506BF-41F9-AB10-921E-829E0812C69A) */);
    return;
}

UAnimSequence* ABP_ItemAnimLayersBase::SelectTurnInPlaceAnimation(double Direction) {
    return (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=94CEF939-4C8D-210C-B2C8-A6A611CC5DC0) */ ? (/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=E4238653-435D-B11E-20CB-1FA4C4343FE7) */ ? Crouch_TurnInPlace_Right : TurnInPlace_Right) : (/* TODO[bpr-expr]: K2Node_PropertyAccess (guid=39EA6ABE-44D2-5C8E-ED66-EEBC468EAEC2) */ ? Crouch_TurnInPlace_Left : TurnInPlace_Left));
}

