// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Characters/Heroes/Mannequin/Animations/ABP_Mannequin_Base
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraAnimInstance.h"
class UAnimInstance;

#include "ABP_Mannequin_Base.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class ABP_Mannequin_Base : public ULyraAnimInstance, public IALI_ItemAnimLayers_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Gameplay Tag Bindings")
    bool GameplayTag_IsADS = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Gameplay Tag Bindings")
    bool GameplayTag_IsFiring = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Location Data")
    FVector WorldLocation;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Location Data")
    double DisplacementSinceLastUpdate = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Rotation Data")
    FRotator WorldRotation;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Turn In Place")
    double RootYawOffset = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Rotation Data")
    double YawDeltaSinceLastUpdate = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Acceleration Data")
    FVector LocalAcceleration2D;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Acceleration Data")
    bool HasAcceleration = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Character State Data")
    bool IsOnGround = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Character State Data")
    bool IsCrouching = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Linked Layer Data")
    bool LinkedLayerChanged = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool IsFirstUpdate = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Velocity Data")
    FVector WorldVelocity;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Velocity Data")
    FVector LocalVelocity2D;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Turn In Place")
    FloatSpringState RootYawOffsetSpringState;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Turn In Place")
    double TurnYawCurveValue = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="LocomotionSM Data")
    uint8 StartDirection = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Velocity Data")
    double LocalVelocityDirectionAngle = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    double CardinalDirectionDeadZone = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Velocity Data")
    double LocalVelocityDirectionAngleWithOffset = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Velocity Data")
    uint8 LocalVelocityDirection = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Velocity Data")
    uint8 LocalVelocityDirectionNoOffset = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Location Data")
    double DisplacementSpeed = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Velocity Data")
    bool HasVelocity = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="LocomotionSM Data")
    uint8 PivotInitialDirection = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Character State Data")
    bool CrouchStateChange = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Character State Data")
    bool ADSStateChanged = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Character State Data")
    bool WasADSLastUpdate = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Character State Data")
    double TimeSinceFiredWeapon = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Character State Data")
    bool IsJumping = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Character State Data")
    bool IsFalling = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Aiming Data")
    double AimPitch = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Linked Layer Data")
    TObjectPtr<UAnimInstance> LastLinkedLayer;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Character State Data")
    double TimeToJumpApex = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Turn In Place")
    uint8 RootYawOffsetMode = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Gameplay Tag Bindings")
    bool GameplayTag_IsReloading = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Gameplay Tag Bindings")
    bool GameplayTag_IsDashing = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Gameplay Tag Bindings")
    bool GameplayTag_IsMelee = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Turn In Place")
    FVector2D RootYawOffsetAngleClamp;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Blend Weight Data")
    double UpperbodyDynamicAdditiveWeight = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Rotation Data")
    double AdditiveLeanAngle = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="LocomotionSM Data")
    double LastPivotTime = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="LocomotionSM Data")
    uint8 CardinalDirectionFromAcceleration = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Turn In Place")
    FVector2D RootYawOffsetAngleClampCrouched;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Acceleration Data")
    FVector PivotDirection2D;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Rotation Data")
    double YawDeltaSpeed = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool EnableControlRig = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Character State Data")
    bool IsRunningIntoWall = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Aiming Data")
    double AimYaw = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool UseFootPlacement = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool bEnableRootYawOffset = false;

    UFUNCTION(BlueprintCallable)
    void AnimGraph();
    UFUNCTION(BlueprintCallable)
    void BlueprintThreadSafeUpdateAnimation(float DeltaTime);
    UFUNCTION(BlueprintCallable)
    void UpdateLocationData(double DeltaTime);
    UFUNCTION(BlueprintCallable)
    void UpdateRotationData();
    UFUNCTION(BlueprintCallable)
    void UpdateVelocityData();
    UFUNCTION(BlueprintCallable)
    void UpdateAccelerationData();
    UFUNCTION(BlueprintCallable)
    void SetRootYawOffset(double InRootYawOffset);
    UFUNCTION(BlueprintCallable)
    void ProcessTurnYawCurve();
    UFUNCTION(BlueprintCallable)
    void UpdateIdleState(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void SetUpStartState(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void UpdateStartState(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void UpdateStopState(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void SetUpPivotState(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void UpdatePivotState(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void UpdateCharacterStateData(double DeltaTime);
    UFUNCTION(BlueprintCallable)
    void UpdateBlendWeightData(double DeltaTime);
    UFUNCTION(BlueprintCallable)
    void SelectCardinalDirectionFromAngle(double Angle, double DeadZone, uint8 CurrentDirection, bool UseCurrentDirection, uint8& Direction, uint8& Direction, uint8& Direction, uint8& Direction);
    UFUNCTION(BlueprintCallable)
    void UpdateAimingData();
    UFUNCTION(BlueprintCallable)
    void UpdateLocomotionStateMachine(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void UpdateJumpFallData();
    UFUNCTION(BlueprintCallable)
    void UpdateRootYawOffset(double InDeltaTime);
    UFUNCTION(BlueprintCallable)
    void GetMovementComponent(UCharacterMovementComponent*& ReturnValue, UCharacterMovementComponent*& ReturnValue);
    UFUNCTION(BlueprintCallable)
    void GetOppositeCardinalDirection(uint8 CurrentDirection, uint8& ReturnValue, uint8& ReturnValue, uint8& ReturnValue, uint8& ReturnValue);
    UFUNCTION(BlueprintCallable)
    bool IsMovingPerpendicularToInitialPivot();
    UFUNCTION(BlueprintCallable)
    void UpdateWallDetectionHeuristic();
    UFUNCTION(BlueprintCallable)
    bool ShouldEnableControlRig();
};
