// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Characters/Heroes/Mannequin/Animations/ABP_Mannequin_TopDown
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "BP_Mannequin_Base_C.h"
#include "ABP_Mannequin_TopDown.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class ABP_Mannequin_TopDown : public ABP_Mannequin_Base_C {
    GENERATED_BODY()
public:
};
