// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Characters/Heroes/Mannequin/Animations/Locomotion/Rifle/ABP_RifleAnimLayers
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "BP_ItemAnimLayersBase_C.h"
#include "ABP_RifleAnimLayers.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class ABP_RifleAnimLayers : public ABP_ItemAnimLayersBase_C {
    GENERATED_BODY()
public:
};
