// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Characters/Heroes/Mannequin/Animations/LinkedLayers/ABP_ItemAnimLayersBase
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "AnimInstance.h"
class UAimOffsetBlendSpace;
class UAnimSequence;

#include "ABP_ItemAnimLayersBase.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class ABP_ItemAnimLayersBase : public AAnimInstance, public IALI_ItemAnimLayers_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="AnimSet - Walk")
    FAnimStruct_CardinalDirections Walk_Cardinals;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="AnimSet - Walk")
    FAnimStruct_CardinalDirections Crouch_Walk_Cardinals;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Idle")
    TObjectPtr<UAnimSequence> Idle_ADS;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Idle")
    TObjectPtr<UAnimSequence> Idle_Hipfire;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Idle")
    TArray<TObjectPtr<UAnimSequence>> Idle_Breaks;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Jog")
    FAnimStruct_CardinalDirections Jog_Cardinals;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Pivots")
    FAnimStruct_CardinalDirections Jog_Pivot_Cardinals;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Starts")
    FAnimStruct_CardinalDirections Jog_Start_Cardinals;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Stops")
    FAnimStruct_CardinalDirections Jog_Stop_Cardinals;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Jump")
    TObjectPtr<UAnimSequence> Jump_Start;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Jump")
    TObjectPtr<UAnimSequence> Jump_Apex;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Jump")
    TObjectPtr<UAnimSequence> Jump_FallLand;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Jump")
    TObjectPtr<UAnimSequence> Jump_RecoveryAdditive;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Idle")
    TObjectPtr<UAnimSequence> Crouch_Idle;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Idle Breaks")
    bool WantsIdleBreak = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Idle Breaks")
    double TimeUntilNextIdleBreak = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Idle Breaks")
    int32 CurrentIdleBreakIndex = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Aiming")
    TObjectPtr<UAnimSequence> Aim_HipFirePose;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Aiming")
    TObjectPtr<UAnimSequence> Aim_HipFirePose_Crouch;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Turn In Place")
    double TurnInPlaceAnimTime = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    FVector2D PlayRateClampStartsPivots;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Pivots")
    FVector PivotStartingAcceleration;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Aiming")
    TObjectPtr<UAimOffsetBlendSpace> IdleAimOffset;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Starts")
    FAnimStruct_CardinalDirections ADS_Start_Cardinals;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Starts")
    FAnimStruct_CardinalDirections Crouch_Start_Cardinals;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Stops")
    FAnimStruct_CardinalDirections ADS_Stop_Cardinals;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Stops")
    FAnimStruct_CardinalDirections Crouch_Stop_Cardinals;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Pivots")
    FAnimStruct_CardinalDirections ADS_Pivot_Cardinals;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Pivots")
    FAnimStruct_CardinalDirections Crouch_Pivot_Cardinals;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    bool RaiseWeaponAfterFiringWhenCrouched = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    bool DisableHandIK = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    bool EnableLeftHandPoseOverride = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    double RaiseWeaponAfterFiringDuration = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Blend Weight Data")
    double HipFireUpperBodyOverrideWeight = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Idle Breaks")
    double IdleBreakDelayTime = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Jump")
    TObjectPtr<UAnimSequence> Jump_StartLoop;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Jump")
    TObjectPtr<UAnimSequence> Jump_FallLoop;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Jump")
    double LandRecoveryAlpha = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Jump")
    double TimeFalling = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Skel Control Data")
    double HandIK_Right_Alpha = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Skel Control Data")
    double HandIK_Left_Alpha = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Stride Warping")
    double StrideWarpingStartAlpha = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Stride Warping")
    double StrideWarpingPivotAlpha = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Stride Warping")
    double StrideWarpingCycleAlpha = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Pivots")
    double TimeAtPivotStop = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    double StrideWarpingBlendInDurationScaled = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    double StrideWarpingBlendInStartOffset = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Idle")
    TObjectPtr<UAnimSequence> Crouch_Idle_Entry;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Idle")
    TObjectPtr<UAnimSequence> Crouch_Idle_Exit;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Idle")
    TObjectPtr<UAnimSequence> LeftHandPose_Override;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    FName LocomotionDistanceCurveName;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Jump")
    FName JumpDistanceCurveName;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Blend Weight Data")
    double AimOffsetBlendWeight = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Aiming")
    TObjectPtr<UAimOffsetBlendSpace> RelaxedAimOffset;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    FVector2D PlayRateClampCycle;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Turn in Place")
    TObjectPtr<UAnimSequence> TurnInPlace_Left;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double LeftHandPoseOverrideWeight = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    float HandFKWeight = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Turn In Place")
    double TurnInPlaceRotationDirection = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Turn in Place")
    TObjectPtr<UAnimSequence> TurnInPlace_Right;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Turn in Place")
    TObjectPtr<UAnimSequence> Crouch_TurnInPlace_Left;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Anim Set - Turn in Place")
    TObjectPtr<UAnimSequence> Crouch_TurnInPlace_Right;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Turn In Place")
    double TurnInPlaceRecoveryDirection = 0.0;

    UFUNCTION(BlueprintCallable)
    void AnimGraph();
    UFUNCTION(BlueprintCallable)
    void UpdateIdleAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void SetUpIdleBreakAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void SetUpStartAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void UpdateStartAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void UpdateCycleAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void SetUpStopAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void UpdateStopAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void BlueprintThreadSafeUpdateAnimation(float DeltaTime);
    UFUNCTION(BlueprintCallable)
    void SetUpPivotAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void UpdatePivotAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void SetUpIdleState(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void UpdateIdleState(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void SetupTurnInPlaceAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void UpdateTurnInPlaceAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void SetUpTurnInPlaceRotationState(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void SetUpTurnInPlaceRecoveryState(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void UpdateTurnInPlaceRecoveryAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void UpdateHipFireRaiseWeaponPose(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void GetMainAnimBPThreadSafe(ABP_Mannequin_Base*& ReturnValue, ABP_Mannequin_Base*& ReturnValue);
    UFUNCTION(BlueprintCallable)
    void UpdateBlendWeightData(double DeltaTime);
    UFUNCTION(BlueprintCallable)
    bool CanPlayIdleBreak();
    UFUNCTION(BlueprintCallable)
    void ResetIdleBreakTransitionLogic();
    UFUNCTION(BlueprintCallable)
    void ProcessIdleBreakTransitionLogic(double DeltaTime);
    UFUNCTION(BlueprintCallable)
    void ChooseIdleBreakDelayTime();
    UFUNCTION(BlueprintCallable)
    void SetUpFallLandAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void UpdateFallLandAnim(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void LandRecoveryStart(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void UpdateJumpFallData(double DeltaTime);
    UFUNCTION(BlueprintCallable)
    void UpdateSkelControlData();
    UFUNCTION(BlueprintCallable)
    void ShouldEnableFootPlacement(bool& ReturnValue, bool& ReturnValue);
    UFUNCTION(BlueprintCallable)
    void GetMovementComponent(UCharacterMovementComponent*& ReturnValue, UCharacterMovementComponent*& ReturnValue);
    UFUNCTION(BlueprintCallable)
    UAnimSequenceBase* GetDesiredPivotSequence(uint8 InDirection);
    UFUNCTION(BlueprintCallable)
    double GetPredictedStopDistance();
    UFUNCTION(BlueprintCallable)
    bool ShouldDistanceMatchStop();
    UFUNCTION(BlueprintCallable)
    void SetupIdleTransition(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    void SetLeftHandPoseOverrideWeight(const FAnimUpdateContext& Context, const FAnimNodeReference& Node);
    UFUNCTION(BlueprintCallable)
    UAnimSequence* SelectTurnInPlaceAnimation(double Direction);
};
