// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Characters/Heroes/Mannequin/Animations/ABP_Mannequin_CopyPose
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "AnimInstance.h"
class USkeletalMeshComponent;

#include "ABP_Mannequin_CopyPose.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class ABP_Mannequin_CopyPose : public AAnimInstance {
    GENERATED_BODY()
public:
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<USkeletalMeshComponent> ComponentPlayingAnim;

    UFUNCTION(BlueprintCallable)
    void AnimGraph();
};
