// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Characters/Heroes/Mannequin/Animations/Locomotion/Shotgun/ABP_ShotgunAnimLayers_Feminine
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "BP_RifleAnimLayers_Feminine_C.h"
#include "ABP_ShotgunAnimLayers_Feminine.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class ABP_ShotgunAnimLayers_Feminine : public ABP_RifleAnimLayers_Feminine_C {
    GENERATED_BODY()
public:
};
