// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Blueprint/B_AbilitySpawner
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "B_WeaponSpawner_C.h"
#include "B_AbilitySpawner.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_AbilitySpawner : public UB_WeaponSpawner_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra|WeaponPickup")
    TSubclassOf</Script/GameplayAbilities.GameplayEffect> GameplayEffectToApply;

    UFUNCTION(BlueprintCallable)
    void GiveWeapon(const TSubclassOf</Script/LyraGame.LyraInventoryItemDefinition>& WeaponItemClass, APawn* ReceivingPawn, bool& ReturnValue, bool& ReturnValue);
};
