// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_AbilitySpawner.h"

void UB_AbilitySpawner::GiveWeapon(const TSubclassOf<ULyraInventoryItemDefinition>& WeaponItemClass, APawn* ReceivingPawn, bool& ReturnValue, bool& ReturnValue) {
    if (IsValid(AbilitySystemBlueprintLibrary::GetAbilitySystemComponent(ReceivingPawn))) {
    }
    ReturnValue = nullptr;
    ReturnValue = nullptr;
    return;
}

