// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Accolades/B_AccoladeRelay
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameplayMessageProcessor.h"
#include "B_AccoladeRelay.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_AccoladeRelay : public UGameplayMessageProcessor {
    GENERATED_BODY()
public:
};
