// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Bot/B_AI_Controller_LyraShooter_Passive
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "B_AI_Controller_LyraShooter_C.h"
#include "B_AI_Controller_LyraShooter_Passive.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_AI_Controller_LyraShooter_Passive : public UB_AI_Controller_LyraShooter_C {
    GENERATED_BODY()
public:
};
