// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_AimAssistTargetTest.h"
#include "Components/SceneComponent.h"
#include "Components/AimAssistTargetComponent.h"
#include "Components/StaticMeshComponent.h"

AB_AimAssistTargetTest::AB_AimAssistTargetTest() {
    DefaultSceneRoot = CreateDefaultSubobject<USceneComponent>(TEXT("DefaultSceneRoot"));
    AimAssistTarget = CreateDefaultSubobject<UAimAssistTargetComponent>(TEXT("AimAssistTarget"));
    Sphere = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Sphere"));
    AimAssistTarget->SetupAttachment(DefaultSceneRoot);
    Sphere->SetupAttachment(DefaultSceneRoot);
    RootComponent = DefaultSceneRoot;
    // TODO[bpr-comp-prop]: DefaultSceneRoot->bVisualizeComponent = true;
    // TODO[bpr-comp-prop]: AimAssistTarget->CapsuleHalfHeight = 54.753723f;
    // TODO[bpr-comp-prop]: AimAssistTarget->CapsuleRadius = 54.38335f;
    // TODO[bpr-comp-prop]: AimAssistTarget->bUseSystemDefaultObstacleAreaClass = false;
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassOverrideFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassOverrideFinder.Succeeded()) { /* TODO[bpr-comp-prop]: AimAssistTarget->AreaClassOverride = AreaClassOverrideFinder.Object; */ }
    }
    // TODO[bpr-component-default]: AimAssistTarget->BodyInstance = /* StructProperty: (ObjectType=ECC_PhysicsBody,CollisionProfileName="Custom",CollisionResponses=(ResponseArray=((Channel="Pawn",Response=ECR_Overlap),(Channel="Visibility",Response=ECR_Ignore),(Channel="Camera",Response=ECR_Ignore),(Channel="PhysicsBody",Response=ECR_Ignore),(Channel="Vehicle",Response=ECR_Ignore),(Channel="Destructible",Response=ECR_Ignore)))) */;
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Engine/BasicShapes/Sphere.Sphere'"));
        if (StaticMeshFinder.Succeeded()) { /* TODO[bpr-comp-prop]: Sphere->StaticMesh = StaticMeshFinder.Object; */ }
    }
    // TODO[bpr-component-default]: Sphere->OverrideMaterials = /* ArrayProperty: ("/Script/Engine.Material'/Engine/VREditor/Devices/Vive/M_ViveControllerTrim.M_ViveControllerTrim'") */;
}

