// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_AI_Controller_LyraShooter.h"
#include "Components/AIPerceptionComponent.h"

AB_AI_Controller_LyraShooter::AB_AI_Controller_LyraShooter() {
    AIPerception = CreateDefaultSubobject<AIPerceptionComponent>(TEXT("AIPerception"));
    RootComponent = AIPerception;
    // TODO[bpr-component-default]: AIPerception->SensesConfig = /* ArrayProperty: ("/Script/AIModule.AISenseConfig_Sight'/ShooterCore/Bot/B_AI_Controller_LyraShooter.B_AI_Controller_LyraShooter_C:AIPerception_GEN_VARIABLE.AISenseConfig_Sight_1'","/Script/AIModule.AISenseConfig_Damage'/ShooterCore/Bot/B_AI_Controller_LyraShooter.B_AI_Controller_LyraShooter_C:AIPerception_GEN_VARIABLE.AISenseConfig_Damage_0'") */;
    {
        static ConstructorHelpers::FObjectFinder<UClass> DominantSenseFinder(TEXT("/Script/CoreUObject.Class'/Script/AIModule.AISense_Sight'"));
        if (DominantSenseFinder.Succeeded()) { /* TODO[bpr-comp-prop]: AIPerception->DominantSense = DominantSenseFinder.Object; */ }
    }
}

