// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_AimAssistTargetTest.h"

AB_AimAssistTargetTest::AB_AimAssistTargetTest() {
    DefaultSceneRoot = CreateDefaultSubobject<USceneComponent>(TEXT("DefaultSceneRoot"));
    AimAssistTarget = CreateDefaultSubobject<UAimAssistTargetComponent>(TEXT("AimAssistTarget"));
    Sphere = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Sphere"));
    AimAssistTarget->SetupAttachment(DefaultSceneRoot);
    Sphere->SetupAttachment(DefaultSceneRoot);
    RootComponent = DefaultSceneRoot;
    DefaultSceneRoot->bVisualizeComponent = true;
    AimAssistTarget->CapsuleHalfHeight = 54.753723f;
    AimAssistTarget->CapsuleRadius = 54.38335f;
    AimAssistTarget->bUseSystemDefaultObstacleAreaClass = false;
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassOverrideFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassOverrideFinder.Succeeded()) { AimAssistTarget->AreaClassOverride = AreaClassOverrideFinder.Object; }
    }
    // TODO[bpr-component-default]: AimAssistTarget->BodyInstance = /* StructProperty: (ObjectType=ECC_PhysicsBody,CollisionProfileName="AimAssist_OverlapDynamic",CollisionResponses=(ResponseArray=((Channel="WorldStatic",Response=ECR_Ignore),(Channel="WorldDynamic",Response=ECR_Ignore),(Channel="Pawn",Response=ECR_Ignore),(Channel="Visibility",Response=ECR_Ignore),(Channel="Camera",Response=ECR_Ignore),(Channel="PhysicsBody",Response=ECR_Ignore),(Channel="Vehicle",Response=ECR_Ignore),(Channel="Destructible",Response=ECR_Ignore),(Channel="Lyra_TraceChannel_AimAssist",Response=ECR_Overlap)))) */;
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Engine/BasicShapes/Sphere.Sphere'"));
        if (StaticMeshFinder.Succeeded()) { Sphere->StaticMesh = StaticMeshFinder.Object; }
    }
    // TODO[bpr-component-default]: Sphere->OverrideMaterials = /* ArrayProperty: ("/Script/Engine.Material'/Engine/VREditor/Devices/Vive/M_ViveControllerTrim.M_ViveControllerTrim'") */;
}

