// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Input/Components/B_AimAssistTargetManager
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "AimAssistTargetManagerComponent.h"
#include "B_AimAssistTargetManager.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class AB_AimAssistTargetManager : public AAimAssistTargetManagerComponent {
    GENERATED_BODY()
public:
};
