// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Bot/B_AI_Controller_LyraShooter
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraPlayerBotController.h"
class AIPerceptionComponent;
class UBehaviorTree;

#include "B_AI_Controller_LyraShooter.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_AI_Controller_LyraShooter : public ULyraPlayerBotController {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double StuckTime = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FName EnemyNameKey;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UBehaviorTree> BTAsset;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<AIPerceptionComponent> AIPerception;

    UB_AI_Controller_LyraShooter();

};
