// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterTests/Input/SoundVibrations/B_AudioBasedVibration
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "InputDeviceAudioBasedVibrationProperty.h"
#include "B_AudioBasedVibration.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_AudioBasedVibration : public UInputDeviceAudioBasedVibrationProperty {
    GENERATED_BODY()
public:
};
