// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterTests/System/Experiences/B_AutomatedShooterTest
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraExperienceDefinition.h"
#include "B_AutomatedShooterTest.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_AutomatedShooterTest : public ULyraExperienceDefinition {
    GENERATED_BODY()
public:
};
