// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterTests/System/Experiences/B_BasicShooterTest
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraExperienceDefinition.h"
#include "B_BasicShooterTest.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_BasicShooterTest : public ULyraExperienceDefinition {
    GENERATED_BODY()
public:
};
