// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_BlockSpawning.h"

AB_BlockSpawning::AB_BlockSpawning() {
    DefaultSceneRoot = CreateDefaultSubobject<USceneComponent>(TEXT("DefaultSceneRoot"));
    RootComponent = DefaultSceneRoot;
    DefaultSceneRoot->bVisualizeComponent = true;
}

