// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /TopDownArena/Game/Bombs/B_Bomb_Standard
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "B_Bomb_Base_C.h"
class UAudioComponent;
class UMaterialInstanceDynamic;
class UNiagaraComponent;
class UStaticMeshComponent;

#include "B_Bomb_Standard.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_Bomb_Standard : public UB_Bomb_Base_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UMaterialInstanceDynamic> BombMID;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> SphereMesh;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> CylinderMesh;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UNiagaraComponent> FuseVFX;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UNiagaraComponent> NS_BombFuse1;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UAudioComponent> ExplosionAudio;

    UB_Bomb_Standard();

    UFUNCTION(BlueprintCallable)
    void ClientUpdateFireballVisuals();
};
