// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_Bomb_Standard.h"
#include "Components/StaticMeshComponent.h"
#include "NiagaraComponent.h"
#include "Components/AudioComponent.h"

UB_Bomb_Standard::UB_Bomb_Standard() {
    SphereMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("SphereMesh"));
    CylinderMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("CylinderMesh"));
    FuseVFX = CreateDefaultSubobject<UNiagaraComponent>(TEXT("FuseVFX"));
    NS_BombFuse1 = CreateDefaultSubobject<UNiagaraComponent>(TEXT("NS_BombFuse1"));
    ExplosionAudio = CreateDefaultSubobject<UAudioComponent>(TEXT("ExplosionAudio"));
    CylinderMesh->SetupAttachment(SphereMesh);
    FuseVFX->SetupAttachment(CylinderMesh);
    RootComponent = ExplosionAudio;
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Engine/BasicShapes/Sphere.Sphere'"));
        if (StaticMeshFinder.Succeeded()) { /* TODO[bpr-comp-prop]: SphereMesh->StaticMesh = StaticMeshFinder.Object; */ }
    }
    // TODO[bpr-component-default]: SphereMesh->OverrideMaterials = /* ArrayProperty: ("/Script/Engine.Material'/TopDownArena/Game/Bombs/M_Bomb.M_Bomb'") */;
    // TODO[bpr-component-default]: SphereMesh->BodyInstance = /* StructProperty: (ObjectType=ECC_WorldStatic,CollisionEnabled=NoCollision,CollisionProfileName="NoCollision",CollisionResponses=(ResponseArray=((Channel="Visibility",Response=ECR_Ignore),(Channel="Camera",Response=ECR_Ignore)))) */;
    // TODO[bpr-comp-prop]: SphereMesh->RelativeLocation = FVector(0.0f, 0.0f, 23.0f);
    // TODO[bpr-comp-prop]: SphereMesh->RelativeRotation = FRotator(-30.0f, -0.0f, -10.0f);
    // TODO[bpr-comp-prop]: SphereMesh->RelativeScale3D = FVector(0.5f, 0.5f, 0.5f);
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Engine/BasicShapes/Cylinder.Cylinder'"));
        if (StaticMeshFinder.Succeeded()) { /* TODO[bpr-comp-prop]: CylinderMesh->StaticMesh = StaticMeshFinder.Object; */ }
    }
    // TODO[bpr-comp-prop]: CylinderMesh->StaticMeshImportVersion = 1;
    // TODO[bpr-component-default]: CylinderMesh->OverrideMaterials = /* ArrayProperty: ("/Script/Engine.Material'/TopDownArena/Game/Bombs/M_Bomb.M_Bomb'") */;
    // TODO[bpr-component-default]: CylinderMesh->BodyInstance = /* StructProperty: (ObjectType=ECC_WorldStatic,CollisionEnabled=NoCollision,CollisionProfileName="NoCollision",CollisionResponses=(ResponseArray=((Channel="Visibility",Response=ECR_Ignore),(Channel="Camera",Response=ECR_Ignore)))) */;
    // TODO[bpr-comp-prop]: CylinderMesh->RelativeLocation = FVector(0.000002f, -0.0f, 49.506672f);
    // TODO[bpr-comp-prop]: CylinderMesh->RelativeScale3D = FVector(0.35f, 0.35f, 0.35f);
    {
        static ConstructorHelpers::FObjectFinder<UNiagaraSystem> AssetFinder(TEXT("/Script/Niagara.NiagaraSystem'/TopDownArena/Game/Effects/NS_BombFuse.NS_BombFuse'"));
        if (AssetFinder.Succeeded()) { /* TODO[bpr-comp-prop]: FuseVFX->Asset = AssetFinder.Object; */ }
    }
    // TODO[bpr-component-default]: FuseVFX->OverrideParameters = /* StructProperty: () */;
    // TODO[bpr-comp-prop]: FuseVFX->RelativeLocation = FVector(-0.000008f, -0.0f, 88.091614f);
    // TODO[bpr-comp-prop]: FuseVFX->RelativeRotation = FRotator(30.0f, -0.0f, 10.0f);
    {
        static ConstructorHelpers::FObjectFinder<UNiagaraSystem> AssetFinder(TEXT("/Script/Niagara.NiagaraSystem'/TopDownArena/Game/Effects/Bomb/NS_BombExplosion.NS_BombExplosion'"));
        if (AssetFinder.Succeeded()) { /* TODO[bpr-comp-prop]: NS_BombFuse1->Asset = AssetFinder.Object; */ }
    }
    // TODO[bpr-component-default]: NS_BombFuse1->OverrideParameters = /* StructProperty: (UserParameterRedirects=(((Name="PositionArray",TypeDefHandle=(RegisteredTypeIndex=68)), (Name="User.PositionArray",TypeDefHandle=(RegisteredTypeIndex=68)))),SortedParameterOffsets=((Offset=0,Name="User.PositionArray",TypeDefHandle=(RegisteredTypeIndex=68))),DataInterfaces=("/Script/Niagara.NiagaraDataInterfaceArrayFloat3'/TopDownArena/Game/Bombs/B_Bomb_Standard.B_Bomb_Standard_C:NS_BombFuse1_GEN_VARIABLE.NiagaraDataInterfaceArrayFloat3_1'")) */;
    // TODO[bpr-comp-prop]: NS_BombFuse1->bAutoActivate = false;
    {
        static ConstructorHelpers::FObjectFinder<USoundBase> SoundFinder(TEXT("/Script/Engine.SoundCue'/TopDownArena/Game/Bombs/ExplosionFireballCue.ExplosionFireballCue'"));
        if (SoundFinder.Succeeded()) { /* TODO[bpr-comp-prop]: ExplosionAudio->Sound = SoundFinder.Object; */ }
    }
    // TODO[bpr-comp-prop]: ExplosionAudio->bAutoActivate = false;
}

void UB_Bomb_Standard::ClientUpdateFireballVisuals() {
    ActorComponent::Activate(false);
    for (auto& Element : DirectionalRadius) {
        // TODO[bpr-unsupported]: K2Node_MacroInstance (guid=8E74BE92-4883-F7AA-A1E4-4AA270DE82A9) — manual port required.
        // Manual: Unrecognized BP node class 'K2Node_MacroInstance'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
    }
    NiagaraDataInterfaceArrayFunctionLibrary::SetNiagaraArrayVector(RelativeFireballPos, NS_BombFuse1, TEXT("User.PositionArray"));
    ActorComponent::Activate(true);
}

