// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_Bomb_Base.h"
#include "Net/UnrealNetwork.h"
#include "Components/SceneComponent.h"
#include "Components/BoxComponent.h"
#include "Components/InstancedStaticMeshComponent.h"

AB_Bomb_Base::AB_Bomb_Base() {
    DefaultSceneRoot = CreateDefaultSubobject<USceneComponent>(TEXT("DefaultSceneRoot"));
    CollisionBox = CreateDefaultSubobject<UBoxComponent>(TEXT("CollisionBox"));
    FireballCollision = CreateDefaultSubobject<UInstancedStaticMeshComponent>(TEXT("FireballCollision"));
    OverlapBox = CreateDefaultSubobject<UBoxComponent>(TEXT("OverlapBox"));
    CollisionBox->SetupAttachment(DefaultSceneRoot);
    FireballCollision->SetupAttachment(DefaultSceneRoot);
    OverlapBox->SetupAttachment(DefaultSceneRoot);
    RootComponent = DefaultSceneRoot;
    // TODO[bpr-comp-prop]: DefaultSceneRoot->bVisualizeComponent = true;
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassFinder.Succeeded()) { /* TODO[bpr-comp-prop]: CollisionBox->AreaClass = AreaClassFinder.Object; */ }
    }
    // TODO[bpr-comp-prop]: CollisionBox->bUseSystemDefaultObstacleAreaClass = false;
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassOverrideFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassOverrideFinder.Succeeded()) { /* TODO[bpr-comp-prop]: CollisionBox->AreaClassOverride = AreaClassOverrideFinder.Object; */ }
    }
    // TODO[bpr-comp-prop]: CollisionBox->CanCharacterStepUpOn = ECB_No;
    // TODO[bpr-component-default]: CollisionBox->BodyInstance = /* StructProperty: (ObjectType=ECC_WorldStatic,CollisionEnabled=QueryAndPhysics,CollisionProfileName="BlockAll",CollisionResponses=(ResponseArray=)) */;
    // TODO[bpr-comp-prop]: CollisionBox->RelativeLocation = FVector(-0.0f, -0.0f, 27.06225f);
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Engine/BasicShapes/Sphere.Sphere'"));
        if (StaticMeshFinder.Succeeded()) { /* TODO[bpr-comp-prop]: FireballCollision->StaticMesh = StaticMeshFinder.Object; */ }
    }
    // TODO[bpr-component-default]: FireballCollision->OverrideMaterials = /* ArrayProperty: (None) */;
    // TODO[bpr-component-default]: FireballCollision->BodyInstance = /* StructProperty: (ObjectType=ECC_WorldStatic,CollisionEnabled=QueryOnly,CollisionProfileName="OverlapAll",CollisionResponses=(ResponseArray=((Channel="WorldStatic",Response=ECR_Overlap),(Channel="WorldDynamic",Response=ECR_Overlap),(Channel="Pawn",Response=ECR_Overlap),(Channel="Visibility",Response=ECR_Overlap),(Channel="Camera",Response=ECR_Overlap),(Channel="PhysicsBody",Response=ECR_Overlap),(Channel="Vehicle",Response=ECR_Overlap),(Channel="Destructible",Response=ECR_Overlap)))) */;
    // TODO[bpr-comp-prop]: FireballCollision->RelativeScale3D = FVector(0.98f, 0.98f, 0.98f);
    // TODO[bpr-comp-prop]: FireballCollision->bHiddenInGame = true;
    // TODO[bpr-comp-prop]: OverlapBox->BoxExtent = FVector(48.0f, 48.0f, 96.0f);
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassFinder.Succeeded()) { /* TODO[bpr-comp-prop]: OverlapBox->AreaClass = AreaClassFinder.Object; */ }
    }
    // TODO[bpr-comp-prop]: OverlapBox->bUseSystemDefaultObstacleAreaClass = false;
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassOverrideFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassOverrideFinder.Succeeded()) { /* TODO[bpr-comp-prop]: OverlapBox->AreaClassOverride = AreaClassOverrideFinder.Object; */ }
    }
    // TODO[bpr-component-default]: OverlapBox->BodyInstance = /* StructProperty: (CollisionProfileName="OverlapOnlyPawn",CollisionResponses=(ResponseArray=((Channel="Pawn",Response=ECR_Overlap),(Channel="Camera",Response=ECR_Ignore),(Channel="Vehicle",Response=ECR_Overlap)))) */;
    // TODO[bpr-comp-prop]: OverlapBox->RelativeLocation = FVector(0.0f, 0.0f, 50.0f);
    bReplicates = true;
}

void AB_Bomb_Base::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const {
    Super::GetLifetimeReplicatedProps(OutLifetimeProps);
    DOREPLIFETIME(AB_Bomb_Base, DirectionalRadius);
}

void AB_Bomb_Base::ServerAddFireballInstance(int32 DeltaX, int32 DeltaY, bool& SpaceWasBlocked, bool& SpawnedFireball) {
    RelativeFireballPos = KismetMathLibrary::MakeVector(/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=553764E6-44DF-D21F-DF21-388F35E8EB4A) */, /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=7BB9D280-442F-57E5-1510-B49468CB55A3) */, 50f);
    WorldFireballPos = /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=89A34D89-4362-55B9-A3CE-82BC1B2E158B) */;
    KismetSystemLibrary::BoxOverlapActors(nullptr, {this}, TEXT("48.000000,48.000000,48.000000"), WorldFireballPos, {TEXT("ObjectTypeQuery2"), TEXT("ObjectTypeQuery1"), TEXT("ObjectTypeQuery3")}, nullptr);
    for (auto& Element : KismetSystemLibrary::BoxOverlapActors(nullptr, {this}, TEXT("48.000000,48.000000,48.000000"), WorldFireballPos, {TEXT("ObjectTypeQuery2"), TEXT("ObjectTypeQuery1"), TEXT("ObjectTypeQuery3")}, nullptr)) {
        if (auto* AsStaticMeshActor = Cast<StaticMeshActor>(/* TODO[bpr-expr]: K2Node_MacroInstance (guid=6010CB01-46C4-3906-4A04-D882FE6B7474) */)) {
            IsBlocked = true;
            SpawnFireball = false;
        } else {
            if (auto* AsBDestructableBlock = Cast</TopDownArena/Game/Environment/B_DestructableBlock.B_DestructableBlock>(/* TODO[bpr-expr]: K2Node_MacroInstance (guid=6010CB01-46C4-3906-4A04-D882FE6B7474) */)) {
                IsBlocked = true;
                SpawnBonus(Cast</TopDownArena/Game/Environment/B_DestructableBlock.B_DestructableBlock>(/* TODO[bpr-expr]: K2Node_MacroInstance (guid=6010CB01-46C4-3906-4A04-D882FE6B7474) */));
                K2_DestroyActor();
            } else {
                if (auto* AsBBombBase = Cast</TopDownArena/Game/Bombs/B_Bomb_Base.B_Bomb_Base>(/* TODO[bpr-expr]: K2Node_MacroInstance (guid=6010CB01-46C4-3906-4A04-D882FE6B7474) */)) {
                    IsBlocked = true;
                    TriggerExplosion();
                } else {
                    if (auto* AsBTopDownArenaPickup = Cast</TopDownArena/Game/Pickups/B_TopDownArena_Pickup.B_TopDownArena_Pickup>(/* TODO[bpr-expr]: K2Node_MacroInstance (guid=6010CB01-46C4-3906-4A04-D882FE6B7474) */)) {
                        IsBlocked = true;
                        K2_DestroyActor();
                    } else {
                        if (IsValid(AbilitySystemBlueprintLibrary::GetAbilitySystemComponent(/* TODO[bpr-expr]: K2Node_MacroInstance (guid=6010CB01-46C4-3906-4A04-D882FE6B7474) */))) {
                        }
                    }
                }
            }
        }
    }
    if (SpawnFireball) {
        InstancedStaticMeshComponent::AddInstance(nullptr, RelativeFireballPos, TEXT("0, 0, 0"), TEXT("1.000000,1.000000,1.000000"), false);
    }
    SpaceWasBlocked = IsBlocked;
    SpawnedFireball = SpawnFireball;
    return;
    SpaceWasBlocked = nullptr;
    SpawnedFireball = nullptr;
    return;
}

void AB_Bomb_Base::ServerExpandFireballInAllDirections() {
    for (auto& Element : DirectionsExpanding) {
        if (/* TODO[bpr-expr]: K2Node_GetArrayItem (guid=80EF075C-402E-9256-0A24-4AAB1604C12A) */) {
        } else {
            ServerAddFireballInstance(/* TODO[bpr-expr]: K2Node_MacroInstance (guid=61A7E5DC-478F-C7DF-92F2-2AAB6AB6EF5D) */.X, /* TODO[bpr-expr]: K2Node_MacroInstance (guid=61A7E5DC-478F-C7DF-92F2-2AAB6AB6EF5D) */.Y);
            // TODO[bpr-unsupported]: K2Node_CallArrayFunction (guid=D9D2E564-4938-2ADC-0FE5-47ACF707FEDA) — manual port required.
            // Manual: Unrecognized BP node class 'K2Node_CallArrayFunction'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
            if (ServerAddFireballInstance(/* TODO[bpr-expr]: K2Node_MacroInstance (guid=61A7E5DC-478F-C7DF-92F2-2AAB6AB6EF5D) */.X, /* TODO[bpr-expr]: K2Node_MacroInstance (guid=61A7E5DC-478F-C7DF-92F2-2AAB6AB6EF5D) */.Y)) {
                // TODO[bpr-unsupported]: K2Node_CallArrayFunction (guid=1B6EA6E7-49AF-8BA0-140A-9DA7F726F3F9) — manual port required.
                // Manual: Unrecognized BP node class 'K2Node_CallArrayFunction'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
            }
        }
    }
    // TODO[bpr-unsupported]: K2Node_MacroInstance (guid=F2EFD9DD-4B64-038B-A178-8BBF24775FB5) — manual port required.
    // Manual: Unrecognized BP node class 'K2Node_MacroInstance'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
}

void AB_Bomb_Base::SnapshotRange() {
    if (AbilitySystemBlueprintLibrary::GetFloatAttribute(InstigatingPlayerState, TEXT("(AttributeName=\"BombRange\",Attribute=/Script/TopDownArenaRuntime.TopDownArenaAttributeSet:BombRange,AttributeOwner=\"/Script/CoreUObject.Class'/Script/TopDownArenaRuntime.TopDownArenaAttributeSet'\")"))) {
        ExplosionRadius = KismetMathLibrary::FTrunc(AbilitySystemBlueprintLibrary::GetFloatAttribute(InstigatingPlayerState, TEXT("(AttributeName=\"BombRange\",Attribute=/Script/TopDownArenaRuntime.TopDownArenaAttributeSet:BombRange,AttributeOwner=\"/Script/CoreUObject.Class'/Script/TopDownArenaRuntime.TopDownArenaAttributeSet'\")")));
    }
}

void AB_Bomb_Base::SpawnBonus(AActor* Actor) {
    if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=6BE0B58B-42DD-F4F3-EC94-D297F8DFC59A) */) {
        [&]{ FActorSpawnParameters p;
    p.Owner = nullptr;
    p.Instigator = nullptr;
    p.SpawnCollisionHandlingOverride = TEXT("Undefined");
    return GetWorld()->SpawnActor<AActor>(nullptr, nullptr, p); }();
    }
}

void AB_Bomb_Base::OnRep_DirectionalRadius() {
    // TODO[bpr-unsupported]: K2Node_MacroInstance (guid=4DEA9C9F-49D3-AB96-08DD-C484CC9954BC) — manual port required.
    // Manual: Unrecognized BP node class 'K2Node_MacroInstance'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
}

void AB_Bomb_Base::ClientUpdateFireballVisuals() {
}

