// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /TopDownArena/Game/Bombs/B_Bomb_Base
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
class APlayerState;
class UBoxComponent;
class UGameplayEffect;
class UInstancedStaticMeshComponent;
class USceneComponent;

#include "B_Bomb_Base.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class AB_Bomb_Base : public AActor {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 ExplosionRadius = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 RadiusState = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool IsFuseStillBurning = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<FIntPoint> DirectionsExpanding;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<bool> DirectionsBlocked;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<APlayerState> InstigatingPlayerState;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 PercentageDropBonus = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double MinBurnTimeEvenIfShortened = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double BombLifespan = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double FireballPropagationDelay = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double FireballHoverTime = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Default")
    TArray<int32> DirectionalRadius;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TSubclassOf<UGameplayEffect> BombDamageGameplayEffect;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USceneComponent> DefaultSceneRoot;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UBoxComponent> CollisionBox;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UInstancedStaticMeshComponent> FireballCollision;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UBoxComponent> OverlapBox;

    AB_Bomb_Base();

    virtual void GetLifetimeReplicatedProps(TArray<class FLifetimeProperty>& OutLifetimeProps) const override;

    UFUNCTION(BlueprintCallable)
    void ServerAddFireballInstance(int32 DeltaX, int32 DeltaY, bool& SpaceWasBlocked, bool& SpawnedFireball);
    UFUNCTION(BlueprintCallable)
    void ServerExpandFireballInAllDirections();
    UFUNCTION(BlueprintCallable)
    void SnapshotRange();
    UFUNCTION(BlueprintCallable)
    void SpawnBonus(AActor* Actor);
    UFUNCTION(BlueprintCallable)
    void OnRep_DirectionalRadius();
    UFUNCTION(BlueprintCallable)
    void ClientUpdateFireballVisuals();
};
