// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Characters/Cosmetics/B_CharacterSelection
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraControllerComponent_CharacterParts.h"
#include "B_CharacterSelection.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_CharacterSelection : public ULyraControllerComponent_CharacterParts {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<TSubclassOf</Script/Engine.Actor>> AvailableCharacterParts;

};
