// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/ControlPoint/B_ControlPointScoring
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "B_ShooterGameScoring_Base_C.h"
class AActor;
class ULyraGamePhaseAbility;

#include "GameplayTagContainer.h"

#include "B_ControlPointScoring.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_ControlPointScoring : public UB_ShooterGameScoring_Base_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Default")
    int32 TargetScore = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Default")
    TArray<int32> ControlPointOwnerTeams;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Default")
    TArray<TObjectPtr<AActor>> ControlPoints;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TMap<FString, int32> TeamColors;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<FLinearColor> RawTeamColors;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 TeamColorAssignIndex = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FGameplayTag ActiveUserFacingCue;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 WinningTeamId = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 LeadingTeam = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double DelayBetweenScoring = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<ULyraGamePhaseAbility> Phase;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FTimerHandle ScoringTimer;

    virtual void GetLifetimeReplicatedProps(TArray<class FLifetimeProperty>& OutLifetimeProps) const override;

    UFUNCTION(BlueprintCallable)
    FLinearColor GetTeamColor(int32 TeamID);
    UFUNCTION(BlueprintCallable)
    void GetTeamScoreCP(int32 TeamID, int32& Current, int32& Target, bool& Victory);
    UFUNCTION(BlueprintCallable)
    void GetPointStatus(int32 TeamID, int32& OwnedByTeam, int32& Unowned, int32& OwnedByEnemy);
    UFUNCTION(BlueprintCallable)
    void ClearUserFacingCue();
    UFUNCTION(BlueprintCallable)
    void ActivateUserFacingCue(const FGameplayTag& GameplayCueTag, const FGameplayCueParameters& Parameters);
    UFUNCTION(BlueprintCallable)
    void HandleVictory(int32 TeamId);
    UFUNCTION(BlueprintCallable)
    void OnRep_TargetScore();
};
