// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_ControlPointScoring.h"
#include "Net/UnrealNetwork.h"

void UB_ControlPointScoring::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const {
    Super::GetLifetimeReplicatedProps(OutLifetimeProps);
    DOREPLIFETIME(UB_ControlPointScoring, TargetScore);
    DOREPLIFETIME(UB_ControlPointScoring, ControlPointOwnerTeams);
    DOREPLIFETIME(UB_ControlPointScoring, ControlPoints);
}

F/Script/CoreUObject.LinearColor UB_ControlPointScoring::GetTeamColor(int32 TeamID) {
    if (BlueprintMapLibrary::Map_Find(TeamID, TeamColors)) {
        return BlueprintMapLibrary::Map_Find(TeamID, TeamColors);
    } else {
        BlueprintMapLibrary::Map_Add(TeamID, TeamColors, /* TODO[bpr-expr]: K2Node_GetArrayItem (guid=C8846E19-408B-544C-49A6-28B29F0DCFA5) */);
        // TODO[bpr-unsupported]: K2Node_MacroInstance (guid=89CC85F9-463A-54A0-3E83-8ABE4CA94712) — manual port required.
        // Manual: Unrecognized BP node class 'K2Node_MacroInstance'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
    }
    return TEXT("");
}

void UB_ControlPointScoring::GetTeamScoreCP(int32 TeamID, int32& Current, int32& Target, bool& Victory) {
    Current = LyraTeamSubsystem::GetTeamTagStackCount(TEXT("(TagName=\"ShooterGame.ControlPoint.TeamScore\")"), TeamID);
    Target = TargetScore;
    Victory = /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=FA7B55EC-4257-EC2E-402B-BDBAD9AA8B15) */;
    return;
}

void UB_ControlPointScoring::GetPointStatus(int32 TeamID, int32& OwnedByTeam, int32& Unowned, int32& OwnedByEnemy) {
    for (auto& Element : ControlPointOwnerTeams) {
        if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=89AC91CF-475F-AE3D-622A-FA979BD756B1) */) {
            // TODO[bpr-unsupported]: K2Node_MacroInstance (guid=107E39DC-4D74-5761-61D7-DF99E3C4F883) — manual port required.
            // Manual: Unrecognized BP node class 'K2Node_MacroInstance'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
        } else {
            if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=980A8D1C-4858-08F9-90EB-90988AD482E1) */) {
                // TODO[bpr-unsupported]: K2Node_MacroInstance (guid=92BD2406-4E0B-5D15-3AD4-AC91D9FB664C) — manual port required.
                // Manual: Unrecognized BP node class 'K2Node_MacroInstance'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
            } else {
                // TODO[bpr-unsupported]: K2Node_MacroInstance (guid=863C52A0-4C9D-1D3E-7B83-0AA11AD91EF6) — manual port required.
                // Manual: Unrecognized BP node class 'K2Node_MacroInstance'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
            }
        }
    }
    OwnedByTeam = LOwnedByTeam;
    Unowned = LUnowned;
    OwnedByEnemy = LOwnedByEnemy;
    return;
}

void UB_ControlPointScoring::ClearUserFacingCue() {
    if (BlueprintGameplayTagLibrary::IsGameplayTagValid(ActiveUserFacingCue)) {
        GameplayCueFunctionLibrary::RemoveGameplayCueOnActor(ActiveUserFacingCue, AbilitySystemBlueprintLibrary::MakeGameplayCueParameters(1, nullptr, nullptr, nullptr, nullptr, 1, nullptr, TEXT("0,0,0"), nullptr, TEXT("0,0,0"), 0f, nullptr, nullptr, 0f, nullptr, nullptr, false), GameplayStatics::GetGameState(this, nullptr));
        ActiveUserFacingCue = nullptr;
    }
}

void UB_ControlPointScoring::ActivateUserFacingCue(const F/Script/GameplayTags.GameplayTag& GameplayCueTag, const F/Script/GameplayAbilities.GameplayCueParameters& Parameters) {
    ClearUserFacingCue();
    ActiveUserFacingCue = GameplayCueTag;
    GameplayCueFunctionLibrary::AddGameplayCueOnActor(/* TODO[bpr-expr]: K2Node_VariableSet (guid=7CBCE752-4B5A-5976-3D8D-EB8606A9CAC0) */, Parameters, GameplayStatics::GetGameState(this, nullptr));
    return;
}

void UB_ControlPointScoring::HandleVictory(int32 TeamId) {
    WinningTeamId = TeamId;
    ActivateUserFacingCue(TEXT("(TagName=\"GameplayCue.ShooterGame.UserMessage.MatchDecided\")"), AbilitySystemBlueprintLibrary::MakeGameplayCueParameters(WinningTeamId, nullptr, nullptr, nullptr, nullptr, 1, nullptr, TEXT("0,0,0"), nullptr, TEXT("0,0,0"), 0f, nullptr, nullptr, 0f, nullptr, nullptr, false));
    LyraGamePhaseSubsystem::K2_StartPhase(nullptr, nullptr);
    KismetSystemLibrary::K2_ClearAndInvalidateTimerHandle(ScoringTimer, nullptr);
}

void UB_ControlPointScoring::OnRep_TargetScore() {
}

