// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Blueprint/B_ControlPointVolume
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
class APawn;
class AStaticMeshActor;
class UAudioComponent;
class UB_ControlPointScoring;
class ULight;
class UNiagaraComponent;
class UPointLightComponent;
class USceneComponent;
class UStaticMeshComponent;

#include "B_ControlPointVolume.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class AB_ControlPointVolume : public AActor {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Control Point")
    TArray<TObjectPtr<APawn>> OverlappingPawns;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Control Point")
    TArray<int32> OverlappingTeams;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Control Point")
    int32 OwnerTeamID = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Control Point")
    double SecondsLeft = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Control Point")
    double TimeRequiredForCapture = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UB_ControlPointScoring> ControlPointGameMode;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Control Point")
    F/Script/CoreUObject.LinearColor TargetColor;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Control Point")
    F/Script/CoreUObject.LinearColor OwningTeamColor;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Control Point")
    int32 CapturingTeamID = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Control Point")
    F/Script/CoreUObject.Vector AreaScale;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Control Point")
    TArray<TObjectPtr<AStaticMeshActor>> StaticMeshList;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Control Point")
    TArray<TObjectPtr<UStaticMeshComponent>> SM_Components;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Control Point")
    TArray<TObjectPtr<ULight>> LightList;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USceneComponent> DefaultSceneRoot;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> Cube;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UNiagaraComponent> NS_CapturePoint;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UAudioComponent> Audio_CPProgress;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UNiagaraComponent> NS_CapturePointCounter;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UAudioComponent> Audio_CPComplete;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UPointLightComponent> PointLight;

    AB_ControlPointVolume();

    virtual void GetLifetimeReplicatedProps(TArray<class FLifetimeProperty>& OutLifetimeProps) const override;

    UFUNCTION(BlueprintCallable)
    void UpdateTimeline();
    UFUNCTION(BlueprintCallable)
    void CheckTimerNS();
    UFUNCTION(BlueprintCallable)
    void MarkThisPointContested();
    UFUNCTION(BlueprintCallable)
    void MarkThisPointRecaptured();
};
