// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/B_CommonInputData
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "CommonUIInputData.h"
#include "B_CommonInputData.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_CommonInputData : public UCommonUIInputData {
    GENERATED_BODY()
public:
};
