// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Item/B_CubeHat
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
class UStaticMeshComponent;

#include "B_CubeHat.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class AB_CubeHat : public AActor {
    GENERATED_BODY()
public:
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> Cube;

    AB_CubeHat();

};
