// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterTests/Blueprint/B_DevicePropertyTester
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "ShooterTestsDevicePropertyTester.h"
#include "B_DevicePropertyTester.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_DevicePropertyTester : public UShooterTestsDevicePropertyTester {
    GENERATED_BODY()
public:
};
