// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /TopDownArena/Game/Environment/B_DestructableBlock
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
class USceneComponent;
class UStaticMeshComponent;

#include "B_DestructableBlock.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class AB_DestructableBlock : public AActor {
    GENERATED_BODY()
public:
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USceneComponent> Scene;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> StaticMesh;

    AB_DestructableBlock();

};
