// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Accolades/B_ElimStreakProcessor
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "ElimStreakProcessor.h"
#include "B_ElimStreakProcessor.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_ElimStreakProcessor : public UElimStreakProcessor {
    GENERATED_BODY()
public:
};
