// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Accolades/B_ElimChainProcessor
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "ElimChainProcessor.h"
#include "B_ElimChainProcessor.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_ElimChainProcessor : public UElimChainProcessor {
    GENERATED_BODY()
public:
};
