// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_ExperienceList3D.h"
#include "Components/SceneComponent.h"
#include "Components/BillboardComponent.h"

AB_ExperienceList3D::AB_ExperienceList3D() {
    DefaultSceneRoot = CreateDefaultSubobject<USceneComponent>(TEXT("DefaultSceneRoot"));
    Billboard = CreateDefaultSubobject<UBillboardComponent>(TEXT("Billboard"));
    Billboard->SetupAttachment(DefaultSceneRoot);
    RootComponent = DefaultSceneRoot;
    // TODO[bpr-comp-prop]: DefaultSceneRoot->bVisualizeComponent = true;
    {
        static ConstructorHelpers::FObjectFinder<UTexture2D> SpriteFinder(TEXT("/Script/Engine.Texture2D'/Engine/EditorResources/S_Note.S_Note'"));
        if (SpriteFinder.Succeeded()) { /* TODO[bpr-comp-prop]: Billboard->Sprite = SpriteFinder.Object; */ }
    }
}

