// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Effects/Blueprints/B_FootStep
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
class UNiagaraComponent;
class UNiagaraSystem;
class USceneComponent;
class USkeletalMeshComponent;

#include "B_FootStep.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class AB_FootStep : public AActor, public ILyraContextEffectsInterface {
    GENERATED_BODY()
public:
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<UNiagaraComponent> NS_FootPrint;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool FootPrintTrigger = false;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<USkeletalMeshComponent> SkeletalMeshComponent;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool EnableFootPlantEffect = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FVector FootStepHitLocation;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FQuat FootStepOrientation;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 FootStepSurfaceTypeNiagara = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool FootStepSide = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    uint8 FootStepSurfaceType = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FVector FootStepHitNormal;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FTransform FootStepSocketTransform;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FName CurrentSocket;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UNiagaraSystem> FootPrintSystem;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FName FootStepRightFootBone;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FHitResult HitResult;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FName CurrentBone;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USceneComponent> DefaultSceneRoot;

    AB_FootStep();

};
