// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Environments/Gameplay/B_GameplayEffectPad_Child_Healing
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "BP_GameplayEffectPad_C.h"
#include "B_GameplayEffectPad_Child_Healing.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_GameplayEffectPad_Child_Healing : public UBP_GameplayEffectPad_C {
    GENERATED_BODY()
public:
};
