// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_GeneratedTube_Advanced.h"

UDynamicMesh* UB_GeneratedTube_Advanced::fnRepeater(UDynamicMesh* InputPin, int32 Instances) {
    AllocateComputeMesh();
    GeometryScriptLibrary_MeshDecompositionFunctions::CopyMeshToMesh(InputPin, AllocateComputeMesh(), nullptr);
    GeometryScriptLibrary_MeshBasicEditFunctions::AppendMeshRepeated(GeometryScriptLibrary_MeshDecompositionFunctions::CopyMeshToMesh(InputPin, AllocateComputeMesh(), nullptr), TEXT("()"), nullptr, TEXT("0, 0, 0"), TEXT("0,45.000000, 0"), 0f, 0f, /* TODO[bpr-expr]: K2Node_Composite (guid=FD4BED88-454F-B0A8-288F-92A77E329039) */, TEXT("1.000000,1.000000,1.000000"), nullptr, /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=386C5787-4A53-B697-F688-C0A4C07D65A6) */, InputPin, true, false);
    return GeometryScriptLibrary_MeshBasicEditFunctions::AppendMeshRepeated(GeometryScriptLibrary_MeshDecompositionFunctions::CopyMeshToMesh(InputPin, AllocateComputeMesh(), nullptr), TEXT("()"), nullptr, TEXT("0, 0, 0"), TEXT("0,45.000000, 0"), 0f, 0f, /* TODO[bpr-expr]: K2Node_Composite (guid=FD4BED88-454F-B0A8-288F-92A77E329039) */, TEXT("1.000000,1.000000,1.000000"), nullptr, /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=386C5787-4A53-B697-F688-C0A4C07D65A6) */, InputPin, true, false);
}

void UB_GeneratedTube_Advanced::ApplyMaterials(const TArray<UMaterialInterface*>& Materials) {
    Material = /* TODO[bpr-expr]: K2Node_GetArrayItem (guid=1B1E50FB-4D56-8FB0-308A-0FA14856BF06) */;
    return;
}

