// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Tools/B_GeneratedTube
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "BakedGeneratedMeshActor_C.h"
class UDynamicMesh;
class UMaterialInterface;

#include "B_GeneratedTube.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_GeneratedTube : public UBakedGeneratedMeshActor_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    double RevolveDegrees = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    double Radius = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    int32 Steps = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    double Thickness = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    double Height = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    double StartOffset = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    FVector VectorHandle;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    FVector ThicknessHandle;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    bool bUseHandles = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    bool bBevel = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    double BevelDistance = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    TObjectPtr<UMaterialInterface> Material;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UDynamicMesh> TargetMesh;

    UFUNCTION(BlueprintCallable)
    void ApplyMaterials(const TArray<UMaterialInterface*>& Materials);
};
