// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_GeneratedTube.h"

void UB_GeneratedTube::ApplyMaterials(const TArray<UMaterialInterface*>& Materials) {
    Material = /* TODO[bpr-expr]: K2Node_GetArrayItem (guid=946E130C-45F1-DA51-FD85-49B78F11CDE6) */;
    return;
}

