// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Tools/B_GeneratedTube_Advanced
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "BakedGeneratedMeshActor_C.h"
class UDynamicMesh;
class UMaterialInterface;

#include "B_GeneratedTube_Advanced.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_GeneratedTube_Advanced : public UBakedGeneratedMeshActor_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Revolve Options")
    double RevolveDegrees = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Revolve Options")
    double StartOffset = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Revolve Options")
    double Radius = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Revolve Options")
    double Thickness = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Revolve Options")
    int32 Steps = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Revolve Options")
    double Height = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    FVector VectorHandle;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    FVector ThicknessHandle;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Bevels")
    bool bBevel = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Bevels")
    double BevelDistance = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Revolve Options")
    TObjectPtr<UMaterialInterface> Material;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UDynamicMesh> DynamicMesh;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Repeater")
    bool bRepeaterWall = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Repeater")
    int32 Instances = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Repeater")
    double GapRevolvePercent = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Window")
    bool bWindow = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Window")
    bool bWindowDebug = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Window")
    bool WindowRepeater = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Window")
    bool bSyncInstanceToWall = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Window")
    double WindowWidth = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Window")
    double WindowHeight = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Window")
    double WindowHeightOffset = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Window")
    double WindowCornerRadius = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Window")
    int32 WindowStepRound = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Window")
    double WindowAngleOffset = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Window")
    double WindowCutterExtrude = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Window")
    int32 InstancesWindows = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UDynamicMesh> Window;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double RadiusWindowsOffset = 0.0;

    UFUNCTION(BlueprintCallable)
    UDynamicMesh* fnRepeater(UDynamicMesh* InputPin, int32 Instances);
    UFUNCTION(BlueprintCallable)
    void ApplyMaterials(const TArray<UMaterialInterface*>& Materials);
};
