// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_GrantInventoryPad_WithMesh.h"

UB_GrantInventoryPad_WithMesh::UB_GrantInventoryPad_WithMesh() {
    SkeletalMesh = CreateDefaultSubobject<USkeletalMeshComponent>(TEXT("SkeletalMesh"));
    RootComponent = SkeletalMesh;
    SkeletalMesh->RelativeLocation = FVector(0.0f, 0.0f, 67.0f);
    SkeletalMesh->RelativeScale3D = FVector(1.8f, 1.8f, 1.8f);
}

