// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Blueprint/B_GrantAbilityPad_ApplyGE
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
class UMaterialBillboardComponent;
class UMaterialInstanceDynamic;
class UPointLightComponent;
class USceneComponent;
class USphereComponent;
class UStaticMesh;
class UStaticMeshComponent;
class UTextRenderComponent;

#include "B_GrantAbilityPad_ApplyGE.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class AB_GrantAbilityPad_ApplyGE : public AActor {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TSubclassOf</Script/GameplayAbilities.GameplayEffect> GameplayEffectToApply;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FText TextToDisplay;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    F/Script/CoreUObject.LinearColor PadColor;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool bActive = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double Duration = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UMaterialInstanceDynamic> MID_TimerIndicator;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UStaticMesh> Mesh;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USceneComponent> DefaultSceneRoot;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USphereComponent> Volume;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UTextRenderComponent> Text;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> PadBase;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> Pad;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USceneComponent> Scene;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> ItemMesh;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UMaterialBillboardComponent> TimerIndicator;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UPointLightComponent> PointLight;

    AB_GrantAbilityPad_ApplyGE();

};
