// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Blueprint/B_GrantInventoryPad_WithMesh
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "B_GrantInventory_Pad_C.h"
class USkeletalMeshComponent;

#include "B_GrantInventoryPad_WithMesh.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_GrantInventoryPad_WithMesh : public UB_GrantInventory_Pad_C {
    GENERATED_BODY()
public:
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USkeletalMeshComponent> SkeletalMesh;

    UB_GrantInventoryPad_WithMesh();

};
