// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_GrantInventory_Pad.h"
#include "Components/SceneComponent.h"
#include "Components/SphereComponent.h"
#include "Components/TextRenderComponent.h"
#include "Components/StaticMeshComponent.h"

AB_GrantInventory_Pad::AB_GrantInventory_Pad() {
    DefaultSceneRoot = CreateDefaultSubobject<USceneComponent>(TEXT("DefaultSceneRoot"));
    Volume = CreateDefaultSubobject<USphereComponent>(TEXT("Volume"));
    Text = CreateDefaultSubobject<UTextRenderComponent>(TEXT("Text"));
    PadBase = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("PadBase"));
    Pad = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Pad"));
    Volume->SetupAttachment(DefaultSceneRoot);
    Text->SetupAttachment(DefaultSceneRoot);
    PadBase->SetupAttachment(DefaultSceneRoot);
    Pad->SetupAttachment(DefaultSceneRoot);
    RootComponent = DefaultSceneRoot;
    // TODO[bpr-comp-prop]: DefaultSceneRoot->bVisualizeComponent = true;
    // TODO[bpr-comp-prop]: Volume->SphereRadius = 110.0f;
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassFinder.Succeeded()) { /* TODO[bpr-comp-prop]: Volume->AreaClass = AreaClassFinder.Object; */ }
    }
    // TODO[bpr-comp-prop]: Volume->bUseSystemDefaultObstacleAreaClass = false;
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassOverrideFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassOverrideFinder.Succeeded()) { /* TODO[bpr-comp-prop]: Volume->AreaClassOverride = AreaClassOverrideFinder.Object; */ }
    }
    // TODO[bpr-component-default]: Volume->BodyInstance = /* StructProperty: (CollisionProfileName="Trigger",CollisionResponses=(ResponseArray=((Channel="WorldStatic",Response=ECR_Overlap),(Channel="WorldDynamic",Response=ECR_Overlap),(Channel="Pawn",Response=ECR_Overlap),(Channel="Visibility",Response=ECR_Ignore),(Channel="Camera",Response=ECR_Overlap),(Channel="PhysicsBody",Response=ECR_Overlap),(Channel="Vehicle",Response=ECR_Overlap),(Channel="Destructible",Response=ECR_Overlap)))) */;
    // TODO[bpr-comp-prop]: Text->Text = TEXT("NSLOCTEXT(\"[71D9014C41F2D482FB059BB7991E2A65]\", \"D0A00FC54C480DD66974159CB138B62A\", \"DAMAGE\")");
    // TODO[bpr-comp-prop]: Text->HorizontalAlignment = EHTA_Center;
    // TODO[bpr-comp-prop]: Text->VerticalAlignment = EVRTA_TextCenter;
    // TODO[bpr-comp-prop]: Text->WorldSize = 60.0f;
    // TODO[bpr-comp-prop]: Text->RelativeLocation = FVector(0.0f, 0.0f, 10.5f);
    // TODO[bpr-comp-prop]: Text->RelativeRotation = FRotator(90.0f, 180.0f, 0.0f);
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Engine/BasicShapes/Cylinder.Cylinder'"));
        if (StaticMeshFinder.Succeeded()) { /* TODO[bpr-comp-prop]: PadBase->StaticMesh = StaticMeshFinder.Object; */ }
    }
    // TODO[bpr-comp-prop]: PadBase->StaticMeshImportVersion = 1;
    // TODO[bpr-component-default]: PadBase->OverrideMaterials = /* ArrayProperty: ("/Script/Engine.Material'/Engine/EngineDebugMaterials/VertexColorMaterial.VertexColorMaterial'") */;
    // TODO[bpr-comp-prop]: PadBase->RelativeLocation = FVector(0.0f, 0.0f, -20.0f);
    // TODO[bpr-comp-prop]: PadBase->RelativeScale3D = FVector(2.25f, 2.25f, 0.346154f);
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Engine/BasicShapes/Cylinder.Cylinder'"));
        if (StaticMeshFinder.Succeeded()) { /* TODO[bpr-comp-prop]: Pad->StaticMesh = StaticMeshFinder.Object; */ }
    }
    // TODO[bpr-comp-prop]: Pad->StaticMeshImportVersion = 1;
    // TODO[bpr-component-default]: Pad->OverrideMaterials = /* ArrayProperty: ("/Script/Engine.Material'/Engine/BasicShapes/BasicShapeMaterial.BasicShapeMaterial'") */;
    // TODO[bpr-comp-prop]: Pad->RelativeLocation = FVector(0.0f, 0.0f, -15.0f);
    // TODO[bpr-comp-prop]: Pad->RelativeScale3D = FVector(2.0f, 2.0f, 0.333333f);
}

