// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_Grenade.h"
#include "Net/UnrealNetwork.h"

AB_Grenade::AB_Grenade() {
    ProjectileMovement = CreateDefaultSubobject<UProjectileMovementComponent>(TEXT("ProjectileMovement"));
    Mesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Mesh"));
    RootComponent = Mesh;
    ProjectileMovement->InitialSpeed = 2500.0f;
    ProjectileMovement->MaxSpeed = 2550.0f;
    ProjectileMovement->bShouldBounce = true;
    ProjectileMovement->bInterpMovement = true;
    ProjectileMovement->bInterpRotation = true;
    ProjectileMovement->Bounciness = 0.3f;
    ProjectileMovement->Friction = 0.8f;
    ProjectileMovement->BounceVelocityStopSimulatingThreshold = 25.0f;
    ProjectileMovement->MinFrictionFraction = 0.8f;
    ProjectileMovement->Velocity = FVector(1.0f, 0.0f, 0.15f);
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Game/Weapons/Grenade/Mesh/SM_grenade.SM_grenade'"));
        if (StaticMeshFinder.Succeeded()) { Mesh->StaticMesh = StaticMeshFinder.Object; }
    }
    // TODO[bpr-component-default]: Mesh->BodyInstance = /* StructProperty: (CollisionProfileName="Custom",CollisionResponses=(ResponseArray=((Channel="Visibility",Response=ECR_Ignore),(Channel="Camera",Response=ECR_Ignore))),LinearDamping=0.200000,AngularDamping=0.100000,MassScale=5.000000) */;
    Mesh->bCanEverAffectNavigation = false;
    bReplicates = true;
}

void AB_Grenade::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const {
    Super::GetLifetimeReplicatedProps(OutLifetimeProps);
    DOREPLIFETIME(AB_Grenade, Gameplay Tag);
}

void AB_Grenade::SetupVFX() {
    NiagaraFunctionLibrary::SpawnSystemAttached(TEXT("None"), Mesh, TEXT("0, 0, 0"), TEXT("KeepRelativeOffset"), TEXT("None"), TEXT("0, 0, 0"), nullptr, true, false, true);
    if (IsValid(NiagaraFunctionLibrary::SpawnSystemAttached(TEXT("None"), Mesh, TEXT("0, 0, 0"), TEXT("KeepRelativeOffset"), TEXT("None"), TEXT("0, 0, 0"), nullptr, true, false, true))) {
    }
}

