// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Blueprint/B_GrantInventory_Pad
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
class ULyraInventoryItemDefinition;
class USceneComponent;
class USkeletalMesh;
class USoundBase;
class USphereComponent;
class UStaticMeshComponent;
class UTextRenderComponent;

#include "B_GrantInventory_Pad.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class AB_GrantInventory_Pad : public AActor {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FLinearColor PadColor;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TSubclassOf<ULyraInventoryItemDefinition> ItemDefinition;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<USoundBase> PickUpSound;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool bDestroyOnPickup = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<USkeletalMesh> PickUpMesh;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USceneComponent> DefaultSceneRoot;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USphereComponent> Volume;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UTextRenderComponent> Text;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> PadBase;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> Pad;

    AB_GrantInventory_Pad();

};
