// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_GrantAbilityPad_ApplyGE.h"

AB_GrantAbilityPad_ApplyGE::AB_GrantAbilityPad_ApplyGE() {
    DefaultSceneRoot = CreateDefaultSubobject<USceneComponent>(TEXT("DefaultSceneRoot"));
    Volume = CreateDefaultSubobject<USphereComponent>(TEXT("Volume"));
    Text = CreateDefaultSubobject<UTextRenderComponent>(TEXT("Text"));
    PadBase = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("PadBase"));
    Pad = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Pad"));
    Scene = CreateDefaultSubobject<USceneComponent>(TEXT("Scene"));
    ItemMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("ItemMesh"));
    TimerIndicator = CreateDefaultSubobject<UMaterialBillboardComponent>(TEXT("TimerIndicator"));
    PointLight = CreateDefaultSubobject<UPointLightComponent>(TEXT("PointLight"));
    Volume->SetupAttachment(DefaultSceneRoot);
    Text->SetupAttachment(DefaultSceneRoot);
    PadBase->SetupAttachment(DefaultSceneRoot);
    Pad->SetupAttachment(DefaultSceneRoot);
    Scene->SetupAttachment(DefaultSceneRoot);
    ItemMesh->SetupAttachment(Scene);
    TimerIndicator->SetupAttachment(DefaultSceneRoot);
    PointLight->SetupAttachment(DefaultSceneRoot);
    RootComponent = DefaultSceneRoot;
    DefaultSceneRoot->bVisualizeComponent = true;
    Volume->SphereRadius = 150.0f;
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassFinder.Succeeded()) { Volume->AreaClass = AreaClassFinder.Object; }
    }
    Volume->bUseSystemDefaultObstacleAreaClass = false;
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassOverrideFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassOverrideFinder.Succeeded()) { Volume->AreaClassOverride = AreaClassOverrideFinder.Object; }
    }
    // TODO[bpr-component-default]: Volume->BodyInstance = /* StructProperty: (CollisionProfileName="Trigger",CollisionResponses=(ResponseArray=((Channel="WorldStatic",Response=ECR_Overlap),(Channel="WorldDynamic",Response=ECR_Overlap),(Channel="Pawn",Response=ECR_Overlap),(Channel="Visibility",Response=ECR_Ignore),(Channel="Camera",Response=ECR_Overlap),(Channel="PhysicsBody",Response=ECR_Overlap),(Channel="Vehicle",Response=ECR_Overlap),(Channel="Destructible",Response=ECR_Overlap)))) */;
    Volume->RelativeLocation = FVector(-0.0f, 0.0f, 136.730194f);
    Text->Text = TEXT("NSLOCTEXT(\"[B6FA4E4D457643687206F9AB614D7844]\", \"37CDC1814D54416FE2D8B0946EDC8797\", \"DAMAGE\")");
    Text->HorizontalAlignment = EHTA_Center;
    Text->VerticalAlignment = EVRTA_TextCenter;
    Text->WorldSize = 60.0f;
    Text->RelativeLocation = FVector(0.0f, 0.0f, 10.5f);
    Text->RelativeRotation = FRotator(90.0f, 180.0f, 0.0f);
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Engine/BasicShapes/Cylinder.Cylinder'"));
        if (StaticMeshFinder.Succeeded()) { PadBase->StaticMesh = StaticMeshFinder.Object; }
    }
    PadBase->StaticMeshImportVersion = 1;
    // TODO[bpr-component-default]: PadBase->OverrideMaterials = /* ArrayProperty: ("/Script/Engine.Material'/ShooterCore/Effects/Material/MT_BlackBorder.MT_BlackBorder'") */;
    PadBase->RelativeLocation = FVector(0.0f, 0.0f, -6.0f);
    PadBase->RelativeScale3D = FVector(3.25f, 3.25f, 0.125f);
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Engine/BasicShapes/Cylinder.Cylinder'"));
        if (StaticMeshFinder.Succeeded()) { Pad->StaticMesh = StaticMeshFinder.Object; }
    }
    Pad->StaticMeshImportVersion = 1;
    // TODO[bpr-component-default]: Pad->OverrideMaterials = /* ArrayProperty: ("/Script/Engine.Material'/Game/Environments/Gameplay/M_AdjustablePadColor.M_AdjustablePadColor'") */;
    Pad->RelativeLocation = FVector(0.0f, 0.0f, -3.0f);
    Pad->RelativeScale3D = FVector(3.0f, 3.0f, 0.25f);
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Game/Weapons/Healthpack/Mesh/SM_healthpackFull.SM_healthpackFull'"));
        if (StaticMeshFinder.Succeeded()) { ItemMesh->StaticMesh = StaticMeshFinder.Object; }
    }
    ItemMesh->StaticMeshImportVersion = 1;
    ItemMesh->RelativeLocation = FVector(-0.301328f, -5.455413f, 105.358215f);
    ItemMesh->RelativeRotation = FRotator(-9.99997f, 0.00001f, -10.000027f);
    ItemMesh->RelativeScale3D = FVector(3.0f, 3.0f, 3.0f);
    // TODO[bpr-component-default]: TimerIndicator->Elements = /* ArrayProperty: ((Material="/Script/Engine.MaterialInstanceConstant'/ShooterCore/Effects/Material/MI_WeaponSpawnerTimerIndicator.MI_WeaponSpawnerTimerIndicator'",BaseSizeX=75.000000,BaseSizeY=75.000000)) */;
    TimerIndicator->RelativeLocation = FVector(0.0f, 0.0f, 119.0f);
    PointLight->AttenuationRadius = 256.0f;
    PointLight->Intensity = 1200.0f;
    PointLight->CastShadows = false;
    PointLight->RelativeLocation = FVector(0.0f, 0.0f, 250.0f);
}

