// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Game/B_HandleShooterReplays
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "ControllerComponent.h"
class ULyraReplayPlayerController;

#include "B_HandleShooterReplays.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_HandleShooterReplays : public UControllerComponent {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<ULyraReplayPlayerController> AsLyraReplayPlayerController;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TSubclassOf</Script/UMG.UserWidget> WidgetToSpawn;

};
