// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Characters/Heroes/B_Hero_Default
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Character_Default_C.h"
class AIPerceptionStimuliSourceComponent;
class UAnimMontage;
class UB_FootStep;
class ULyraContextEffectComponent;
class ULyraHeroComponent;

#include "B_Hero_Default.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_Hero_Default : public UCharacter_Default_C, public ILyraContextEffectsInterface {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Ragdoll")
    double RagdollImpulseStrength = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Ragdoll")
    FName RagdollImpulseBone;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<TObjectPtr<UAnimMontage>> DeathMontages;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UB_FootStep> FootStep;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<ULyraHeroComponent> LyraHero;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<AIPerceptionStimuliSourceComponent> AIPerceptionStimuliSource;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<ULyraContextEffectComponent> LyraContextEffect;

    UB_Hero_Default();

    UFUNCTION(BlueprintCallable)
    void Ragdoll();
    UFUNCTION(BlueprintCallable)
    void Death();
    UFUNCTION(BlueprintCallable)
    void HideEquippedWeapons();
    UFUNCTION(BlueprintCallable)
    void UpdateCustomStencilFromTeamID(int32 TeamId);
};
