// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_Hero_ShooterMannequin.h"

UB_Hero_ShooterMannequin::UB_Hero_ShooterMannequin() {
    AimAssistTarget = CreateDefaultSubobject<UAimAssistTargetComponent>(TEXT("AimAssistTarget"));
    PawnCosmeticsComponent = CreateDefaultSubobject<UB_MannequinPawnCosmetics>(TEXT("PawnCosmeticsComponent"));
    RootComponent = PawnCosmeticsComponent;
    AimAssistTarget->CapsuleHalfHeight = 92.868629f;
    AimAssistTarget->CapsuleRadius = 41.280899f;
    AimAssistTarget->bUseSystemDefaultObstacleAreaClass = false;
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassOverrideFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassOverrideFinder.Succeeded()) { AimAssistTarget->AreaClassOverride = AreaClassOverrideFinder.Object; }
    }
    // TODO[bpr-component-default]: AimAssistTarget->BodyInstance = /* StructProperty: (ObjectType=ECC_PhysicsBody,CollisionProfileName="AimAssist_OverlapDynamic",CollisionResponses=(ResponseArray=((Channel="WorldStatic",Response=ECR_Ignore),(Channel="WorldDynamic",Response=ECR_Ignore),(Channel="Pawn",Response=ECR_Ignore),(Channel="Visibility",Response=ECR_Ignore),(Channel="Camera",Response=ECR_Ignore),(Channel="PhysicsBody",Response=ECR_Ignore),(Channel="Vehicle",Response=ECR_Ignore),(Channel="Destructible",Response=ECR_Ignore),(Channel="Lyra_TraceChannel_AimAssist",Response=ECR_Overlap)))) */;
}

void UB_Hero_ShooterMannequin::ChangeQuickbarSlot(int32 NewSlotIndex, const F/Script/GameplayTags.GameplayTag& SlotActionTag) {
    LyraQuickBarComponent::GetSlots();
    if (IsValid(/* TODO[bpr-expr]: K2Node_GetArrayItem (guid=FD3A09C6-46C9-5ACE-EB7A-F6ADCE10BC59) */)) {
    }
}

void UB_Hero_ShooterMannequin::AddInitialInventory() {
    // TODO[bpr-unsupported]: K2Node_MacroInstance (guid=26F0A45F-4968-0256-BB8C-1093164D441B) — manual port required.
    // Manual: Unrecognized BP node class 'K2Node_MacroInstance'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
}

void UB_Hero_ShooterMannequin::ClearInventory() {
    // TODO[bpr-unsupported]: K2Node_MacroInstance (guid=347EBCAC-4D2D-6C6D-F285-84861E9360AF) — manual port required.
    // Manual: Unrecognized BP node class 'K2Node_MacroInstance'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
}

void UB_Hero_ShooterMannequin::CreateOrUpdateOutlineIfNeeded(int32 TeamID, const F/Script/CoreUObject.LinearColor& OutlineColor) {
    if (IsLocallyControlled()) {
        MaterialInstanceDynamic::SetScalarParameterValue(TEXT("TeamID"), KismetMathLibrary::Conv_IntToDouble(TeamID));
    }
}

void UB_Hero_ShooterMannequin::OnRep_PlayerInfo() {
    OnTeamOrCosmeticsChanged(nullptr, 0);
}

void UB_Hero_ShooterMannequin::OnTeamOrCosmeticsChanged(int32 TeamID, ULyraTeamDisplayAsset* TeamDisplayAsset) {
    LyraTeamStatics::GetTeamColorWithFallback(TEXT("(R=0.645833,G=0.000000,B=0.568715,A=1.000000)"), TeamDisplayAsset, TEXT("TeamColor"));
    CreateOrUpdateOutlineIfNeeded(LyraTeamStatics::GetTeamColorWithFallback(TEXT("(R=0.645833,G=0.000000,B=0.568715,A=1.000000)"), TeamDisplayAsset, TEXT("TeamColor")), TeamID);
    UpdateCustomStencilFromTeamID(TeamID);
    if (IsValid(TeamDisplayAsset)) {
    }
}

void UB_Hero_ShooterMannequin::OnUnknownTriggered(const FInputActionValue& Value) {
    ChangeQuickbarSlot(0, TEXT("(TagName=\"InputTag.Ability.Quickslot.SelectSlot\")"));
}

void UB_Hero_ShooterMannequin::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent) {
    Super::SetupPlayerInputComponent(PlayerInputComponent);
    if (auto* EIC = Cast<UEnhancedInputComponent>(PlayerInputComponent)) {
        EIC->BindAction(IA_Unknown, ETriggerEvent::Triggered, this, &ThisClass::OnUnknownTriggered);
    }
}

