// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterTests/Blueprint/Messages/B_HeavyListener
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "HeavyPerformanceListener.h"
#include "B_HeavyListener.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_HeavyListener : public UHeavyPerformanceListener {
    GENERATED_BODY()
public:
};
