// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_Hero_Default.h"

UB_Hero_Default::UB_Hero_Default() {
    LyraHero = CreateDefaultSubobject<ULyraHeroComponent>(TEXT("LyraHero"));
    AIPerceptionStimuliSource = CreateDefaultSubobject<AIPerceptionStimuliSourceComponent>(TEXT("AIPerceptionStimuliSource"));
    LyraContextEffect = CreateDefaultSubobject<ULyraContextEffectComponent>(TEXT("LyraContextEffect"));
    RootComponent = LyraContextEffect;
    // TODO[bpr-component-default]: AIPerceptionStimuliSource->RegisterAsSourceForSenses = /* ArrayProperty: ("/Script/CoreUObject.Class'/Script/AIModule.AISense_Sight'","/Script/CoreUObject.Class'/Script/AIModule.AISense_Hearing'") */;
    // TODO[bpr-component-default]: LyraContextEffect->DefaultContextEffectsLibraries = /* SetProperty: ("/Game/ContextEffects/CFX_DefaultSkin.CFX_DefaultSkin") */;
}

void UB_Hero_Default::Ragdoll() {
    PrimitiveComponent::SetCollisionProfileName(TEXT("Ragdoll"), true);
    SkeletalMeshComponent::SetAllBodiesBelowSimulatePhysics(RagdollImpulseBone, true, true);
    PrimitiveComponent::AddImpulse(RagdollImpulseBone, /* TODO[bpr-expr]: K2Node_CommutativeAssociativeBinaryOperator (guid=730FBB46-47AD-68D8-CFDD-25A4ED93EFB5) */, true);
}

void UB_Hero_Default::Death() {
}

void UB_Hero_Default::HideEquippedWeapons() {
    if (IsValid(GetComponentByClass(nullptr))) {
    }
}

void UB_Hero_Default::UpdateCustomStencilFromTeamID(int32 TeamId) {
    StencilValue = (/* TODO[bpr-expr]: K2Node_CommutativeAssociativeBinaryOperator (guid=748ACD6D-4367-9441-376D-7995BD131E90) */ ? 0 : TeamId);
    LyraSystemStatics::FindComponentsByClass(nullptr, nullptr, true);
    for (auto& Element : LyraSystemStatics::FindComponentsByClass(nullptr, nullptr, true)) {
        PrimitiveComponent::SetCustomDepthStencilValue(StencilValue);
    }
}

