// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_HealPickup.h"

AB_HealPickup::AB_HealPickup() {
    Scene = CreateDefaultSubobject<USceneComponent>(TEXT("Scene"));
    Mesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Mesh"));
    Mesh->SetupAttachment(Scene);
    RootComponent = Scene;
    Scene->RelativeScale3D = FVector(10.0f, 10.0f, 10.0f);
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Game/Weapons/Healthpack/Mesh/SM_healthpackPart.SM_healthpackPart'"));
        if (StaticMeshFinder.Succeeded()) { Mesh->StaticMesh = StaticMeshFinder.Object; }
    }
    // TODO[bpr-component-default]: Mesh->OverrideMaterials = /* ArrayProperty: (None) */;
    Mesh->bGenerateOverlapEvents = false;
    Mesh->bApplyImpulseOnDamage = false;
    Mesh->bReplicatePhysicsToAutonomousProxy = false;
    // TODO[bpr-component-default]: Mesh->BodyInstance = /* StructProperty: (ObjectType=ECC_WorldStatic,CollisionEnabled=NoCollision,CollisionProfileName="NoCollision",CollisionResponses=(ResponseArray=((Channel="Visibility",Response=ECR_Ignore),(Channel="Camera",Response=ECR_Ignore))),bEnableGravity=False) */;
    // TODO[bpr-component-default]: Mesh->PrimaryComponentTick = /* StructProperty: (bStartWithTickEnabled=False) */;
}

