// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /TopDownArena/Game/B_Hero_Arena
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "B_Hero_Default_C.h"
class UB_MannequinPawnCosmetics;
class UStaticMeshComponent;

#include "B_Hero_Arena.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_Hero_Arena : public UB_Hero_Default_C {
    GENERATED_BODY()
public:
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> DirectionIndicatorMesh;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UB_MannequinPawnCosmetics> B_MannequinPawnCosmetics;

    UB_Hero_Arena();

    UFUNCTION(BlueprintCallable)
    void OnTeamorCosmeticsChanged(int32 TeamId, ULyraTeamDisplayAsset* TeamDisplayAsset);
};
