// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterTests/Blueprint/Messages/B_HeavyBroadcaster
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "HeavyPerformanceBroadcastor.h"
#include "B_HeavyBroadcaster.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_HeavyBroadcaster : public UHeavyPerformanceBroadcastor {
    GENERATED_BODY()
public:
};
