// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Game/B_Hero_ShooterMannequin
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "B_Hero_Default_C.h"
class UAimAssistTargetComponent;
class UAudioComponent;
class UB_MannequinPawnCosmetics;
class UInputAction;
class ULyraEquipmentInstance;
class UMaterialInstanceDynamic;

#include "B_Hero_ShooterMannequin.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_Hero_ShooterMannequin : public UB_Hero_Default_C, public IBI_EmoteSoundInterface_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<ULyraEquipmentInstance> EquippedWeapon;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TSubclassOf</Script/LyraGame.LyraEquipmentDefinition> WeaponID;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<TSubclassOf</Script/LyraGame.LyraInventoryItemDefinition>> InitialInventoryItems;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UMaterialInstanceDynamic> MPP_outlineMaterial;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<UAudioComponent> Emote_AudioComponent;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Input")
    TObjectPtr<UInputAction> IA_Unknown;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UAimAssistTargetComponent> AimAssistTarget;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UB_MannequinPawnCosmetics> PawnCosmeticsComponent;

    UB_Hero_ShooterMannequin();

    UFUNCTION(BlueprintCallable)
    void ChangeQuickbarSlot(int32 NewSlotIndex, const F/Script/GameplayTags.GameplayTag& SlotActionTag);
    UFUNCTION(BlueprintCallable)
    void AddInitialInventory();
    UFUNCTION(BlueprintCallable)
    void ClearInventory();
    UFUNCTION(BlueprintCallable)
    void CreateOrUpdateOutlineIfNeeded(int32 TeamID, const F/Script/CoreUObject.LinearColor& OutlineColor);
    UFUNCTION(BlueprintCallable)
    void OnRep_PlayerInfo();
    UFUNCTION(BlueprintCallable)
    void OnTeamOrCosmeticsChanged(int32 TeamID, ULyraTeamDisplayAsset* TeamDisplayAsset);
    UFUNCTION()
    void OnUnknownTriggered(const FInputActionValue& Value);
    virtual void SetupPlayerInputComponent(UInputComponent* PlayerInputComponent) override;
};
