// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterExplorer/Items/B_InteractableRock
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraWorldCollectable.h"
class UStaticMeshComponent;

#include "B_InteractableRock.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_InteractableRock : public ULyraWorldCollectable {
    GENERATED_BODY()
public:
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> StaticMesh;

    UB_InteractableRock();

};
