// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterTests/Input/DeviceColor/B_InputDeviceColor
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "ColorInputDeviceProperty.h"
#include "B_InputDeviceColor.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_InputDeviceColor : public UColorInputDeviceProperty {
    GENERATED_BODY()
public:
};
