// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_InteractableChair.h"

UB_InteractableChair::UB_InteractableChair() {
    Scene = CreateDefaultSubobject<USceneComponent>(TEXT("Scene"));
    Back = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Back"));
    Base = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Base"));
    SmartObject = CreateDefaultSubobject<USmartObjectComponent>(TEXT("SmartObject"));
    Back->SetupAttachment(Scene);
    Base->SetupAttachment(Scene);
    SmartObject->SetupAttachment(Scene);
    RootComponent = Scene;
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Engine/EngineMeshes/Cube.Cube'"));
        if (StaticMeshFinder.Succeeded()) { Back->StaticMesh = StaticMeshFinder.Object; }
    }
    // TODO[bpr-component-default]: Back->BodyInstance = /* StructProperty: (CollisionProfileName="Custom",CollisionResponses=(ResponseArray=((Channel="Lyra_TraceChannel_Interaction",Response=ECR_Overlap),(Channel="Lyra_TraceChannel_Weapon"),(Channel="Lyra_TraceChannel_Weapon_Capsule"),(Channel="Lyra_TraceChannel_Weapon_Multi")))) */;
    Back->RelativeScale3D = FVector(0.5f, 0.75f, 0.25f);
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Engine/EngineMeshes/Cube.Cube'"));
        if (StaticMeshFinder.Succeeded()) { Base->StaticMesh = StaticMeshFinder.Object; }
    }
    // TODO[bpr-component-default]: Base->BodyInstance = /* StructProperty: (CollisionProfileName="Custom",CollisionResponses=(ResponseArray=((Channel="Lyra_TraceChannel_Interaction",Response=ECR_Overlap),(Channel="Lyra_TraceChannel_Weapon"),(Channel="Lyra_TraceChannel_Weapon_Capsule"),(Channel="Lyra_TraceChannel_Weapon_Multi")))) */;
    Base->RelativeLocation = FVector(0.0f, -65.0f, 95.0f);
    Base->RelativeScale3D = FVector(0.5f, 0.25f, 0.5f);
}

