// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterExplorer/Items/B_InteractableChair
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraWorldCollectable.h"
class USceneComponent;
class USmartObjectComponent;
class UStaticMeshComponent;

#include "B_InteractableChair.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_InteractableChair : public ULyraWorldCollectable {
    GENERATED_BODY()
public:
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USceneComponent> Scene;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> Back;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> Base;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USmartObjectComponent> SmartObject;

    UB_InteractableChair();

};
