// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_InteractableRock.h"
#include "Components/StaticMeshComponent.h"

UB_InteractableRock::UB_InteractableRock() {
    StaticMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("StaticMesh"));
    RootComponent = StaticMesh;
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Engine/EngineMeshes/Cube.Cube'"));
        if (StaticMeshFinder.Succeeded()) { /* TODO[bpr-comp-prop]: StaticMesh->StaticMesh = StaticMeshFinder.Object; */ }
    }
    // TODO[bpr-component-default]: StaticMesh->BodyInstance = /* StructProperty: (CollisionProfileName="Custom") */;
}

