// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_InteractableRock.h"

UB_InteractableRock::UB_InteractableRock() {
    StaticMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("StaticMesh"));
    RootComponent = StaticMesh;
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Engine/EngineMeshes/Cube.Cube'"));
        if (StaticMeshFinder.Succeeded()) { StaticMesh->StaticMesh = StaticMeshFinder.Object; }
    }
    // TODO[bpr-component-default]: StaticMesh->BodyInstance = /* StructProperty: (CollisionProfileName="Custom",CollisionResponses=(ResponseArray=((Channel="Lyra_TraceChannel_Interaction",Response=ECR_Overlap),(Channel="Lyra_TraceChannel_Weapon"),(Channel="Lyra_TraceChannel_Weapon_Capsule"),(Channel="Lyra_TraceChannel_Weapon_Multi")))) */;
}

