// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Blueprint/B_Launcher
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
class ACharacter;
class UPointLightComponent;
class USceneComponent;
class USphereComponent;
class UStaticMeshComponent;

#include "B_Launcher.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class AB_Launcher : public AActor {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Launcher")
    TObjectPtr<ACharacter> OverlappingPawn;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Launcher")
    FLinearColor LightColor;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Launcher")
    double LightIntensity = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Launcher")
    double LightAttenuation = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Launcher")
    float GlowIntensity = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Launcher")
    double SphereRadius = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Launcher")
    FGameplayTag GameplayTag;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Launcher")
    bool DoNotActivateonFallEntry = false;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USceneComponent> DefaultSceneRoot;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> LauncherMesh;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UPointLightComponent> PointLight;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USphereComponent> Sphere;

    AB_Launcher();

    UFUNCTION(BlueprintCallable)
    bool Overlap();
};
