// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Blueprint/B_Launcher_Up
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "B_Launcher_C.h"
#include "B_Launcher_Up.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_Launcher_Up : public UB_Launcher_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Launcher")
    double UpOverride = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Launcher")
    double MinimumVerticalVelocityAllowed = 0.0;

    UFUNCTION(BlueprintCallable)
    bool Overlap();
};
