// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_Launcher.h"

AB_Launcher::AB_Launcher() {
    DefaultSceneRoot = CreateDefaultSubobject<USceneComponent>(TEXT("DefaultSceneRoot"));
    LauncherMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("LauncherMesh"));
    PointLight = CreateDefaultSubobject<UPointLightComponent>(TEXT("PointLight"));
    Sphere = CreateDefaultSubobject<USphereComponent>(TEXT("Sphere"));
    LauncherMesh->SetupAttachment(DefaultSceneRoot);
    PointLight->SetupAttachment(DefaultSceneRoot);
    Sphere->SetupAttachment(DefaultSceneRoot);
    RootComponent = DefaultSceneRoot;
    DefaultSceneRoot->bVisualizeComponent = true;
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Game/Weapons/Spawnpad/Mesh/SM_launchpad_Square.SM_launchpad_Square'"));
        if (StaticMeshFinder.Succeeded()) { LauncherMesh->StaticMesh = StaticMeshFinder.Object; }
    }
    LauncherMesh->StaticMeshImportVersion = 1;
    // TODO[bpr-component-default]: LauncherMesh->OverrideMaterials = /* ArrayProperty: (None,None) */;
    LauncherMesh->RelativeLocation = FVector(0.0f, 0.0f, -1.240211f);
    PointLight->AttenuationRadius = 360.0f;
    PointLight->CastShadows = false;
    PointLight->RelativeLocation = FVector(0.0f, -0.0f, 129.65239f);
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassFinder.Succeeded()) { Sphere->AreaClass = AreaClassFinder.Object; }
    }
    Sphere->bUseSystemDefaultObstacleAreaClass = false;
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassOverrideFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassOverrideFinder.Succeeded()) { Sphere->AreaClassOverride = AreaClassOverrideFinder.Object; }
    }
    // TODO[bpr-component-default]: Sphere->BodyInstance = /* StructProperty: (CollisionProfileName="Custom",CollisionResponses=(ResponseArray=((Channel="WorldStatic",Response=ECR_Ignore),(Channel="WorldDynamic",Response=ECR_Ignore),(Channel="Pawn",Response=ECR_Overlap),(Channel="Visibility",Response=ECR_Ignore),(Channel="Camera",Response=ECR_Ignore),(Channel="PhysicsBody",Response=ECR_Ignore),(Channel="Vehicle",Response=ECR_Ignore),(Channel="Destructible",Response=ECR_Ignore)))) */;
    Sphere->RelativeLocation = FVector(-0.0f, 0.0f, 83.148697f);
}

bool AB_Launcher::Overlap() {
    return true;
}

