// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Environments/B_LoadRandomLobbyBackground
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
class UBillboardComponent;
class UBoxComponent;
class ULoadingProcessTask;
class USceneComponent;

#include "B_LoadRandomLobbyBackground.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class AB_LoadRandomLobbyBackground : public AActor {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FPrimaryAssetId BackgroundToLoad;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FVector BoxExtents;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<ULoadingProcessTask> LoadingScreenTask;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UBillboardComponent> EditorOnlyBillboard;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USceneComponent> Scene;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UBoxComponent> EditorOnlyBox;

    AB_LoadRandomLobbyBackground();

};
