// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_LoadRandomLobbyBackground.h"
#include "Components/BillboardComponent.h"
#include "Components/SceneComponent.h"
#include "Components/BoxComponent.h"

AB_LoadRandomLobbyBackground::AB_LoadRandomLobbyBackground() {
    EditorOnlyBillboard = CreateDefaultSubobject<UBillboardComponent>(TEXT("EditorOnlyBillboard"));
    Scene = CreateDefaultSubobject<USceneComponent>(TEXT("Scene"));
    EditorOnlyBox = CreateDefaultSubobject<UBoxComponent>(TEXT("EditorOnlyBox"));
    EditorOnlyBillboard->SetupAttachment(Scene);
    EditorOnlyBox->SetupAttachment(Scene);
    RootComponent = Scene;
    // TODO[bpr-comp-prop]: EditorOnlyBillboard->bIsEditorOnly = true;
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassFinder.Succeeded()) { /* TODO[bpr-comp-prop]: EditorOnlyBox->AreaClass = AreaClassFinder.Object; */ }
    }
    // TODO[bpr-comp-prop]: EditorOnlyBox->bUseSystemDefaultObstacleAreaClass = false;
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassOverrideFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassOverrideFinder.Succeeded()) { /* TODO[bpr-comp-prop]: EditorOnlyBox->AreaClassOverride = AreaClassOverrideFinder.Object; */ }
    }
    // TODO[bpr-component-default]: EditorOnlyBox->BodyInstance = /* StructProperty: (ObjectType=ECC_WorldStatic,CollisionEnabled=NoCollision,CollisionProfileName="NoCollision",CollisionResponses=(ResponseArray=((Channel="Visibility",Response=ECR_Ignore),(Channel="Camera",Response=ECR_Ignore)))) */;
    // TODO[bpr-comp-prop]: EditorOnlyBox->bIsEditorOnly = true;
}

