// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/B_LyraGameInstance
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraGameInstance.h"
class UAudioComponent;

#include "B_LyraGameInstance.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_LyraGameInstance : public ULyraGameInstance {
    GENERATED_BODY()
public:
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<UAudioComponent> MusicSystem;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<UAudioComponent> Audio_LobbySelect;

};
