// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/B_LyraUIPolicy
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameUIPolicy.h"
#include "B_LyraUIPolicy.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_LyraUIPolicy : public UGameUIPolicy {
    GENERATED_BODY()
public:
};
