// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/B_LyraGameMode
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraGameMode.h"
class USceneComponent;

#include "B_LyraGameMode.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_LyraGameMode : public ULyraGameMode {
    GENERATED_BODY()
public:
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USceneComponent> DefaultSceneRoot;

    UB_LyraGameMode();

};
