// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/System/Experiences/B_LyraDefaultExperience
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraExperienceDefinition.h"
#include "B_LyraDefaultExperience.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_LyraDefaultExperience : public ULyraExperienceDefinition {
    GENERATED_BODY()
public:
};
