// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_LyraGameMode.h"

UB_LyraGameMode::UB_LyraGameMode() {
    DefaultSceneRoot = CreateDefaultSubobject<USceneComponent>(TEXT("DefaultSceneRoot"));
    RootComponent = DefaultSceneRoot;
    DefaultSceneRoot->bVisualizeComponent = true;
}

