// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/System/FrontEnd/B_LyraFrontEnd_Experience
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraExperienceDefinition.h"
#include "B_LyraFrontEnd_Experience.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_LyraFrontEnd_Experience : public ULyraExperienceDefinition {
    GENERATED_BODY()
public:
};
