// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_Manny.h"

AB_Manny::AB_Manny() {
    MeshComponent = CreateDefaultSubobject<USkeletalMeshComponent>(TEXT("MeshComponent"));
    RootComponent = MeshComponent;
    {
        static ConstructorHelpers::FObjectFinder<UClass> AnimClassFinder(TEXT("/Script/Engine.AnimBlueprintGeneratedClass'/Game/Characters/Heroes/Mannequin/Animations/ABP_Mannequin_CopyPose.ABP_Mannequin_CopyPose_C'"));
        if (AnimClassFinder.Succeeded()) { MeshComponent->AnimClass = AnimClassFinder.Object; }
    }
    {
        static ConstructorHelpers::FObjectFinder<USkeletalMesh> SkeletalMeshFinder(TEXT("/Script/Engine.SkeletalMesh'/Game/Characters/Heroes/Mannequin/Meshes/SKM_Manny.SKM_Manny'"));
        if (SkeletalMeshFinder.Succeeded()) { MeshComponent->SkeletalMesh = SkeletalMeshFinder.Object; }
    }
    {
        static ConstructorHelpers::FObjectFinder<USkinnedAsset> SkinnedAssetFinder(TEXT("/Script/Engine.SkeletalMesh'/Game/Characters/Heroes/Mannequin/Meshes/SKM_Manny.SKM_Manny'"));
        if (SkinnedAssetFinder.Succeeded()) { MeshComponent->SkinnedAsset = SkinnedAssetFinder.Object; }
    }
    MeshComponent->bEnableMaterialParameterCaching = true;
    MeshComponent->bRenderCustomDepth = true;
}

