// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Characters/Cosmetics/B_MannequinPawnCosmetics
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraPawnComponent_CharacterParts.h"
#include "B_MannequinPawnCosmetics.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_MannequinPawnCosmetics : public ULyraPawnComponent_CharacterParts {
    GENERATED_BODY()
public:
};
