// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Characters/Cosmetics/B_Manny
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraTaggedActor.h"
class USkeletalMeshComponent;

#include "B_Manny.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class AB_Manny : public ALyraTaggedActor {
    GENERATED_BODY()
public:
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USkeletalMeshComponent> MeshComponent;

    AB_Manny();

};
