// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_MusicManagerComponent_Base.h"

void AB_MusicManagerComponent_Base::SetIsMenu(bool InBool) {
    if (IsValid(MusicSystem)) {
    }
}

