// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/ControlPoint/B_MusicManagerComponent_ControlPoint
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "B_MusicManagerComponent_Base_C.h"
#include "B_MusicManagerComponent_ControlPoint.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_MusicManagerComponent_ControlPoint : public UB_MusicManagerComponent_Base_C {
    GENERATED_BODY()
public:
};
