// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Audio/Blueprints/B_MusicManagerComponent_Base
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "ActorComponent.h"
class UAudioComponent;

#include "B_MusicManagerComponent_Base.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class AB_MusicManagerComponent_Base : public AActorComponent {
    GENERATED_BODY()
public:
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<UAudioComponent> MusicSystem;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double Alpha_Intensity = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double Alpha_Mvmt = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool bIsMenu = false;

    UFUNCTION(BlueprintCallable)
    void SetIsMenu(bool InBool);
};
