// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Audio/Blueprints/B_MusicManagerComponent_FE
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "B_MusicManagerComponent_Base_C.h"
#include "B_MusicManagerComponent_FE.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_MusicManagerComponent_FE : public UB_MusicManagerComponent_Base_C {
    GENERATED_BODY()
public:
};
