// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Weapons/NetShooter_PROTO/B_NetShooter
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
class UArrowComponent;
class UProjectileMovementComponent;
class UStaticMeshComponent;

#include "B_NetShooter.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class AB_NetShooter : public AActor {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 NumberOfWeb = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Default")
    FVector End;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FHitResult HitBreakResult;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double LifeTime = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Default")
    TArray<FVector> TargetDirection;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Default")
    FVector Start;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double DistanceTrace = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double OffsetImpact = 0.0;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UProjectileMovementComponent> ProjectileMovement;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> Sphere;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UArrowComponent> Arrow;

    AB_NetShooter();

    virtual void GetLifetimeReplicatedProps(TArray<class FLifetimeProperty>& OutLifetimeProps) const override;

};
