// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Effects/Blueprints/B_NiagaraNumberPopComponent
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraNumberPopComponent_NiagaraText.h"
#include "B_NiagaraNumberPopComponent.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_NiagaraNumberPopComponent : public ULyraNumberPopComponent_NiagaraText {
    GENERATED_BODY()
public:
};
