// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterExplorer/Blueprint/B_Pawn_Explorer
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "B_Hero_Default_C.h"
class UAimAssistTargetComponent;
class UAudioComponent;
class UB_MannequinPawnCosmetics;
class UBehaviorTree;
class UContextualAnimSceneActorComponent;
class UInputAction;
class ULyraEquipmentInstance;
class UMaterialInstanceDynamic;
class UMotionWarpingComponent;
class UStateTreeComponent;
class UTextRenderComponent;

#include "B_Pawn_Explorer.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_Pawn_Explorer : public UB_Hero_Default_C, public IBI_EmoteSoundInterface_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<ULyraEquipmentInstance> EquippedWeapon;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TSubclassOf</Script/LyraGame.LyraEquipmentDefinition> WeaponID;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<TSubclassOf</Script/LyraGame.LyraInventoryItemDefinition>> InitialInventoryItems;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UMaterialInstanceDynamic> MPP_outlineMaterial_0;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<UAudioComponent> Emote_AudioComponent;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="AI")
    bool UseBhvTree = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="AI")
    TObjectPtr<UBehaviorTree> BhvTree;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Input")
    TObjectPtr<UInputAction> IA_Unknown;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UAimAssistTargetComponent> AimAssistTarget;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UB_MannequinPawnCosmetics> PawnCosmeticsComponent;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStateTreeComponent> StateTree;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UTextRenderComponent> TextRender;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UMotionWarpingComponent> MotionWarping;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UContextualAnimSceneActorComponent> ContextualAnimSceneActor;

    UB_Pawn_Explorer();

    UFUNCTION(BlueprintCallable)
    void ChangeQuickbarSlot(int32 NewSlotIndex, const F/Script/GameplayTags.GameplayTag& SlotActionTag);
    UFUNCTION(BlueprintCallable)
    void AddInitialInventory();
    UFUNCTION(BlueprintCallable)
    void ClearInventory();
    UFUNCTION(BlueprintCallable)
    void CreateOrUpdateOutlineIfNeeded(int32 TeamID, const F/Script/CoreUObject.LinearColor& OutlineColor);
    UFUNCTION(BlueprintCallable)
    void OnRep_PlayerInfo();
    UFUNCTION(BlueprintCallable)
    void OnTeamOrCosmeticsChanged(int32 TeamID, ULyraTeamDisplayAsset* TeamDisplayAsset);
    UFUNCTION(BlueprintCallable)
    void UseBehaviorTree(AController* Controller);
    UFUNCTION()
    void OnUnknownTriggered(const FInputActionValue& Value);
    virtual void SetupPlayerInputComponent(UInputComponent* PlayerInputComponent) override;
};
