// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_Pawn_Explorer.h"

UB_Pawn_Explorer::UB_Pawn_Explorer() {
    AimAssistTarget = CreateDefaultSubobject<UAimAssistTargetComponent>(TEXT("AimAssistTarget"));
    PawnCosmeticsComponent = CreateDefaultSubobject<UB_MannequinPawnCosmetics>(TEXT("PawnCosmeticsComponent"));
    StateTree = CreateDefaultSubobject<UStateTreeComponent>(TEXT("StateTree"));
    TextRender = CreateDefaultSubobject<UTextRenderComponent>(TEXT("TextRender"));
    MotionWarping = CreateDefaultSubobject<UMotionWarpingComponent>(TEXT("MotionWarping"));
    ContextualAnimSceneActor = CreateDefaultSubobject<UContextualAnimSceneActorComponent>(TEXT("ContextualAnimSceneActor"));
    RootComponent = ContextualAnimSceneActor;
    AimAssistTarget->CapsuleHalfHeight = 92.868629f;
    AimAssistTarget->CapsuleRadius = 41.280899f;
    AimAssistTarget->bUseSystemDefaultObstacleAreaClass = false;
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassOverrideFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassOverrideFinder.Succeeded()) { AimAssistTarget->AreaClassOverride = AreaClassOverrideFinder.Object; }
    }
    // TODO[bpr-component-default]: AimAssistTarget->BodyInstance = /* StructProperty: (ObjectType=ECC_PhysicsBody,CollisionProfileName="AimAssist_OverlapDynamic",CollisionResponses=(ResponseArray=((Channel="WorldStatic",Response=ECR_Ignore),(Channel="WorldDynamic",Response=ECR_Ignore),(Channel="Pawn",Response=ECR_Ignore),(Channel="Visibility",Response=ECR_Ignore),(Channel="Camera",Response=ECR_Ignore),(Channel="PhysicsBody",Response=ECR_Ignore),(Channel="Vehicle",Response=ECR_Ignore),(Channel="Destructible",Response=ECR_Ignore),(Channel="Lyra_TraceChannel_AimAssist",Response=ECR_Overlap)))) */;
    // TODO[bpr-component-default]: StateTree->StateTreeRef = /* StructProperty: (StateTree="/Script/StateTreeModule.StateTree'/ShooterExplorer/AI/StateTrees/Trees/L_STT_FollowPlayer.L_STT_FollowPlayer'",Parameters=(Value=/Engine/Transient.PropertyBag_3b275584a6a97f(StopDistance=200.000000,StartFollowDistance=1000.000000)),PropertyOverrides=(ACC942484299C3890748C595B70B6423,FECED8984F9D196B220D27B6D5AA1C74)) */;
    TextRender->HorizontalAlignment = EHTA_Center;
    TextRender->RelativeLocation = FVector(0.0f, 0.0f, 105.0f);
}

void UB_Pawn_Explorer::ChangeQuickbarSlot(int32 NewSlotIndex, const F/Script/GameplayTags.GameplayTag& SlotActionTag) {
    LyraQuickBarComponent::GetSlots();
    if (IsValid(/* TODO[bpr-expr]: K2Node_GetArrayItem (guid=186CED38-4C71-D791-278C-BC97089803C8) */)) {
    }
}

void UB_Pawn_Explorer::AddInitialInventory() {
    // TODO[bpr-unsupported]: K2Node_MacroInstance (guid=B1D42380-40B4-3877-CF4D-F18059A8AA63) — manual port required.
    // Manual: Unrecognized BP node class 'K2Node_MacroInstance'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
}

void UB_Pawn_Explorer::ClearInventory() {
    // TODO[bpr-unsupported]: K2Node_MacroInstance (guid=4F6E9866-4871-AC95-F773-DFA80EE6E85E) — manual port required.
    // Manual: Unrecognized BP node class 'K2Node_MacroInstance'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
}

void UB_Pawn_Explorer::CreateOrUpdateOutlineIfNeeded(int32 TeamID, const F/Script/CoreUObject.LinearColor& OutlineColor) {
    if (IsLocallyControlled()) {
        MaterialInstanceDynamic::SetScalarParameterValue(TEXT("TeamID"), KismetMathLibrary::Conv_IntToDouble(TeamID));
    }
}

void UB_Pawn_Explorer::OnRep_PlayerInfo() {
    OnTeamOrCosmeticsChanged(nullptr, 0);
}

void UB_Pawn_Explorer::OnTeamOrCosmeticsChanged(int32 TeamID, ULyraTeamDisplayAsset* TeamDisplayAsset) {
    LyraTeamStatics::GetTeamColorWithFallback(TEXT("(R=0.645833,G=0.000000,B=0.568715,A=1.000000)"), TeamDisplayAsset, TEXT("TeamColor"));
    CreateOrUpdateOutlineIfNeeded(LyraTeamStatics::GetTeamColorWithFallback(TEXT("(R=0.645833,G=0.000000,B=0.568715,A=1.000000)"), TeamDisplayAsset, TEXT("TeamColor")), TeamID);
    UpdateCustomStencilFromTeamID(TeamID);
    if (IsValid(TeamDisplayAsset)) {
    }
}

void UB_Pawn_Explorer::UseBehaviorTree(AController* Controller) {
    if (UseBhvTree) {
        ActorComponent::K2_DestroyComponent(nullptr);
        AIController::RunBehaviorTree(BhvTree);
    }
}

void UB_Pawn_Explorer::OnUnknownTriggered(const FInputActionValue& Value) {
    ChangeQuickbarSlot(0, TEXT("(TagName=\"InputTag.Ability.Quickslot.SelectSlot\")"));
}

void UB_Pawn_Explorer::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent) {
    Super::SetupPlayerInputComponent(PlayerInputComponent);
    if (auto* EIC = Cast<UEnhancedInputComponent>(PlayerInputComponent)) {
        EIC->BindAction(IA_Unknown, ETriggerEvent::Triggered, this, &ThisClass::OnUnknownTriggered);
    }
}

