// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Weapons/Pistol/B_Pistol
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "B_Weapon_C.h"
#include "B_Pistol.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_Pistol : public UB_Weapon_C {
    GENERATED_BODY()
public:
};
