// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Characters/Cosmetics/B_PickRandomCharacter
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraControllerComponent_CharacterParts.h"
#include "B_PickRandomCharacter.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_PickRandomCharacter : public ULyraControllerComponent_CharacterParts {
    GENERATED_BODY()
public:
};
