// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /TopDownArena/UserInterface/Player/B_PlayerUIComponent
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "PlayerStateComponent.h"
#include "B_PlayerUIComponent.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_PlayerUIComponent : public UPlayerStateComponent {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    F/Script/UIExtension.UIExtensionHandle ExtensionHandle;

};
