// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Game/B_QuickBarComponent
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraQuickBarComponent.h"
#include "B_QuickBarComponent.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_QuickBarComponent : public ULyraQuickBarComponent {
    GENERATED_BODY()
public:
};
