// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Weapons/Rifle/B_Rifle
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "B_Weapon_C.h"
#include "B_Rifle.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_Rifle : public UB_Weapon_C {
    GENERATED_BODY()
public:
};
