// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_ShooterGameScoring_Base.h"

void UB_ShooterGameScoring_Base::ResetAllActivePlayers() {
    GameplayStatics::GetAllActorsOfClass(this, nullptr, nullptr);
    for (auto& Element : GameplayStatics::GetAllActorsOfClass(this, nullptr, nullptr)) {
        if (IsValid(AbilitySystemBlueprintLibrary::GetAbilitySystemComponent(/* TODO[bpr-expr]: K2Node_MacroInstance (guid=1249B4E6-4EC4-0CC7-4E49-D8889D4A89DA) */))) {
        }
    }
}

void UB_ShooterGameScoring_Base::PostWarmup() {
    GameplayStatics::GetAllActorsOfClass(this, nullptr, nullptr);
    for (auto& Element : GameplayStatics::GetAllActorsOfClass(this, nullptr, nullptr)) {
        if (IsValid(/* TODO[bpr-expr]: K2Node_MacroInstance (guid=E2FD81B6-4771-CCC6-AA0C-97B31321081D) */)) {
        }
    }
    GameplayStatics::GetAllActorsOfClass(this, nullptr, nullptr);
    for (auto& Element : GameplayStatics::GetAllActorsOfClass(this, nullptr, nullptr)) {
        if (IsValid(/* TODO[bpr-expr]: K2Node_MacroInstance (guid=750069D6-4EE6-45C1-8B0B-8483847285E7) */)) {
        }
    }
}

