// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/ControlPoint/AI/B_ShooterBotSpawner_ControlPoint
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraBotCreationComponent.h"
#include "B_ShooterBotSpawner_ControlPoint.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_ShooterBotSpawner_ControlPoint : public ULyraBotCreationComponent {
    GENERATED_BODY()
public:
};
