// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Weapons/Tests/B_ShootingTarget
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraCharacterWithAbilities.h"
class ULyraDamageLogDebuggerComponent;
class UStaticMeshComponent;

#include "B_ShootingTarget.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_ShootingTarget : public ULyraCharacterWithAbilities {
    GENERATED_BODY()
public:
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> Cube;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<ULyraDamageLogDebuggerComponent> LyraDamageLogDebugger;

    UB_ShootingTarget();

};
