// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Experiences/B_ShooterGame_Elimination
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraExperienceDefinition.h"
#include "B_ShooterGame_Elimination.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_ShooterGame_Elimination : public ULyraExperienceDefinition {
    GENERATED_BODY()
public:
};
