// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_ShootingTarget.h"
#include "Components/StaticMeshComponent.h"
#include "Components/LyraDamageLogDebuggerComponent.h"

UB_ShootingTarget::UB_ShootingTarget() {
    Cube = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Cube"));
    LyraDamageLogDebugger = CreateDefaultSubobject<ULyraDamageLogDebuggerComponent>(TEXT("LyraDamageLogDebugger"));
    RootComponent = LyraDamageLogDebugger;
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Engine/BasicShapes/Cube.Cube'"));
        if (StaticMeshFinder.Succeeded()) { /* TODO[bpr-comp-prop]: Cube->StaticMesh = StaticMeshFinder.Object; */ }
    }
    // TODO[bpr-component-default]: Cube->BodyInstance = /* StructProperty: (ObjectType=ECC_Pawn,CollisionEnabled=QueryOnly,CollisionProfileName="Custom",CollisionResponses=(ResponseArray=((Channel="WorldStatic",Response=ECR_Ignore),(Channel="Pawn",Response=ECR_Ignore),(Channel="Camera",Response=ECR_Ignore),(Channel="PhysicsBody",Response=ECR_Ignore),(Channel="Vehicle",Response=ECR_Ignore),(Channel="Destructible",Response=ECR_Ignore)))) */;
    // TODO[bpr-comp-prop]: Cube->RelativeLocation = FVector(0.0f, 0.0f, -100.0f);
    // TODO[bpr-comp-prop]: Cube->RelativeScale3D = FVector(4.0f, 4.0f, 4.0f);
}

