// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Bot/B_ShooterBotSpawner_Perf
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraBotCreationComponent.h"
class UB_PerfTestSpawner;

#include "B_ShooterBotSpawner_Perf.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_ShooterBotSpawner_Perf : public ULyraBotCreationComponent {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 NumActorsToCreate = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<TObjectPtr<UB_PerfTestSpawner>> ActorSpawners;

};
