// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_SimpleFollowPawn.h"
#include "Components/StateTreeComponent.h"

UB_SimpleFollowPawn::UB_SimpleFollowPawn() {
    StateTree = CreateDefaultSubobject<UStateTreeComponent>(TEXT("StateTree"));
    RootComponent = StateTree;
    // TODO[bpr-component-default]: StateTree->StateTreeRef = /* StructProperty: (StateTree="/Script/StateTreeModule.StateTree'/ShooterExplorer/AI/StateTrees/Trees/L_STT_FollowPlayer.L_STT_FollowPlayer'",Parameters=(Value=/Engine/Transient.PropertyBag_548fe7633725313d(StopDistance=200.000000)),PropertyOverrides=(ACC942484299C3890748C595B70B6423)) */;
}

