// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Characters/Heroes/B_SimpleHeroPawn
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "B_Hero_Default_C.h"
class UStaticMeshComponent;

#include "B_SimpleHeroPawn.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_SimpleHeroPawn : public UB_Hero_Default_C {
    GENERATED_BODY()
public:
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> Sphere;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> Cylinder;

    UB_SimpleHeroPawn();

};
