// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_SimpleHeroPawn.h"

UB_SimpleHeroPawn::UB_SimpleHeroPawn() {
    Sphere = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Sphere"));
    Cylinder = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Cylinder"));
    RootComponent = Cylinder;
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Engine/BasicShapes/Sphere.Sphere'"));
        if (StaticMeshFinder.Succeeded()) { Sphere->StaticMesh = StaticMeshFinder.Object; }
    }
    // TODO[bpr-component-default]: Sphere->OverrideMaterials = /* ArrayProperty: ("/Script/Engine.Material'/Game/Characters/Heroes/M_SimpleHeroPawn.M_SimpleHeroPawn'") */;
    // TODO[bpr-component-default]: Sphere->BodyInstance = /* StructProperty: (ObjectType=ECC_Pawn,CollisionEnabled=QueryOnly,CollisionProfileName="CharacterMesh",CollisionResponses=(ResponseArray=((Channel="Pawn",Response=ECR_Ignore),(Channel="Visibility",Response=ECR_Ignore),(Channel="Vehicle",Response=ECR_Ignore)))) */;
    Sphere->RelativeLocation = FVector(0.0f, 0.0f, 50.0f);
    Sphere->RelativeScale3D = FVector(0.5f, 0.5f, 0.5f);
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Engine/BasicShapes/Cylinder.Cylinder'"));
        if (StaticMeshFinder.Succeeded()) { Cylinder->StaticMesh = StaticMeshFinder.Object; }
    }
    Cylinder->StaticMeshImportVersion = 1;
    // TODO[bpr-component-default]: Cylinder->OverrideMaterials = /* ArrayProperty: ("/Script/Engine.Material'/Game/Characters/Heroes/M_SimpleHeroPawn.M_SimpleHeroPawn'") */;
    // TODO[bpr-component-default]: Cylinder->BodyInstance = /* StructProperty: (ObjectType=ECC_Pawn,CollisionEnabled=QueryOnly,CollisionProfileName="CharacterMesh",CollisionResponses=(ResponseArray=((Channel="Pawn",Response=ECR_Ignore),(Channel="Visibility",Response=ECR_Ignore),(Channel="Vehicle",Response=ECR_Ignore)))) */;
    Cylinder->RelativeLocation = FVector(0.0f, 0.0f, -20.0f);
    Cylinder->RelativeScale3D = FVector(0.5f, 0.5f, 0.8f);
}

