// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterExplorer/Blueprint/B_SimpleFollowPawn
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "B_SimpleHeroPawn_C.h"
class UStateTreeComponent;

#include "B_SimpleFollowPawn.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_SimpleFollowPawn : public UB_SimpleHeroPawn_C {
    GENERATED_BODY()
public:
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStateTreeComponent> StateTree;

    UB_SimpleFollowPawn();

};
