// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterTests/Blueprint/B_Test_FireWeapon
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "B_Test_Base_C.h"
#include "B_Test_FireWeapon.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_Test_FireWeapon : public UB_Test_Base_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 StartingAmmoCount = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 EndingAmmoCount = 0;

};
