// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/System/DefaultEditorMap/B_TeleportToUserFacingExperience
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
class UCapsuleComponent;
class ULyraUserFacingExperienceDefinition;
class UNiagaraComponent;
class USceneComponent;
class UStaticMeshComponent;
class UWidgetComponent;

#include "B_TeleportToUserFacingExperience.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class AB_TeleportToUserFacingExperience : public AActor {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<ULyraUserFacingExperienceDefinition> UserFacingExperienceToLoad;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USceneComponent> Scene;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UCapsuleComponent> CollisionCapsule;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> StaticMesh;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UNiagaraComponent> NS_GunPad;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UWidgetComponent> Widget;

    AB_TeleportToUserFacingExperience();

};
