// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Elimination/B_TeamDeathMatchScoring
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "B_ShooterGameScoring_Base_C.h"
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FCountDownUpdate, float, Time);
// TODO[bpr-delegate-signature]: fill in delegate params from BP signature graph (the zero-arg form below is a placeholder).
DECLARE_DYNAMIC_MULTICAST_DELEGATE(FPlayerCounted);

#include "GameplayTagContainer.h"

#include "B_TeamDeathMatchScoring.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_TeamDeathMatchScoring : public UB_ShooterGameScoring_Base_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Default")
    int32 TargetScore = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 WinningTeamId = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FGameplayTag ActiveUserFacingCue;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double WaitForPlayersDuration = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FPlayerCounted PlayerCounted;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Default")
    double CountDownTime = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FCountDownUpdate CountDownUpdate;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 Team0Score = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 Team1Score = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FTimerHandle TimerCountdown;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool BigTeam = false;

    virtual void GetLifetimeReplicatedProps(TArray<class FLifetimeProperty>& OutLifetimeProps) const override;

    UFUNCTION(BlueprintCallable)
    void GetTeamScore(int32 TeamId, int32& CurrentScore, int32& TargetScore, bool& Victory);
    UFUNCTION(BlueprintCallable)
    void OnEliminationScored();
    UFUNCTION(BlueprintCallable)
    void SetDamageEnabled(bool AllowDamage);
    UFUNCTION(BlueprintCallable)
    void ActivateUserFacingCue(const FGameplayTag& GameplayCueTag, const FGameplayCueParameters& Parameters);
    UFUNCTION(BlueprintCallable)
    void ClearUserFacingCue();
    UFUNCTION(BlueprintCallable)
    void RestartAllPlayers();
    UFUNCTION(BlueprintCallable)
    void HandleVictory(int32 TeamId);
    UFUNCTION(BlueprintCallable)
    void OnRep_TargetScore();
    UFUNCTION(BlueprintCallable)
    void OnRep_CountDownTime();
};
