// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /TopDownArena/Game/B_TeamSetup_FourTeams
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraTeamCreationComponent.h"
#include "B_TeamSetup_FourTeams.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_TeamSetup_FourTeams : public ULyraTeamCreationComponent {
    GENERATED_BODY()
public:
};
