// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_Test_AutoRun.h"
#include "Components/BoxComponent.h"

UB_Test_AutoRun::UB_Test_AutoRun() {
    Target Point = CreateDefaultSubobject<UBoxComponent>(TEXT("Target Point"));
    RootComponent = Target Point;
    // TODO[bpr-comp-prop]: Target Point->BoxExtent = FVector(100.0f, 100.0f, 32.0f);
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassFinder.Succeeded()) { /* TODO[bpr-comp-prop]: Target Point->AreaClass = AreaClassFinder.Object; */ }
    }
}

