// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_TeamDeathMatchScoring.h"
#include "Net/UnrealNetwork.h"

void UB_TeamDeathMatchScoring::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const {
    Super::GetLifetimeReplicatedProps(OutLifetimeProps);
    DOREPLIFETIME(UB_TeamDeathMatchScoring, TargetScore);
    DOREPLIFETIME(UB_TeamDeathMatchScoring, CountDownTime);
}

void UB_TeamDeathMatchScoring::GetTeamScore(int32 TeamId, int32& CurrentScore, int32& TargetScore, bool& Victory) {
    CurrentScore = LyraTeamSubsystem::GetTeamTagStackCount(TEXT("(TagName=\"ShooterGame.Score.Eliminations\")"), TeamId);
    TargetScore = TargetScore;
    Victory = /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=7BE89457-49C4-B307-6477-57A10D15C97A) */;
    return;
}

void UB_TeamDeathMatchScoring::OnEliminationScored() {
    Super::OnEliminationScored();
    // TODO[bpr-unsupported]: K2Node_MacroInstance (guid=D52B90DC-447D-EC56-5F9C-1D96043A0970) — manual port required.
    // Manual: Unrecognized BP node class 'K2Node_MacroInstance'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
}

void UB_TeamDeathMatchScoring::SetDamageEnabled(bool AllowDamage) {
    NumPlayerStates = /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=76CF798D-4A73-7BC0-1405-CE98D92BEEF7) */;
    // TODO[bpr-unsupported]: K2Node_MacroInstance (guid=66509AA4-4BF3-7C1C-810D-D9B762D93D09) — manual port required.
    // Manual: Unrecognized BP node class 'K2Node_MacroInstance'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
}

void UB_TeamDeathMatchScoring::ActivateUserFacingCue(const F/Script/GameplayTags.GameplayTag& GameplayCueTag, const F/Script/GameplayAbilities.GameplayCueParameters& Parameters) {
    ClearUserFacingCue();
    ActiveUserFacingCue = GameplayCueTag;
    GameplayCueFunctionLibrary::AddGameplayCueOnActor(/* TODO[bpr-expr]: K2Node_VariableSet (guid=7CBCE752-4B5A-5976-3D8D-EB8606A9CAC0) */, Parameters, GameplayStatics::GetGameState(this, nullptr));
    return;
}

void UB_TeamDeathMatchScoring::ClearUserFacingCue() {
    if (BlueprintGameplayTagLibrary::IsGameplayTagValid(ActiveUserFacingCue)) {
        GameplayCueFunctionLibrary::RemoveGameplayCueOnActor(ActiveUserFacingCue, AbilitySystemBlueprintLibrary::MakeGameplayCueParameters(1, nullptr, nullptr, nullptr, nullptr, 1, nullptr, TEXT("0,0,0"), nullptr, TEXT("0,0,0"), 0f, nullptr, nullptr, 0f, nullptr, nullptr, false), GameplayStatics::GetGameState(this, nullptr));
        ActiveUserFacingCue = nullptr;
    }
}

void UB_TeamDeathMatchScoring::RestartAllPlayers() {
    GameMode = GameplayStatics::GetGameMode(this, nullptr);
    LastControllerIndex = /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=992664DA-4777-5030-9F5D-0ABCC1CAD305) */;
    // TODO[bpr-unsupported]: K2Node_MacroInstance (guid=F8550A2E-45A6-360F-40D8-37905D833D80) — manual port required.
    // Manual: Unrecognized BP node class 'K2Node_MacroInstance'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
}

void UB_TeamDeathMatchScoring::HandleVictory(int32 TeamId) {
    WinningTeamId = TeamId;
    ActivateUserFacingCue(TEXT("(TagName=\"GameplayCue.ShooterGame.UserMessage.MatchDecided\")"), AbilitySystemBlueprintLibrary::MakeGameplayCueParameters(WinningTeamId, nullptr, nullptr, nullptr, nullptr, 1, nullptr, TEXT("0,0,0"), nullptr, TEXT("0,0,0"), 0f, nullptr, nullptr, 0f, nullptr, nullptr, false));
    LyraGamePhaseSubsystem::K2_StartPhase(nullptr, nullptr);
}

void UB_TeamDeathMatchScoring::OnRep_TargetScore() {
    PlayerCounted.Broadcast();
}

void UB_TeamDeathMatchScoring::OnRep_CountDownTime() {
    CountDownUpdate.Broadcast(CountDownTime);
}

