// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_Test_Base.h"

bool UB_Test_Base::IsReady() {
    if (auto* AsBHeroShooterMannequin = Cast</ShooterCore/Game/B_Hero_ShooterMannequin.B_Hero_ShooterMannequin>(GameplayStatics::GetPlayerPawn(this, 0, nullptr))) {
        Hero = Cast</ShooterCore/Game/B_Hero_ShooterMannequin.B_Hero_ShooterMannequin>(GameplayStatics::GetPlayerPawn(this, 0, nullptr));
        return KismetSystemLibrary::IsValid(/* TODO[bpr-expr]: K2Node_VariableSet (guid=3A4BFF93-4D07-CE72-7E6F-8387A74CA0FC) */);
    }
    return false;
}

