// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_TeleportToUserFacingExperience.h"

AB_TeleportToUserFacingExperience::AB_TeleportToUserFacingExperience() {
    Scene = CreateDefaultSubobject<USceneComponent>(TEXT("Scene"));
    CollisionCapsule = CreateDefaultSubobject<UCapsuleComponent>(TEXT("CollisionCapsule"));
    StaticMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("StaticMesh"));
    NS_GunPad = CreateDefaultSubobject<UNiagaraComponent>(TEXT("NS_GunPad"));
    Widget = CreateDefaultSubobject<UWidgetComponent>(TEXT("Widget"));
    CollisionCapsule->SetupAttachment(Scene);
    StaticMesh->SetupAttachment(Scene);
    NS_GunPad->SetupAttachment(StaticMesh);
    Widget->SetupAttachment(Scene);
    RootComponent = Scene;
    CollisionCapsule->CapsuleHalfHeight = 80.0f;
    CollisionCapsule->CapsuleRadius = 80.0f;
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassFinder.Succeeded()) { CollisionCapsule->AreaClass = AreaClassFinder.Object; }
    }
    CollisionCapsule->bUseSystemDefaultObstacleAreaClass = false;
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassOverrideFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassOverrideFinder.Succeeded()) { CollisionCapsule->AreaClassOverride = AreaClassOverrideFinder.Object; }
    }
    // TODO[bpr-component-default]: CollisionCapsule->BodyInstance = /* StructProperty: (CollisionProfileName="OverlapOnlyPawn",CollisionResponses=(ResponseArray=((Channel="Pawn",Response=ECR_Overlap),(Channel="Camera",Response=ECR_Ignore),(Channel="Vehicle",Response=ECR_Overlap)))) */;
    CollisionCapsule->RelativeLocation = FVector(0.0f, 0.0f, 100.0f);
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Game/Weapons/Spawnpad/Mesh/SM_launchpad_Round.SM_launchpad_Round'"));
        if (StaticMeshFinder.Succeeded()) { StaticMesh->StaticMesh = StaticMeshFinder.Object; }
    }
    // TODO[bpr-component-default]: StaticMesh->OverrideMaterials = /* ArrayProperty: (None,None) */;
    {
        static ConstructorHelpers::FObjectFinder<UNiagaraSystem> AssetFinder(TEXT("/Script/Niagara.NiagaraSystem'/Game/Effects/Particles/Item/NS_GunPad.NS_GunPad'"));
        if (AssetFinder.Succeeded()) { NS_GunPad->Asset = AssetFinder.Object; }
    }
    // TODO[bpr-component-default]: NS_GunPad->OverrideParameters = /* StructProperty: (UserParameterRedirects=(((Name="ExplosionDelay",TypeDefHandle=(RegisteredTypeIndex=95)), (Name="User.ExplosionDelay",TypeDefHandle=(RegisteredTypeIndex=95))),((Name="GunPad_Color",TypeDefHandle=(RegisteredTypeIndex=102)), (Name="User.GunPad_Color",TypeDefHandle=(RegisteredTypeIndex=102))),((Name="Luminosity",TypeDefHandle=(RegisteredTypeIndex=95)), (Name="User.Luminosity",TypeDefHandle=(RegisteredTypeIndex=95)))),SortedParameterOffsets=((Offset=20,Name="User.ExplosionDelay",TypeDefHandle=(RegisteredTypeIndex=95)),(Offset=0,Name="User.GunPad_Color",TypeDefHandle=(RegisteredTypeIndex=102)),(Offset=16,Name="User.Luminosity",TypeDefHandle=(RegisteredTypeIndex=95))),ParameterData=(165,135,225,61,178,130,111,62,0,0,128,63,0,0,128,63,0,0,128,63,0,0,0,0)) */;
    // TODO[bpr-component-default]: NS_GunPad->TemplateParameterOverrides = /* MapProperty: (((Name="User.GunPad_Color",TypeDefHandle=(RegisteredTypeIndex=102)), (Bytes=(165,135,225,61,178,130,111,62,0,0,128,63,0,0,128,63),CurrentMode=Bytes)),((Name="User.Luminosity",TypeDefHandle=(RegisteredTypeIndex=95)), (Bytes=(0,0,128,63),CurrentMode=Bytes))) */;
    NS_GunPad->bVisibleInRayTracing = false;
    {
        static ConstructorHelpers::FObjectFinder<UClass> WidgetClassFinder(TEXT("/Script/UMG.WidgetBlueprintGeneratedClass'/Game/UI/Menu/Experiences/W_ExperienceTile.W_ExperienceTile_C'"));
        if (WidgetClassFinder.Succeeded()) { Widget->WidgetClass = WidgetClassFinder.Object; }
    }
    Widget->DrawSize = FVector2D(512.0f, 384.0f);
    Widget->TickMode = Automatic;
    // TODO[bpr-component-default]: Widget->OverrideMaterials = /* ArrayProperty: ("/Script/Engine.Material'/Engine/EngineMaterials/Widget3DPassThrough.Widget3DPassThrough'") */;
    Widget->RelativeLocation = FVector(-0.0f, -146.814331f, 200.0f);
    Widget->RelativeRotation = FRotator(0.0f, 89.999999f, -0.0f);
    Widget->RelativeScale3D = FVector(0.75f, 0.75f, 0.75f);
    // TODO[bpr-component-default]: Widget->PrimaryComponentTick = /* StructProperty: (bAllowTickOnDedicatedServer=False) */;
}

