// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Game/B_TeamSpawningRules
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "TDM_PlayerSpawningManagmentComponent.h"
#include "B_TeamSpawningRules.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_TeamSpawningRules : public UTDM_PlayerSpawningManagmentComponent {
    GENERATED_BODY()
public:
};
