// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Game/B_TeamColor_DeviceProperty
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "ColorInputDeviceProperty.h"
#include "B_TeamColor_DeviceProperty.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_TeamColor_DeviceProperty : public UColorInputDeviceProperty {
    GENERATED_BODY()
public:
};
