// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Game/B_TeamSetup_TwoTeams
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraTeamCreationComponent.h"
#include "B_TeamSetup_TwoTeams.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_TeamSetup_TwoTeams : public ULyraTeamCreationComponent {
    GENERATED_BODY()
public:
};
