// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Characters/Cosmetics/B_TinplateUE4
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraTaggedActor.h"
class AActor;
class USkeletalMeshComponent;
class UStaticMeshComponent;

#include "B_TinplateUE4.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class AB_TinplateUE4 : public ALyraTaggedActor {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<AActor> NewVar_0;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USkeletalMeshComponent> Mannequin_UE4;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> Sphere;

    AB_TinplateUE4();

};
