// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_Tool_Panel_BGM.h"

UDynamicMesh* UB_Tool_Panel_BGM::fnBevel(UDynamicMesh* TargetMesh, double OptionsBevelDistance) {
    GeometryScriptLibrary_MeshPolygroupFunctions::ComputePolygroupsFromAngleThreshold(25f, nullptr, nullptr, 2, TargetMesh);
    GeometryScriptLibrary_MeshModelingFunctions::ApplyMeshPolygroupBevel(nullptr, nullptr, OptionsBevelDistance, TEXT("(Min=(X=0.000000,Y=0.000000,Z=0.000000),Max=(X=0.000000,Y=0.000000,Z=0.000000),IsValid=False)"), TEXT("0.000000,0.000000,0.000000|0.000000,0.000000,-0.000000|1.000000,1.000000,1.000000"), 1f, 0, 0, TEXT("False"), TEXT("True"), true, GeometryScriptLibrary_MeshPolygroupFunctions::ComputePolygroupsFromAngleThreshold(25f, nullptr, nullptr, 2, TargetMesh));
    GeometryScriptLibrary_MeshNormalsFunctions::ComputeSplitNormals(nullptr, TEXT("True"), TEXT("True"), nullptr, nullptr, TEXT("(bDefaultLayer=True,ExtendedLayerIndex=0)"), 25f, TEXT("False"), TEXT("True"), GeometryScriptLibrary_MeshModelingFunctions::ApplyMeshPolygroupBevel(nullptr, nullptr, OptionsBevelDistance, TEXT("(Min=(X=0.000000,Y=0.000000,Z=0.000000),Max=(X=0.000000,Y=0.000000,Z=0.000000),IsValid=False)"), TEXT("0.000000,0.000000,0.000000|0.000000,0.000000,-0.000000|1.000000,1.000000,1.000000"), 1f, 0, 0, TEXT("False"), TEXT("True"), true, GeometryScriptLibrary_MeshPolygroupFunctions::ComputePolygroupsFromAngleThreshold(25f, nullptr, nullptr, 2, TargetMesh)));
    return GeometryScriptLibrary_MeshNormalsFunctions::ComputeSplitNormals(nullptr, TEXT("True"), TEXT("True"), nullptr, nullptr, TEXT("(bDefaultLayer=True,ExtendedLayerIndex=0)"), 25f, TEXT("False"), TEXT("True"), GeometryScriptLibrary_MeshModelingFunctions::ApplyMeshPolygroupBevel(nullptr, nullptr, OptionsBevelDistance, TEXT("(Min=(X=0.000000,Y=0.000000,Z=0.000000),Max=(X=0.000000,Y=0.000000,Z=0.000000),IsValid=False)"), TEXT("0.000000,0.000000,0.000000|0.000000,0.000000,-0.000000|1.000000,1.000000,1.000000"), 1f, 0, 0, TEXT("False"), TEXT("True"), true, GeometryScriptLibrary_MeshPolygroupFunctions::ComputePolygroupsFromAngleThreshold(25f, nullptr, nullptr, 2, TargetMesh)));
}

void UB_Tool_Panel_BGM::ApplyMaterials(const TArray<UMaterialInterface*>& Materials) {
    MaterialPanel = /* TODO[bpr-expr]: K2Node_GetArrayItem (guid=521915F8-4D25-7F3C-3F95-BDB755C40CDB) */;
    MaterialTopper = /* TODO[bpr-expr]: K2Node_GetArrayItem (guid=BFDC23F3-415A-9C3D-A794-69B7C26D860F) */;
    return;
}

