// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Tools/B_Tool_Repeater
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "BakedGeneratedMeshActor_C.h"
class UDynamicMesh;
class UMaterialInterface;
class USplineComponent;

#include "B_Tool_Repeater.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_Tool_Repeater : public UBakedGeneratedMeshActor_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UDynamicMesh> TargetMesh;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Repeater")
    int32 NumberOfPieces = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Repeater")
    float Height = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Repeater")
    float Depth = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Repeater")
    float Width = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double i = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UDynamicMesh> CollisionSweep;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<FVector> Direction;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|SimplifiedCollision")
    bool SimplifiedCollision = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|SimplifiedCollision")
    bool bPreviewSimplifiedturnOFFBEFOREBAKE = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|SimplifiedCollision")
    double OffsetCollision = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|SimplifiedCollision")
    double CollisionDepthAdditive = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|SimplifiedCollision")
    double CollisionWidthAdditive = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Bevel")
    bool bBevel = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Bevel")
    float OptionsBevelDistance = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Repeater")
    TObjectPtr<UMaterialInterface> Material;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<FVector2D> CollisionShape;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<FVector> CollisionStartPoints;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<FVector> CollisionEndPoints;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double CollisionOffset = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Simplified Collision")
    double CollisionGeoTolerance = 0.0;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USplineComponent> Spline;

    UB_Tool_Repeater();

    UFUNCTION(BlueprintCallable)
    void ApplyMaterials(const TArray<UMaterialInterface*>& Materials);
    UFUNCTION(BlueprintCallable)
    void MakeCollisionSpansPointSet(const TArray<FVector>& InputPoints, double LineDeviationTol, const TArray<FVector>&& StartPoints, const TArray<FVector>&& EndPoints);
};
