// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /TopDownArena/Game/Modes/B_TopDownArena_GameComponent_Base
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameStateComponent.h"
#include "B_TopDownArena_GameComponent_Base.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_TopDownArena_GameComponent_Base : public UGameStateComponent {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Default")
    bool IsPlaying = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Default")
    double ServerWorld_GameEndTime = 0.0;

    virtual void GetLifetimeReplicatedProps(TArray<class FLifetimeProperty>& OutLifetimeProps) const override;

    UFUNCTION(BlueprintCallable)
    void GetRoundTimeRemaining(double& SecondsRemaining, double& SecondsRemaining);
};
