// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Tools/B_Tool_Stairs_BGM
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "BakedGeneratedMeshActor_C.h"
class UDynamicMesh;
class UMaterialInterface;

#include "B_Tool_Stairs_BGM.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_Tool_Stairs_BGM : public UBakedGeneratedMeshActor_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    F/Script/CoreUObject.Vector Handle;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    uint8 Type = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    double StepHeight = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    int32 NumSteps = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UDynamicMesh> TargetMesh;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    bool Floating = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    TObjectPtr<UMaterialInterface> Material;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Simplified")
    bool bPreviewSimplifiedturnOFFBEFOREBAKE = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Simplified")
    double OffsetSimplifiedStep = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Simplified")
    bool bSimplifiedCollision = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UDynamicMesh> Simplified;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Simplified")
    bool bTriangle = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Bevel")
    bool bBevel = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Bevel")
    double DistanceBevel = 0.0;

    UFUNCTION(BlueprintCallable)
    void ApplyMaterials(const TArray<UMaterialInterface*>& Materials);
};
