// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /TopDownArena/System/Experiences/B_TopDownArena_Multiplayer_Experience
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraExperienceDefinition.h"
#include "B_TopDownArena_Multiplayer_Experience.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_TopDownArena_Multiplayer_Experience : public ULyraExperienceDefinition {
    GENERATED_BODY()
public:
};
