// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_TopDownArena_GameComponent_Base.h"
#include "Net/UnrealNetwork.h"

void UB_TopDownArena_GameComponent_Base::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const {
    Super::GetLifetimeReplicatedProps(OutLifetimeProps);
    DOREPLIFETIME(UB_TopDownArena_GameComponent_Base, IsPlaying);
    DOREPLIFETIME(UB_TopDownArena_GameComponent_Base, ServerWorld_GameEndTime);
}

void UB_TopDownArena_GameComponent_Base::GetRoundTimeRemaining(double& SecondsRemaining, double& SecondsRemaining) {
    if (IsPlaying) {
        return /* TODO[bpr-expr]: K2Node_CommutativeAssociativeBinaryOperator (guid=191C0947-4DAF-B670-5FDD-B480B018A6C3) */;
    } else {
        return 0f;
    }
    SecondsRemaining = nullptr;
    SecondsRemaining = nullptr;
    return;
}

