// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Tools/B_Tool_RampMakerControl_BGM
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "BakedGeneratedMeshActor_C.h"
class UMaterialInterface;

#include "B_Tool_RampMakerControl_BGM.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_Tool_RampMakerControl_BGM : public UBakedGeneratedMeshActor_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    F/Script/CoreUObject.Vector TopPoint;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    F/Script/CoreUObject.Vector FloorPoint;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UMaterialInterface> Material;

};
