// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_Tool_CornerExtrude.h"

void UB_Tool_CornerExtrude::ApplyMaterials(const TArray<UMaterialInterface*>& Materials) {
    Material = /* TODO[bpr-expr]: K2Node_GetArrayItem (guid=5D9BB86D-4D87-6CAF-EC73-B89B5B4F69E9) */;
    return;
}

