// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_TopDownArena_Pickup.h"
#include "Net/UnrealNetwork.h"
#include "Components/SceneComponent.h"
#include "Components/SphereComponent.h"
#include "Components/NiagaraComponent.h"

AB_TopDownArena_Pickup::AB_TopDownArena_Pickup() {
    DefaultSceneRoot = CreateDefaultSubobject<USceneComponent>(TEXT("DefaultSceneRoot"));
    Volume = CreateDefaultSubobject<USphereComponent>(TEXT("Volume"));
    VFX = CreateDefaultSubobject<UNiagaraComponent>(TEXT("VFX"));
    Volume->SetupAttachment(DefaultSceneRoot);
    VFX->SetupAttachment(DefaultSceneRoot);
    RootComponent = DefaultSceneRoot;
    // TODO[bpr-comp-prop]: DefaultSceneRoot->bVisualizeComponent = true;
    // TODO[bpr-comp-prop]: Volume->SphereRadius = 48.0f;
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassFinder.Succeeded()) { /* TODO[bpr-comp-prop]: Volume->AreaClass = AreaClassFinder.Object; */ }
    }
    // TODO[bpr-comp-prop]: Volume->bUseSystemDefaultObstacleAreaClass = false;
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassOverrideFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassOverrideFinder.Succeeded()) { /* TODO[bpr-comp-prop]: Volume->AreaClassOverride = AreaClassOverrideFinder.Object; */ }
    }
    // TODO[bpr-component-default]: Volume->BodyInstance = /* StructProperty: (CollisionProfileName="Trigger",CollisionResponses=(ResponseArray=((Channel="WorldStatic",Response=ECR_Overlap),(Channel="WorldDynamic",Response=ECR_Overlap),(Channel="Pawn",Response=ECR_Overlap),(Channel="Visibility",Response=ECR_Ignore),(Channel="Camera",Response=ECR_Overlap),(Channel="PhysicsBody",Response=ECR_Overlap),(Channel="Vehicle",Response=ECR_Overlap),(Channel="Destructible",Response=ECR_Overlap)))) */;
    {
        static ConstructorHelpers::FObjectFinder<UNiagaraSystem> AssetFinder(TEXT("/Script/Niagara.NiagaraSystem'/TopDownArena/Game/Effects/PickUp/NS_TopDownArenaPickupBomb.NS_TopDownArenaPickupBomb'"));
        if (AssetFinder.Succeeded()) { /* TODO[bpr-comp-prop]: VFX->Asset = AssetFinder.Object; */ }
    }
    // TODO[bpr-component-default]: VFX->OverrideParameters = /* StructProperty: () */;
    bReplicates = true;
}

void AB_TopDownArena_Pickup::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const {
    Super::GetLifetimeReplicatedProps(OutLifetimeProps);
    DOREPLIFETIME(AB_TopDownArena_Pickup, GameplayEffectToApply);
}

void AB_TopDownArena_Pickup::OnRep_GameplayEffectToApply() {
    AbilitySystemBlueprintLibrary::GetGameplayEffectUIData(nullptr, GameplayEffectToApply);
    if (IsValid(AbilitySystemBlueprintLibrary::GetGameplayEffectUIData(nullptr, GameplayEffectToApply))) {
    }
}

