// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /TopDownArena/Game/Modes/B_TopDownArena_GameComponent_SpawnLocalPlayers
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "B_TopDownArena_GameComponent_Base_C.h"
#include "B_TopDownArena_GameComponent_SpawnLocalPlayers.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_TopDownArena_GameComponent_SpawnLocalPlayers : public UB_TopDownArena_GameComponent_Base_C {
    GENERATED_BODY()
public:
};
