// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Tools/B_Tool_CornerExtrude
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "BakedGeneratedMeshActor_C.h"
class UDynamicMesh;
class UMaterialInterface;

#include "B_Tool_CornerExtrude.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_Tool_CornerExtrude : public UBakedGeneratedMeshActor_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    FVector Handle;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    double Radius = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    double ExtrudeCeiling = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    TObjectPtr<UMaterialInterface> Material;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    bool bMirror = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UDynamicMesh> DynamicMesh;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    double MirrorOffset = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    bool bBevels = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    double BevelDistance = 0.0;

    UFUNCTION(BlueprintCallable)
    void ApplyMaterials(const TArray<UMaterialInterface*>& Materials);
};
