// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Tools/B_Tool_AdvancedWindow
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "BakedGeneratedMeshActor_C.h"
class UDynamicMesh;
class UMaterialInterface;

#include "B_Tool_AdvancedWindow.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_Tool_AdvancedWindow : public UBakedGeneratedMeshActor_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Wall")
    uint8 WallCorner = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Wall")
    double WallCornerRadius = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Wall")
    int32 WallStepsRound = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Wall")
    double WallWidth = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Wall")
    double WallThickness = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Wall")
    double WallHeight = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Opening")
    uint8 OpeningType = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Opening")
    double OpeningWidth = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Opening")
    double OpeningHeight = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Opening")
    double CornerRadius = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Opening")
    int32 StepsRound = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Opening")
    bool bOpeningBorder = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Opening")
    double OpeningBorderThickness = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Opening")
    double OpeningBorderExtrude = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Opening")
    TObjectPtr<UMaterialInterface> MaterialOpeningBorder;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Opening")
    F/Script/CoreUObject.Vector Opening;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UDynamicMesh> Window;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UDynamicMesh> WindowBorder;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UDynamicMesh> DynamicMEsh;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Cutter")
    bool bGroundCutter = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Wall")
    TObjectPtr<UMaterialInterface> MaterialWall;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Glass")
    bool bHasGlass = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Glass")
    double GlassThickness = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Glass")
    TObjectPtr<UMaterialInterface> MaterialGlass;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Trim")
    bool bHasTrim = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Trim")
    uint8 TrimType = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Trim")
    double TrimHeight = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Trim")
    double TrimThickness = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Trim")
    TObjectPtr<UMaterialInterface> MaterialTrim;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Trim")
    bool bVertical = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Extend Walls")
    bool bExtendWall = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Extend Walls")
    double Radius = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Extend Walls")
    int32 Steps = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Extend Walls")
    double ExtensionLenght = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Cutter")
    double GroundCutterOffset = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Cutter")
    bool bTopCutter = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Cutter")
    double TopCutterOffset = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Cutter")
    bool bLeftCutter = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Cutter")
    double LeftCutterOffset = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Cutter")
    bool bRightCutter = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Cutter")
    double RightCutterOffset = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Mirror")
    bool bMirror = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Mirror")
    uint8 MirrorAxis = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Mirror")
    bool bUseHandleForMirror = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Mirror")
    F/Script/CoreUObject.Vector MirrorLocation;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    F/Script/CoreUObject.Rotator MirrorAxis_;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UDynamicMesh> BaseWall;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Mirror")
    F/Script/CoreUObject.Rotator MirrorRotation;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Cutter")
    bool bCustomCutter = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Cutter")
    F/Script/CoreUObject.Vector CustomCutter;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Cutter")
    F/Script/CoreUObject.Rotator CustomCutterRotation;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Bevel")
    bool bBevelCombine = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Bevel")
    double BevelDistanceCombine = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Bevel")
    bool bBevelWall = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Bevel")
    double BevelDistanceWall = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Bevel")
    bool bBevelWindowBorder = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Bevel")
    double BevelDistanceWindowBorder = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Bevel")
    bool bBevelWindow = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Bevel")
    double BevelDistanceWindow = 0.0;

    UFUNCTION(BlueprintCallable)
    void fnCreateTrim(uint8 Index);
    UFUNCTION(BlueprintCallable)
    void fnCreateExtend();
    UFUNCTION(BlueprintCallable)
    void fnCreateExtendTrim(uint8 Type);
    UFUNCTION(BlueprintCallable)
    UDynamicMesh* fnBevel(UDynamicMesh* TargetMesh, double OptionsBevelDistance);
    UFUNCTION(BlueprintCallable)
    void ApplyMaterials(const TArray<UMaterialInterface*>& Materials);
};
