// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Tools/B_Tool_Panel_BGM
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "BakedGeneratedMeshActor_C.h"
class UDynamicMesh;
class UMaterialInterface;

#include "B_Tool_Panel_BGM.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_Tool_Panel_BGM : public UBakedGeneratedMeshActor_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    F/Script/CoreUObject.Vector Handle;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    double CornerRadius = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    int32 StepsRound = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    double TopperInset = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    double TopperExtrude = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    uint8 Operation = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    double OffSetTopper = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    TObjectPtr<UMaterialInterface> MaterialPanel;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    TObjectPtr<UMaterialInterface> MaterialTopper;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    uint8 Type = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Cutter")
    bool bCustomCutter = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Cutter")
    F/Script/CoreUObject.Rotator CustomCutterRotation;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Cutter")
    F/Script/CoreUObject.Vector CustomCutter;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UDynamicMesh> DynamicMEsh;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Bevel")
    bool bBevelPanel = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Bevel")
    double BevelDistancePanel = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UDynamicMesh> TargetMesh;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Bevel")
    bool bBevelTopper = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Bevel")
    double BevelDistanceTopper = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Bevel")
    bool bBevelCombine = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Bevel")
    double BevelDistanceCombine = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Mirror")
    bool bMirror = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Mirror")
    F/Script/CoreUObject.Rotator MirrorRotation;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Mirror")
    uint8 MirrorAxis = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings|Mirror")
    F/Script/CoreUObject.Vector MirrorLocation;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    bool bRec = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    double SafeNormalTolerance = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Settings")
    bool bRecTopper = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UDynamicMesh> Half;

    UFUNCTION(BlueprintCallable)
    UDynamicMesh* fnBevel(UDynamicMesh* TargetMesh, double OptionsBevelDistance);
    UFUNCTION(BlueprintCallable)
    void ApplyMaterials(const TArray<UMaterialInterface*>& Materials);
};
