// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /TopDownArena/Game/Pickups/B_TopDownArena_Pickup
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
class UNiagaraComponent;
class USceneComponent;
class USphereComponent;

#include "B_TopDownArena_Pickup.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class AB_TopDownArena_Pickup : public AActor {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Default")
    TSubclassOf</Script/GameplayAbilities.GameplayEffect> GameplayEffectToApply;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FText DebugDisplayText;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USceneComponent> DefaultSceneRoot;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USphereComponent> Volume;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UNiagaraComponent> VFX;

    AB_TopDownArena_Pickup();

    virtual void GetLifetimeReplicatedProps(TArray<class FLifetimeProperty>& OutLifetimeProps) const override;

    UFUNCTION(BlueprintCallable)
    void OnRep_GameplayEffectToApply();
};
