// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /TopDownArena/System/Experiences/B_TopDownArenaExperience
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraExperienceDefinition.h"
#include "B_TopDownArenaExperience.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_TopDownArenaExperience : public ULyraExperienceDefinition {
    GENERATED_BODY()
public:
};
