// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_Tool_Stairs_BGM.h"

void UB_Tool_Stairs_BGM::ApplyMaterials(const TArray<UMaterialInterface*>& Materials) {
    Material = /* TODO[bpr-expr]: K2Node_GetArrayItem (guid=21DAF8A3-478C-39B2-8EB5-1A8903D9F11B) */;
    return;
}

