// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterTests/Input/TriggerFeedback/B_TriggerFeedbackTest
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "InputDeviceTriggerFeedbackProperty.h"
#include "B_TriggerFeedbackTest.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_TriggerFeedbackTest : public UInputDeviceTriggerFeedbackProperty {
    GENERATED_BODY()
public:
};
