// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Weapons/Rifle/B_WeaponInstance_Rifle
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "B_WeaponInstance_Base_C.h"
#include "B_WeaponInstance_Rifle.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_WeaponInstance_Rifle : public UB_WeaponInstance_Base_C {
    GENERATED_BODY()
public:
};
