// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_WeaponFire.h"
#include "Components/SceneComponent.h"

AB_WeaponFire::AB_WeaponFire() {
    DefaultSceneRoot = CreateDefaultSubobject<USceneComponent>(TEXT("DefaultSceneRoot"));
    RootComponent = DefaultSceneRoot;
    // TODO[bpr-comp-prop]: DefaultSceneRoot->bVisualizeComponent = true;
}

