// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_WeaponDecals.h"
#include "Components/SceneComponent.h"

AB_WeaponDecals::AB_WeaponDecals() {
    DefaultSceneRoot = CreateDefaultSubobject<USceneComponent>(TEXT("DefaultSceneRoot"));
    RootComponent = DefaultSceneRoot;
    // TODO[bpr-comp-prop]: DefaultSceneRoot->bVisualizeComponent = true;
}

