// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Effects/Blueprints/B_WeaponImpacts
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
class UNiagaraComponent;
class UNiagaraSystem;
class USceneComponent;

#include "B_WeaponImpacts.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class AB_WeaponImpacts : public AActor {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<F/Script/CoreUObject.Vector> ImpactPositions;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<F/Script/CoreUObject.Vector> ImpactNormals;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<uint8> ImpactSurfaceTypes;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<UNiagaraComponent> ImpactSystem;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Materials")
    TObjectPtr<UNiagaraSystem> Concrete;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Parameters")
    double DistanceThreshold = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<TObjectPtr<UNiagaraComponent>> ImpactSystems;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Materials")
    TObjectPtr<UNiagaraSystem> Glass;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Materials")
    TObjectPtr<UNiagaraSystem> Default;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Materials")
    TObjectPtr<UNiagaraSystem> Character;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool HasValidSystems = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    F/Script/CoreUObject.Vector MuzzlePosition;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool UseDataChannels = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<F/Game/Effects/Blueprints/SurfaceImpacts.SurfaceImpacts> ImpactBuckets;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USceneComponent> DefaultSceneRoot;

    AB_WeaponImpacts();

    UFUNCTION(BlueprintCallable)
    void SpawnFromDataChannels(uint8 SurfaceType);
    UFUNCTION(BlueprintCallable)
    void AddImpactsToBuckets();
    UFUNCTION(BlueprintCallable)
    void SpawnParticlesFromImpacts();
    UFUNCTION(BlueprintCallable)
    void SpawnFromArrays(uint8 SurfaceType);
};
