// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Weapons/B_WeaponInstance_Base
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraRangedWeaponInstance.h"
class UAnimMontage;

#include "GameplayTagContainer.h"

#include "B_WeaponInstance_Base.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_WeaponInstance_Base : public ULyraRangedWeaponInstance {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Animation")
    TObjectPtr<UAnimMontage> WeaponEquipMontage;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Animation")
    TObjectPtr<UAnimMontage> WeaponUnequipMontage;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Animation")
    TObjectPtr<UAnimMontage> MeleeAttackMontage;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Animation")
    FGameplayTagContainer CosmeticAnimStyleTags;

    UFUNCTION(BlueprintCallable)
    void DetermineCosmeticTags();
};
