// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_WeaponSpawner.h"
#include "Components/PointLightComponent.h"
#include "NiagaraComponent.h"
#include "Components/AudioComponent.h"

UB_WeaponSpawner::UB_WeaponSpawner() {
    PointLight = CreateDefaultSubobject<UPointLightComponent>(TEXT("PointLight"));
    NS_GunPad = CreateDefaultSubobject<UNiagaraComponent>(TEXT("NS_GunPad"));
    NS_GunPad_Loading = CreateDefaultSubobject<UNiagaraComponent>(TEXT("NS_GunPad_Loading"));
    Audio = CreateDefaultSubobject<UAudioComponent>(TEXT("Audio"));
    RootComponent = Audio;
    // TODO[bpr-comp-prop]: PointLight->AttenuationRadius = 250.0f;
    // TODO[bpr-comp-prop]: PointLight->CastShadows = false;
    // TODO[bpr-comp-prop]: PointLight->RelativeLocation = FVector(0.0f, -0.0f, 54.65239f);
    {
        static ConstructorHelpers::FObjectFinder<UNiagaraSystem> AssetFinder(TEXT("/Script/Niagara.NiagaraSystem'/Game/Effects/Particles/Item/NS_GunPad.NS_GunPad'"));
        if (AssetFinder.Succeeded()) { /* TODO[bpr-comp-prop]: NS_GunPad->Asset = AssetFinder.Object; */ }
    }
    // TODO[bpr-component-default]: NS_GunPad->OverrideParameters = /* StructProperty: (UserParameterRedirects=(((Name="ExplosionDelay",TypeDefHandle=(RegisteredTypeIndex=95)), (Name="User.ExplosionDelay",TypeDefHandle=(RegisteredTypeIndex=95))),((Name="GunPad_Color",TypeDefHandle=(RegisteredTypeIndex=102)), (Name="User.GunPad_Color",TypeDefHandle=(RegisteredTypeIndex=102))),((Name="Luminosity",TypeDefHandle=(RegisteredTypeIndex=95)), (Name="User.Luminosity",TypeDefHandle=(RegisteredTypeIndex=95)))),SortedParameterOffsets=((Offset=20,Name="User.ExplosionDelay",TypeDefHandle=(RegisteredTypeIndex=95)),(Offset=0,Name="User.GunPad_Color",TypeDefHandle=(RegisteredTypeIndex=102)),(Offset=16,Name="User.Luminosity",TypeDefHandle=(RegisteredTypeIndex=95))),ParameterData=(0,0,128,63,205,204,76,61,10,215,35,60,0,0,128,63,0,0,128,63,0,0,0,0)) */;
    // TODO[bpr-component-default]: NS_GunPad->TemplateParameterOverrides = /* MapProperty: (((Name="User.Luminosity",TypeDefHandle=(RegisteredTypeIndex=95)), (Bytes=(0,0,128,63),CurrentMode=Bytes))) */;
    // TODO[bpr-comp-prop]: NS_GunPad->bVisibleInRayTracing = false;
    // TODO[bpr-comp-prop]: NS_GunPad->RelativeLocation = FVector(0.0f, 0.0f, -74.0f);
    {
        static ConstructorHelpers::FObjectFinder<UNiagaraSystem> AssetFinder(TEXT("/Script/Niagara.NiagaraSystem'/Game/Effects/Particles/Item/NS_GunPad_Loading.NS_GunPad_Loading'"));
        if (AssetFinder.Succeeded()) { /* TODO[bpr-comp-prop]: NS_GunPad_Loading->Asset = AssetFinder.Object; */ }
    }
    // TODO[bpr-component-default]: NS_GunPad_Loading->OverrideParameters = /* StructProperty: (UserParameterRedirects=(((Name="GunPad_Color",TypeDefHandle=(RegisteredTypeIndex=102)), (Name="User.GunPad_Color",TypeDefHandle=(RegisteredTypeIndex=102))),((Name="LifeTime",TypeDefHandle=(RegisteredTypeIndex=95)), (Name="User.LifeTime",TypeDefHandle=(RegisteredTypeIndex=95))),((Name="Luminosity",TypeDefHandle=(RegisteredTypeIndex=95)), (Name="User.Luminosity",TypeDefHandle=(RegisteredTypeIndex=95))),((Name="OverallOpacity",TypeDefHandle=(RegisteredTypeIndex=95)), (Name="User.OverallOpacity",TypeDefHandle=(RegisteredTypeIndex=95))),((Name="RibbonProgression",TypeDefHandle=(RegisteredTypeIndex=95)), (Name="User.RibbonProgression",TypeDefHandle=(RegisteredTypeIndex=95)))),SortedParameterOffsets=((Offset=0,Name="User.GunPad_Color",TypeDefHandle=(RegisteredTypeIndex=102)),(Offset=16,Name="User.LifeTime",TypeDefHandle=(RegisteredTypeIndex=95)),(Offset=28,Name="User.Luminosity",TypeDefHandle=(RegisteredTypeIndex=95)),(Offset=20,Name="User.OverallOpacity",TypeDefHandle=(RegisteredTypeIndex=95)),(Offset=24,Name="User.RibbonProgression",TypeDefHandle=(RegisteredTypeIndex=95))),ParameterData=(0,0,128,63,205,204,76,61,10,215,35,60,0,0,128,63,0,0,32,65,0,0,128,63,154,153,25,63,0,0,0,0)) */;
    // TODO[bpr-comp-prop]: NS_GunPad_Loading->bVisibleInRayTracing = false;
    // TODO[bpr-comp-prop]: NS_GunPad_Loading->RelativeLocation = FVector(0.0f, 0.0f, -74.0f);
    // TODO[bpr-comp-prop]: NS_GunPad_Loading->bAutoActivate = false;
    {
        static ConstructorHelpers::FObjectFinder<USoundBase> SoundFinder(TEXT("/Script/Engine.SoundWave'/Game/Audio/Sounds/SFX/Lyra_RingLoop_03.Lyra_RingLoop_03'"));
        if (SoundFinder.Succeeded()) { /* TODO[bpr-comp-prop]: Audio->Sound = SoundFinder.Object; */ }
    }
    // TODO[bpr-comp-prop]: Audio->PitchModulationMin = 0.9f;
    // TODO[bpr-comp-prop]: Audio->PitchModulationMax = 1.1f;
    // TODO[bpr-comp-prop]: Audio->VolumeMultiplier = 0.3f;
    {
        static ConstructorHelpers::FObjectFinder<USoundAttenuation> AttenuationSettingsFinder(TEXT("/Script/Engine.SoundAttenuation'/Game/Audio/AttenuationPresets/ATT_Amb_Pad.ATT_Amb_Pad'"));
        if (AttenuationSettingsFinder.Succeeded()) { /* TODO[bpr-comp-prop]: Audio->AttenuationSettings = AttenuationSettingsFinder.Object; */ }
    }
}

void UB_WeaponSpawner::GiveWeapon(const TSubclassOf<ULyraInventoryItemDefinition>& WeaponItemClass, APawn* ReceivingPawn, bool& ReturnValue, bool& ReturnValue, bool& ReturnValue, bool& ReturnValue, bool& ReturnValue, bool& ReturnValue) {
    LyraGamePhaseSubsystem::IsPhaseActive(TEXT("(TagName=\"ShooterGame.GamePhase.PostGame\")"));
    if (LyraGamePhaseSubsystem::IsPhaseActive(TEXT("(TagName=\"ShooterGame.GamePhase.PostGame\")"))) {
        return false;
    } else {
        QuickBar = GetComponentByClass(nullptr);
        InventoryManager = GetComponentByClass(nullptr);
        if (IsValid(/* TODO[bpr-expr]: K2Node_VariableSet (guid=C71DCCE8-4463-4541-A224-089922BA5C12) */)) {
        }
    }
    ReturnValue = nullptr;
    ReturnValue = nullptr;
    ReturnValue = nullptr;
    ReturnValue = nullptr;
    ReturnValue = nullptr;
    ReturnValue = nullptr;
    return;
}

