// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Blueprint/B_WeaponSpawner
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraWeaponSpawner.h"
class UAudioComponent;
class UMaterialInstanceDynamic;
class UNiagaraComponent;
class UPointLightComponent;

#include "B_WeaponSpawner.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UB_WeaponSpawner : public ULyraWeaponSpawner {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra|WeaponPickup")
    FLinearColor LightColor;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra|WeaponPickup")
    double LightIntensity = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra|WeaponPickup")
    double LightRadius = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra|WeaponPickup")
    float GlowIntensity = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UMaterialInstanceDynamic> MID_Pad;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra|WeaponPickup")
    bool GiveAmmoForDuplicatedWeapons = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Debug")
    bool IgnorePickUpWhenReload = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra|WeaponPickup")
    double LifeTimeReload = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra|WeaponPickup")
    FVector WeaponMeshOffset;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UPointLightComponent> PointLight;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UNiagaraComponent> NS_GunPad;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UNiagaraComponent> NS_GunPad_Loading;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UAudioComponent> Audio;

    UB_WeaponSpawner();

    UFUNCTION(BlueprintCallable)
    void GiveWeapon(const TSubclassOf<ULyraInventoryItemDefinition>& WeaponItemClass, APawn* ReceivingPawn, bool& ReturnValue, bool& ReturnValue, bool& ReturnValue, bool& ReturnValue, bool& ReturnValue, bool& ReturnValue);
};
