// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_WeaponFire.h"

AB_WeaponFire::AB_WeaponFire() {
    DefaultSceneRoot = CreateDefaultSubobject<USceneComponent>(TEXT("DefaultSceneRoot"));
    RootComponent = DefaultSceneRoot;
    DefaultSceneRoot->bVisualizeComponent = true;
}

