// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_WeaponDecals.h"

AB_WeaponDecals::AB_WeaponDecals() {
    DefaultSceneRoot = CreateDefaultSubobject<USceneComponent>(TEXT("DefaultSceneRoot"));
    RootComponent = DefaultSceneRoot;
    DefaultSceneRoot->bVisualizeComponent = true;
}

