// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Weapons/B_Weapon
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
class APawn;
class UAudioComponent;
class UB_WeaponDecals;
class UB_WeaponFire;
class UB_WeaponImpacts;
class UNiagaraSystem;
class USkeletalMeshComponent;
class UStaticMesh;

#include "B_Weapon.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class AB_Weapon : public AActor {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra")
    TObjectPtr<APawn> OwnerAsPawn;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra")
    TObjectPtr<UB_WeaponFire> WeaponFire;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra")
    TObjectPtr<UB_WeaponImpacts> WeaponImpacts;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra")
    TObjectPtr<UB_WeaponDecals> WeaponDecals;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra")
    TObjectPtr<UNiagaraSystem> ShellEjectSystem;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra")
    TObjectPtr<UNiagaraSystem> MuzzleFlashSystem;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra")
    TObjectPtr<UNiagaraSystem> TracerSystem;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra")
    TObjectPtr<UStaticMesh> ShellEjectMesh;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra")
    TArray<FVector> ImpactPositions;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra")
    TArray<FVector> ImpactNormals;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra")
    TArray<uint8> ImpactSurfaceTypes;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra")
    FVector MuzzlePosition;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra")
    bool NeedsFakeProjectileData = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra")
    int32 NumerOfFakeProjectiles = 0;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<UAudioComponent> AudioComponent;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Lyra")
    bool ApplyTeamColorsToWeapon = false;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USkeletalMeshComponent> SkeletalMesh;

    AB_Weapon();

    UFUNCTION(BlueprintCallable)
    void AddFakeProjectileData(int32 NumerOfFakeProjectiles, double ConeHalfAngleInDegrees);
    UFUNCTION(BlueprintCallable)
    void TriggerFireAudio(USoundBase* Sound, AActor* Actor);
    UFUNCTION(BlueprintCallable)
    void UpdateCustomStencil(int32 TeamId);
    UFUNCTION(BlueprintCallable)
    void UpdateTeamColors(ULyraTeamDisplayAsset* TeamDisplayAsset);
};
