// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Effects/Blueprints/B_WeaponFire
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
class UNiagaraComponent;
class UNiagaraSystem;
class USceneComponent;
class USkeletalMeshComponent;
class UStaticMesh;

#include "B_WeaponFire.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class AB_WeaponFire : public AActor {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool ShellEjectTrigger = false;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<USkeletalMeshComponent> SkeletalMeshComponent;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<UNiagaraComponent> NS_ShellEject;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<UNiagaraComponent> NS_MuzzleFlash;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<UNiagaraComponent> NS_Tracer;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Shell Eject")
    bool EnableShellEject = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Shell Eject")
    TObjectPtr<UNiagaraSystem> ShellEjectSystem;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Muzzle Flash")
    bool EnableMuzzleFlash = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Muzzle Flash")
    TObjectPtr<UNiagaraSystem> MuzzleFlashSystem;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Tracer")
    bool EnableTracer = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Tracer")
    TObjectPtr<UNiagaraSystem> TracerSystem;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Shell Eject")
    TObjectPtr<UStaticMesh> ShellEjectMesh;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool MuzzleFlashTrigger = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool TracerTrigger = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<F/Script/CoreUObject.Vector> ImpactPositions;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<F/Script/CoreUObject.Vector> ImpactNormals;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<uint8> ImpactSurfaceTypes;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USceneComponent> DefaultSceneRoot;

    AB_WeaponFire();

};
