// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Effects/Blueprints/B_WeaponDecals
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
class UNiagaraComponent;
class UNiagaraSystem;
class USceneComponent;

#include "B_WeaponDecals.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class AB_WeaponDecals : public AActor, public ILyraContextEffectsInterface {
    GENERATED_BODY()
public:
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<UNiagaraComponent> Decal;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool ImpactTrigger = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UNiagaraSystem> DecalSystem;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<FVector> ImpactPositions;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<FVector> ImpactNormals;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<uint8> ImpactSurfaceTypes;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<int32> SurfaceTypes;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USceneComponent> DefaultSceneRoot;

    AB_WeaponDecals();

};
