// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_WindowDoor.h"

void AB_WindowDoor::CleanDegenerateTris(UDynamicMesh* Mesh, double SafeNormalTolerance, bool DebugLogCount, bool DeleteDegenerates) {
    GeometryScriptLibrary_MeshQueryFunctions::GetAllTriangleIDs(Mesh);
    GeometryScriptLibrary_ListUtilityFunctions::ConvertIndexListToArray(GeometryScriptLibrary_MeshQueryFunctions::GetAllTriangleIDs(Mesh));
    for (auto& Element : GeometryScriptLibrary_ListUtilityFunctions::ConvertIndexListToArray(GeometryScriptLibrary_MeshQueryFunctions::GetAllTriangleIDs(Mesh))) {
        // TODO[bpr-unsupported]: K2Node_MacroInstance (guid=C77EADD4-48FC-C08C-1092-CE88639E1D87) — manual port required.
        // Manual: Unrecognized BP node class 'K2Node_MacroInstance'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
    }
    if (/* TODO[bpr-expr]: K2Node_CallArrayFunction (guid=AB96EC56-444B-658A-792B-C29E48F5D280) */) {
    } else {
        if (DebugLogCount) {
            KismetSystemLibrary::PrintString(this, 2f, /* TODO[bpr-expr]: K2Node_CommutativeAssociativeBinaryOperator (guid=7B9DB526-41B1-CB89-C60F-67B6200493C9) */, TEXT("None"), TEXT("(R=0.000000,G=0.660000,B=1.000000,A=1.000000)"), nullptr, true, true);
        }
        if (DeleteDegenerates) {
            GeometryScriptLibrary_ListUtilityFunctions::ConvertArrayToIndexList(DegenerateTriList, TEXT("Triangle"));
            GeometryScriptLibrary_MeshBasicEditFunctions::DeleteTrianglesFromMesh(Mesh, GeometryScriptLibrary_ListUtilityFunctions::ConvertArrayToIndexList(DegenerateTriList, TEXT("Triangle")), false);
            GeometryScriptLibrary_MeshRepairFunctions::CompactMesh(nullptr, GeometryScriptLibrary_MeshBasicEditFunctions::DeleteTrianglesFromMesh(Mesh, GeometryScriptLibrary_ListUtilityFunctions::ConvertArrayToIndexList(DegenerateTriList, TEXT("Triangle")), false));
        }
    }
}

