// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "B_WindSystem.h"

AB_WindSystem::AB_WindSystem() {
    DefaultSceneRoot = CreateDefaultSubobject<USceneComponent>(TEXT("DefaultSceneRoot"));
    sfx_Amb_Wind_lp_meta = CreateDefaultSubobject<UAudioComponent>(TEXT("sfx_Amb_Wind_lp_meta"));
    sfx_Amb_Wind_lp_meta->SetupAttachment(DefaultSceneRoot);
    RootComponent = DefaultSceneRoot;
    DefaultSceneRoot->bVisualizeComponent = true;
    {
        static ConstructorHelpers::FObjectFinder<USoundBase> SoundFinder(TEXT("/Script/MetasoundEngine.MetaSoundSource'/Game/Audio/MetaSounds/sfx_Amb_Wind_lp_meta.sfx_Amb_Wind_lp_meta'"));
        if (SoundFinder.Succeeded()) { sfx_Amb_Wind_lp_meta->Sound = SoundFinder.Object; }
    }
}

