// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Audio/Sounds/Emotes/BI_EmoteSoundInterface
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Interface.h"
#include "BI_EmoteSoundInterface.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UBI_EmoteSoundInterface : public UInterface {
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintCallable)
    UAudioComponent* GetEmoteAudioComponent();
    UFUNCTION(BlueprintCallable)
    void SetEmoteAudioComponent(UAudioComponent* AudioComponent);
};
