// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "BI_EmoteSoundInterface.h"

UAudioComponent* UBI_EmoteSoundInterface::GetEmoteAudioComponent() {
    return nullptr;
}

void UBI_EmoteSoundInterface::SetEmoteAudioComponent(UAudioComponent* AudioComponent) {
}

