// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterTests/Blueprint/Messages/BP_Event_Listener
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "ColorChangingTestListener.h"
#include "BP_Event_Listener.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UBP_Event_Listener : public UColorChangingTestListener {
    GENERATED_BODY()
public:
};
