// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "BP_Event_Broadcaster.h"

ABP_Event_Broadcaster::ABP_Event_Broadcaster() {
    DefaultSceneRoot = CreateDefaultSubobject<USceneComponent>(TEXT("DefaultSceneRoot"));
    Sphere = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Sphere"));
    TextRender = CreateDefaultSubobject<UTextRenderComponent>(TEXT("TextRender"));
    Sphere->SetupAttachment(DefaultSceneRoot);
    TextRender->SetupAttachment(DefaultSceneRoot);
    RootComponent = DefaultSceneRoot;
    DefaultSceneRoot->bVisualizeComponent = true;
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Engine/BasicShapes/Sphere.Sphere'"));
        if (StaticMeshFinder.Succeeded()) { Sphere->StaticMesh = StaticMeshFinder.Object; }
    }
    // TODO[bpr-component-default]: Sphere->OverrideMaterials = /* ArrayProperty: ("/Script/Engine.Material'/ShooterTests/Blueprint/Messages/M_ListenerColorMaterial.M_ListenerColorMaterial'") */;
    TextRender->Text = TEXT("NSLOCTEXT(\"[BF8509369D7BE9692AED8C4A219CD479]\", \"6A42914C46238AE4550750BB48CDCAC3\", \"Count: {x}\")");
    TextRender->HorizontalAlignment = EHTA_Center;
    TextRender->VerticalAlignment = EVRTA_TextCenter;
    TextRender->RelativeLocation = FVector(0.0f, 0.0f, 110.0f);
    TextRender->RelativeRotation = FRotator(0.0f, 90.0f, 0.0f);
}

