// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterTests/Blueprint/Messages/BP_Event_Broadcaster
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "AsyncColorChangeBroadcastActor.h"
class USceneComponent;
class UStaticMeshComponent;
class UTextRenderComponent;

#include "BP_Event_Broadcaster.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class ABP_Event_Broadcaster : public AAsyncColorChangeBroadcastActor {
    GENERATED_BODY()
public:
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USceneComponent> DefaultSceneRoot;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> Sphere;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UTextRenderComponent> TextRender;

    ABP_Event_Broadcaster();

};
