// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "BP_Event_Broadcaster.h"
#include "Components/SceneComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Components/TextRenderComponent.h"

ABP_Event_Broadcaster::ABP_Event_Broadcaster() {
    DefaultSceneRoot = CreateDefaultSubobject<USceneComponent>(TEXT("DefaultSceneRoot"));
    Sphere = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Sphere"));
    TextRender = CreateDefaultSubobject<UTextRenderComponent>(TEXT("TextRender"));
    Sphere->SetupAttachment(DefaultSceneRoot);
    TextRender->SetupAttachment(DefaultSceneRoot);
    RootComponent = DefaultSceneRoot;
    // TODO[bpr-comp-prop]: DefaultSceneRoot->bVisualizeComponent = true;
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Engine/BasicShapes/Sphere.Sphere'"));
        if (StaticMeshFinder.Succeeded()) { /* TODO[bpr-comp-prop]: Sphere->StaticMesh = StaticMeshFinder.Object; */ }
    }
    // TODO[bpr-component-default]: Sphere->OverrideMaterials = /* ArrayProperty: ("/Script/Engine.Material'/ShooterTests/Blueprint/Messages/M_ListenerColorMaterial.M_ListenerColorMaterial'") */;
    // TODO[bpr-comp-prop]: TextRender->Text = TEXT("NSLOCTEXT(\"[BF8509369D7BE9692AED8C4A219CD479]\", \"6A42914C46238AE4550750BB48CDCAC3\", \"Count: {x}\")");
    // TODO[bpr-comp-prop]: TextRender->HorizontalAlignment = EHTA_Center;
    // TODO[bpr-comp-prop]: TextRender->VerticalAlignment = EVRTA_TextCenter;
    // TODO[bpr-comp-prop]: TextRender->RelativeLocation = FVector(0.0f, 0.0f, 110.0f);
    // TODO[bpr-comp-prop]: TextRender->RelativeRotation = FRotator(0.0f, 90.0f, 0.0f);
}

