// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Environments/Gameplay/BP_GameplayEffectPad
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
class UMaterialInterface;
class USceneComponent;
class USphereComponent;
class UStaticMeshComponent;
class UTextRenderComponent;

#include "BP_GameplayEffectPad.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class ABP_GameplayEffectPad : public AActor {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TSubclassOf<UGameplayEffect> GameplayEffectToApply;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UMaterialInterface> MAT_HealPad;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UMaterialInterface> MAT_DamagePad;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UMaterialInterface> MAT_SpecialPad;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TSubclassOf<UGameplayEffect> GE_Damage;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TSubclassOf<UGameplayEffect> GE_Heal;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USceneComponent> DefaultSceneRoot;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USphereComponent> Volume;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UTextRenderComponent> Text;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> PadBase;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UStaticMeshComponent> Pad;

    ABP_GameplayEffectPad();

};
