// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "BP_GameplayEffectPad_Forcefeedback.h"

ABP_GameplayEffectPad_Forcefeedback::ABP_GameplayEffectPad_Forcefeedback() {
    DefaultSceneRoot = CreateDefaultSubobject<USceneComponent>(TEXT("DefaultSceneRoot"));
    Volume = CreateDefaultSubobject<USphereComponent>(TEXT("Volume"));
    Text = CreateDefaultSubobject<UTextRenderComponent>(TEXT("Text"));
    PadBase = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("PadBase"));
    Pad = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Pad"));
    Volume->SetupAttachment(DefaultSceneRoot);
    Text->SetupAttachment(DefaultSceneRoot);
    PadBase->SetupAttachment(DefaultSceneRoot);
    Pad->SetupAttachment(DefaultSceneRoot);
    RootComponent = DefaultSceneRoot;
    DefaultSceneRoot->bVisualizeComponent = true;
    Volume->SphereRadius = 150.0f;
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassFinder.Succeeded()) { Volume->AreaClass = AreaClassFinder.Object; }
    }
    Volume->bUseSystemDefaultObstacleAreaClass = false;
    {
        static ConstructorHelpers::FObjectFinder<UClass> AreaClassOverrideFinder(TEXT("/Script/CoreUObject.Class'/Script/NavigationSystem.NavArea_Obstacle'"));
        if (AreaClassOverrideFinder.Succeeded()) { Volume->AreaClassOverride = AreaClassOverrideFinder.Object; }
    }
    // TODO[bpr-component-default]: Volume->BodyInstance = /* StructProperty: (CollisionProfileName="Trigger",CollisionResponses=(ResponseArray=((Channel="WorldStatic",Response=ECR_Overlap),(Channel="WorldDynamic",Response=ECR_Overlap),(Channel="Pawn",Response=ECR_Overlap),(Channel="Visibility",Response=ECR_Ignore),(Channel="Camera",Response=ECR_Overlap),(Channel="PhysicsBody",Response=ECR_Overlap),(Channel="Vehicle",Response=ECR_Overlap),(Channel="Destructible",Response=ECR_Overlap)))) */;
    Text->Text = TEXT("NSLOCTEXT(\"[0E5174C44605D153A940A8BE4CA84557]\", \"D4739F964AFB0EBAD6FAE7A448CAED1C\", \"DAMAGE\")");
    Text->HorizontalAlignment = EHTA_Center;
    Text->VerticalAlignment = EVRTA_TextCenter;
    Text->WorldSize = 60.0f;
    Text->RelativeLocation = FVector(-0.0f, 0.0f, 110.5f);
    Text->RelativeRotation = FRotator(0.000001f, 180.0f, 0.0f);
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Engine/BasicShapes/Cylinder.Cylinder'"));
        if (StaticMeshFinder.Succeeded()) { PadBase->StaticMesh = StaticMeshFinder.Object; }
    }
    PadBase->StaticMeshImportVersion = 1;
    // TODO[bpr-component-default]: PadBase->OverrideMaterials = /* ArrayProperty: ("/Script/Engine.Material'/Engine/EngineDebugMaterials/VertexColorMaterial.VertexColorMaterial'") */;
    PadBase->RelativeLocation = FVector(0.0f, 0.0f, -20.0f);
    PadBase->RelativeScale3D = FVector(3.25f, 3.25f, 0.5f);
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> StaticMeshFinder(TEXT("/Script/Engine.StaticMesh'/Engine/BasicShapes/Cylinder.Cylinder'"));
        if (StaticMeshFinder.Succeeded()) { Pad->StaticMesh = StaticMeshFinder.Object; }
    }
    Pad->StaticMeshImportVersion = 1;
    // TODO[bpr-component-default]: Pad->OverrideMaterials = /* ArrayProperty: ("/Script/Engine.Material'/Engine/BasicShapes/BasicShapeMaterial.BasicShapeMaterial'") */;
    Pad->RelativeLocation = FVector(0.0f, 0.0f, -15.0f);
    Pad->RelativeScale3D = FVector(3.0f, 3.0f, 0.5f);
}

