// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "BP_ThirdPersonCharacter.h"

ABP_ThirdPersonCharacter::ABP_ThirdPersonCharacter() {
    CameraBoom = CreateDefaultSubobject<USpringArmComponent>(TEXT("CameraBoom"));
    FollowCamera = CreateDefaultSubobject<UCameraComponent>(TEXT("FollowCamera"));
    FollowCamera->SetupAttachment(CameraBoom);
    RootComponent = CameraBoom;
    CameraBoom->TargetArmLength = 400.0f;
    CameraBoom->bUsePawnControlRotation = true;
    CameraBoom->RelativeLocation = FVector(0.0f, 0.0f, 8.492264f);
    FollowCamera->OrthoWidth = 512.0f;
    FollowCamera->bAutoCalculateOrthoPlanes = false;
    FollowCamera->OrthoNearClipPlane = 0.0f;
}

void ABP_ThirdPersonCharacter::Move(double XAxis, double YAxis) {
    AddMovementInput(XAxis, KismetMathLibrary::GetRightVector(TEXT("0, 0, 0"), 0f, GetControlRotation(), GetControlRotation()), false);
    AddMovementInput(YAxis, KismetMathLibrary::GetForwardVector(TEXT("0, 0, 0"), 0f, 0f, GetControlRotation()), false);
}

void ABP_ThirdPersonCharacter::Aim(float XAxis, double YAxis) {
    AddControllerYawInput(XAxis);
    AddControllerPitchInput(YAxis);
}

void ABP_ThirdPersonCharacter::OnUnknownStarted(const FInputActionValue& Value) {
    Jump();
}

void ABP_ThirdPersonCharacter::OnUnknownCompleted(const FInputActionValue& Value) {
    StopJumping();
}

void ABP_ThirdPersonCharacter::OnUnknownTriggered(const FInputActionValue& Value) {
    Move(/* TODO[bpr-expr]: K2Node_EnhancedInputAction (guid=B418BC36-4024-0533-4D5C-B6A083A2862D) */, /* TODO[bpr-expr]: K2Node_EnhancedInputAction (guid=B418BC36-4024-0533-4D5C-B6A083A2862D) */);
}

void ABP_ThirdPersonCharacter::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent) {
    Super::SetupPlayerInputComponent(PlayerInputComponent);
    if (auto* EIC = Cast<UEnhancedInputComponent>(PlayerInputComponent)) {
        EIC->BindAction(IA_Unknown, ETriggerEvent::Started, this, &ThisClass::OnUnknownStarted);
        EIC->BindAction(IA_Unknown, ETriggerEvent::Completed, this, &ThisClass::OnUnknownCompleted);
        EIC->BindAction(IA_Unknown, ETriggerEvent::Triggered, this, &ThisClass::OnUnknownTriggered);
    }
}

