// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Imported/ThirdPerson/BP_ThirdPersonCharacter
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Character.h"
class UCameraComponent;
class UInputAction;
class USpringArmComponent;

#include "BP_ThirdPersonCharacter.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class ABP_ThirdPersonCharacter : public ACharacter {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Input")
    TObjectPtr<UInputAction> IA_Unknown;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USpringArmComponent> CameraBoom;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<UCameraComponent> FollowCamera;

    ABP_ThirdPersonCharacter();

    UFUNCTION(BlueprintCallable)
    void Move(double XAxis, double YAxis);
    UFUNCTION(BlueprintCallable)
    void Aim(float XAxis, double YAxis);
    UFUNCTION()
    void OnUnknownStarted(const FInputActionValue& Value);
    UFUNCTION()
    void OnUnknownCompleted(const FInputActionValue& Value);
    UFUNCTION()
    void OnUnknownTriggered(const FInputActionValue& Value);
    virtual void SetupPlayerInputComponent(UInputComponent* PlayerInputComponent) override;
};
