// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Imported/ThirdPerson/BP_ThirdPersonPlayerController
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/PlayerController.h"
#include "BP_ThirdPersonPlayerController.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class ABP_ThirdPersonPlayerController : public APlayerController {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Input|Touch Controls")
    TSubclassOf</Script/UMG.UserWidget> TouchControlsWidgetClass;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Input|Touch Controls")
    bool ForceTouchControls = false;

    UFUNCTION(BlueprintCallable)
    void ShouldUseTouchControls(bool& UseMobileControls, bool& UseMobileControls);
};
