// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/AI/BP_TestEnemy
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
class USceneComponent;

#include "BP_TestEnemy.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class ABP_TestEnemy : public AActor {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="Combat")
    float Health = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Combat")
    float MaxHealth = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated, Category="AI")
    TObjectPtr<AActor> AggroTarget;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Combat")
    bool bIsAlive = false;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components")
    TObjectPtr<USceneComponent> DefaultSceneRoot;

    ABP_TestEnemy();

    virtual void GetLifetimeReplicatedProps(TArray<class FLifetimeProperty>& OutLifetimeProps) const override;

    UFUNCTION(BlueprintCallable)
    bool TakeDamage(float Damage);
    UFUNCTION(BlueprintCallable)
    void OnDeath();
};
