// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/UserInterface/HUD/W_AbilityFailureFeedback
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraTaggedWidget.h"
#include "W_AbilityFailureFeedback.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_AbilityFailureFeedback : public ULyraTaggedWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FText FailureReasonText;

};
