// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/UserInterface/Notifications/Accolades/W_AccoladeToast
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_AccoladeToast.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_AccoladeToast : public UUserWidget {
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintCallable)
    void PlayIntroOutro();
};
