// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/UserInterface/Notifications/Accolades/W_AccoladeHostWidget
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraAccoladeHostWidget.h"
#include "W_AccoladeHostWidget.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_AccoladeHostWidget : public ULyraAccoladeHostWidget {
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintCallable)
    UUserWidget* CreateAccoladeWidget(const FPendingAccoladeEntry& Entry);
};
