// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_AccoladeToast.h"

void UW_AccoladeToast::PlayIntroOutro() {
    PlayAnimationForward(IntroOutro, 1f, false);
}

