// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Hud/W_ActionTouchButton_MobileOnly
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "W_ActionTouchButton_C.h"
#include "W_ActionTouchButton_MobileOnly.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_ActionTouchButton_MobileOnly : public UW_ActionTouchButton_C {
    GENERATED_BODY()
public:
};
