// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_AccoladeHostWidget.h"

UUserWidget* UW_AccoladeHostWidget::CreateAccoladeWidget(const FPendingAccoladeEntry& Entry) {
    SetVisibility(TEXT("HitTestInvisible"));
    if (IsValid(Entry.Sound)) {
    }
    TextBlock::SetText(Entry.Row.DisplayName);
    Image::SetBrushResourceObject(Entry.Icon);
    /ShooterCore/UserInterface/Notifications/Accolades/W_AccoladeToast.W_AccoladeToast::PlayIntroOutro();
    return MyToast;
    return nullptr;
}

