// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_ActionTouchButton.h"

void UW_ActionTouchButton::UpdateCoolDownPercent(double Percent) {
    Image::GetDynamicMaterial();
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("Animate_CoolDown"), Percent);
    Image::GetDynamicMaterial();
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("Animate_Cooldown"), Percent);
}

void UW_ActionTouchButton::SetButtonStyle() {
    OverlaySlot::SetPadding(HitTestPadding);
    SetVisibility((UseBacking ? TEXT("HitTestInvisible") : TEXT("Collapsed")));
    SetVisibility((UseShadow ? TEXT("HitTestInvisible") : TEXT("Collapsed")));
    SetVisibility((UseBlur ? TEXT("HitTestInvisible") : TEXT("Collapsed")));
    SetVisibility((UseGlow ? TEXT("HitTestInvisible") : TEXT("Collapsed")));
    SetVisibility((UseGlowBoost ? TEXT("HitTestInvisible") : TEXT("Collapsed")));
    Image::SetBrush(ButtonBrush);
    Image::SetBrush(ButtonGlowBrush);
    OverlaySlot::SetPadding(GlowOverdraw);
    OverlaySlot::SetPadding(GlowOverdraw);
    BackgroundBlur::SetCornerRadius(KismetMathLibrary::MakeVector4(BlurCornerRadius, BlurCornerRadius, BlurCornerRadius, BlurCornerRadius));
    OverlaySlot::SetPadding(BlurPadding);
}

void UW_ActionTouchButton::ResetMaterials() {
    StopAnimation(CooldownInactiveToActive);
    Image::GetDynamicMaterial();
    Image::GetDynamicMaterial();
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("Animate_ActiveToInactive"), 1f);
}

