// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Hud/W_ActionTouchButton
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraButtonBase.h"
class UInputAction;

#include "GameplayTagContainer.h"

#include "W_ActionTouchButton.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_ActionTouchButton : public ULyraButtonBase {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FTimerHandle CooldownTimer;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double Duration = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double StartTime = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool Charging = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Config")
    TObjectPtr<UInputAction> AssociatedAction;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Config")
    FGameplayTag DurationMessageTag;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Style")
    FMargin HitTestPadding;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Style")
    bool UseBacking = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Style")
    bool UseShadow = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Style")
    bool UseBlur = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Style")
    bool UseGlow = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Style")
    bool UseGlowBoost = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Style")
    bool IsToggleButton = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Style")
    bool HasCooldown = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Style")
    FSlateBrush ButtonBrush;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool IsDisabled = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Style")
    FSlateBrush ButtonGlowBrush;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Style")
    FMargin GlowOverdraw;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Style")
    FMargin BlurPadding;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Style")
    double BlurCornerRadius = 0.0;

    UFUNCTION(BlueprintCallable)
    void UpdateCoolDownPercent(double Percent);
    UFUNCTION(BlueprintCallable)
    void SetButtonStyle();
    UFUNCTION(BlueprintCallable)
    void ResetMaterials();
};
