// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_AmmoCounter_Shotgun.h"

void UW_AmmoCounter_Shotgun::SetWeaponSpecificImages(UImage* AmmoCounterImage, UImage* WeaponSpecificImage) {
    Image::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Brush.DrawAs, /*ImageSize=*/Brush.ImageSize, /*Margin=*/Brush.Margin, /*Mirroring=*/Brush.Mirroring, /*OutlineSettings=*/Brush.OutlineSettings, /*ResourceObject=*/WeaponSpecificImage, /*Tiling=*/Brush.Tiling, /*TintColor=*/Brush.TintColor});
}

