// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Weapons/Pistol/W_AmmoCounter_Pistol
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraReticleWidgetBase.h"
class ULyraQuickBarComponent;

#include "W_AmmoCounter_Pistol.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_AmmoCounter_Pistol : public ULyraReticleWidgetBase {
    GENERATED_BODY()
public:
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<ULyraQuickBarComponent> QuickBar;

    UFUNCTION(BlueprintCallable)
    void SetWeaponSpecificImages(UImage* AmmoCounterImage, UImage* WeaponSpecificImage);
};
