// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Foundation/Widgets/W_AspectImageWithBlur
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_AspectImageWithBlur.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_AspectImageWithBlur : public UUserWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FSlateBrush DisplayBrush;

};
