// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_BasePlayerRow.h"

TArray<UWidget*> UW_BasePlayerRow::GetPlayerStateAwareChildren() {
    return nullptr;
}

void UW_BasePlayerRow::SetRowColor(bool IsOddNumberedRow) {
}

