// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Foundation/Widgets/BottomBar/W_BottomActionBar
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "CommonUserWidget.h"
#include "W_BottomActionBar.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_BottomActionBar : public UCommonUserWidget {
    GENERATED_BODY()
public:
};
