// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Foundation/Widgets/BottomBar/W_BoundActionButton
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraBoundActionButton.h"
#include "W_BoundActionButton.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_BoundActionButton : public ULyraBoundActionButton {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool IsDisabled = false;

    UFUNCTION(BlueprintCallable)
    void UpdateSyleOnInputMethod(uint8 InputType);
    UFUNCTION(BlueprintCallable)
    void ResetMaterials();
};
