// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/ControlPoint/UI/W_ControlPointMarker
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "CommonUserWidget.h"
class UMaterialInstanceDynamic;

#include "W_ControlPointMarker.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_ControlPointMarker : public UCommonUserWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UMaterialInstanceDynamic> BurstRingMID;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UMaterialInstanceDynamic> FillMID;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UMaterialInstanceDynamic> SoftGlowMID;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UMaterialInstanceDynamic> PointLetterMID;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UMaterialInstanceDynamic> RingMID;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UMaterialInstanceDynamic> RingGlowMID;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FText PointLetterText;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 PointOwnerTeamId = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 NumberOfOverlayingTeams = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 PreviousPointOwnerTeamId = 0;

    UFUNCTION(BlueprintCallable)
    void SetDynamicMaterial();
    UFUNCTION(BlueprintCallable)
    void UpdateControlPointStatus(UB_ControlPointVolume* ControlPointVolume);
    UFUNCTION(BlueprintCallable)
    void PointOwnerChanged(UB_ControlPointVolume* ControlPointVolume);
    UFUNCTION(BlueprintCallable)
    void IsPointOwned();
    UFUNCTION(BlueprintCallable)
    void IsPointOccupied(UB_ControlPointVolume* ControlPointVolume);
};
