// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/ControlPoint/UI/W_ControlPointStatusWidget
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraTaggedWidget.h"
class APlayerState;
class UB_ControlPointScoring;

#include "W_ControlPointStatusWidget.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_ControlPointStatusWidget : public ULyraTaggedWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UB_ControlPointScoring> ControlPointMode;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<APlayerState> OwningPlayerState;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 MyTeamID = 0;

};
