// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Foundation/Dialogs/W_ControllerDisconnected
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraControllerDisconnectedScreen.h"
#include "W_ControllerDisconnected.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_ControllerDisconnected : public ULyraControllerDisconnectedScreen {
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintCallable)
    UWidget* BP_GetDesiredFocusTarget();
};
