// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Settings/Extensions/ColorBlind/W_ColorBlindExtension
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameSettingDetailExtension.h"
#include "W_ColorBlindExtension.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_ColorBlindExtension : public UGameSettingDetailExtension {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<TObjectPtr<UObject>> CardItems;

};
