// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Foundation/Dialogs/W_ConfirmationError
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "W_ConfirmationDialog_C.h"
#include "W_ConfirmationError.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_ConfirmationError : public UW_ConfirmationDialog_C {
    GENERATED_BODY()
public:
};
