// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_ControlPointMarker.h"

void UW_ControlPointMarker::SetDynamicMaterial() {
    Image::GetDynamicMaterial();
    FillMID = Image::GetDynamicMaterial();
    Image::GetDynamicMaterial();
    RingMID = Image::GetDynamicMaterial();
    Image::GetDynamicMaterial();
    RingGlowMID = Image::GetDynamicMaterial();
    TextBlock::GetDynamicFontMaterial();
    PointLetterMID = TextBlock::GetDynamicFontMaterial();
    Image::GetDynamicMaterial();
    SoftGlowMID = Image::GetDynamicMaterial();
    Image::GetDynamicMaterial();
    BurstRingMID = Image::GetDynamicMaterial();
}

void UW_ControlPointMarker::UpdateControlPointStatus(UB_ControlPointVolume* ControlPointVolume) {
    PointOwnerTeamId = OwnerTeamID;
    PointOwnerChanged(ControlPointVolume);
    IsPointOwned();
    IsPointOccupied(ControlPointVolume);
}

void UW_ControlPointMarker::PointOwnerChanged(UB_ControlPointVolume* ControlPointVolume) {
    if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=C9DB911F-4048-CAE0-F4A5-B8958FB42E97) */) {
    } else {
        PlayAnimationForward(OnPointOwnerChanged, 1f, false);
        PreviousPointOwnerTeamId = OwnerTeamID;
        MaterialInstanceDynamic::SetScalarParameterValue(TEXT("IsEmptyPoint"), (/* TODO[bpr-expr]: K2Node_CommutativeAssociativeBinaryOperator (guid=08A7686B-484C-841E-FE8A-3987C0E24A01) */ ? 0f : 1f));
        MaterialInstanceDynamic::SetScalarParameterValue(TEXT("IsRedOrBlue"), (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=7293916A-4C66-53A1-AE3F-CEBBFDB64542) */ ? 0f : 1f));
    }
    return;
}

void UW_ControlPointMarker::IsPointOwned() {
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("IsEmptyPoint"), (/* TODO[bpr-expr]: K2Node_CommutativeAssociativeBinaryOperator (guid=7B1E8DA0-4B9D-6AA0-2CC0-3D97C7256B39) */ ? 0f : 1f));
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("bIsDisabled"), (/* TODO[bpr-expr]: K2Node_CommutativeAssociativeBinaryOperator (guid=7B1E8DA0-4B9D-6AA0-2CC0-3D97C7256B39) */ ? 0f : 1f));
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("Hover_Animate"), (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=D4AA137B-48A0-D39B-2A93-6F8FD6EF11C8) */ ? 0f : 1f));
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("IsRedOrBlue"), (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=D4AA137B-48A0-D39B-2A93-6F8FD6EF11C8) */ ? 0f : 1f));
}

void UW_ControlPointMarker::IsPointOccupied(UB_ControlPointVolume* ControlPointVolume) {
    if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=361DE623-455A-55E9-8BCF-70A86FB6B079) */) {
        MaterialInstanceDynamic::SetScalarParameterValue(TEXT("IsEmptyPoint"), 1f);
    } else {
        MaterialInstanceDynamic::SetScalarParameterValue(TEXT("IsEmptyPoint"), 0f);
        for (auto& Element : OverlappingTeams) {
            if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=B4DA37F3-4235-1C8D-1215-F795A95A3C63) */) {
                MaterialInstanceDynamic::SetScalarParameterValue(TEXT("IsContested"), 0f);
                MaterialInstanceDynamic::SetScalarParameterValue(TEXT("IsRedOrBlue"), KismetMathLibrary::SelectFloat(0f, 1f, /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=CE323585-4BB3-6807-95F7-0D924AB1BB35) */));
                MaterialInstanceDynamic::SetScalarParameterValue(TEXT("IsFlashing"), (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=1F5AEE31-42C8-19E2-8123-E79183DA54F9) */ ? 0f : 1f));
            } else {
                MaterialInstanceDynamic::SetScalarParameterValue(TEXT("IsContested"), 1f);
                MaterialInstanceDynamic::SetScalarParameterValue(TEXT("IsFlashing"), 1f);
            }
        }
    }
}

