// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_ControllerDisconnected.h"

UWidget* UW_ControllerDisconnected::BP_GetDesiredFocusTarget() {
    return nullptr;
}

