// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/ControlPoint/UI/W_CPScoreWidget
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraTaggedWidget.h"
class UB_ControlPointScoring;

#include "W_CPScoreWidget.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_CPScoreWidget : public ULyraTaggedWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 MyTeamID = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UB_ControlPointScoring> ControlPointMode;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 EnemyTeamId = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 PreviousScoreLeft = 0;

    UFUNCTION(BlueprintCallable)
    void UpdateStyleSides();
    UFUNCTION(BlueprintCallable)
    void UpdateTeamStyles();
    UFUNCTION(BlueprintCallable)
    void EvaluateSound_RoundEnding(UB_ControlPointScoring* CPScoring);
};
