// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_CPScoreWidget.h"

void UW_CPScoreWidget::UpdateStyleSides() {
    Border::GetDynamicMaterial();
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("InverseGradient"), (MyTeamID == 0 ? 0f : (MyTeamID == 1 ? 1f : 0f)));
}

void UW_CPScoreWidget::UpdateTeamStyles() {
    TextBlock::SetColorAndOpacity(/Script/SlateCore.SlateColor{/*ColorUseRule=*/TEXT("UseColor_Specified"), /*SpecifiedColor=*/(MyTeamID == 0 ? nullptr : (MyTeamID == 1 ? TEXT("(R=1.000000,G=0.496933,B=0.318547,A=1.000000)") : TEXT("(R=0.283149,G=0.887923,B=0.822786,A=1.000000)")))});
    TextBlock::SetColorAndOpacity(/Script/SlateCore.SlateColor{/*ColorUseRule=*/TEXT("UseColor_Specified"), /*SpecifiedColor=*/(EnemyTeamID == 0 ? nullptr : (EnemyTeamID == 1 ? TEXT("(R=1.000000,G=0.496933,B=0.318547,A=1.000000)") : TEXT("(R=0.283149,G=0.887923,B=0.822786,A=1.000000)")))});
    Image::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Brush.DrawAs, /*ImageSize=*/Brush.ImageSize, /*Margin=*/Brush.Margin, /*Mirroring=*/Brush.Mirroring, /*OutlineSettings=*/Brush.OutlineSettings, /*ResourceObject=*/(MyTeamID == 0 ? nullptr : (MyTeamID == 1 ? nullptr : nullptr)), /*Tiling=*/Brush.Tiling, /*TintColor=*/Brush.TintColor});
    Image::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Brush.DrawAs, /*ImageSize=*/Brush.ImageSize, /*Margin=*/Brush.Margin, /*Mirroring=*/Brush.Mirroring, /*OutlineSettings=*/Brush.OutlineSettings, /*ResourceObject=*/(EnemyTeamID == 0 ? nullptr : (EnemyTeamID == 1 ? nullptr : nullptr)), /*Tiling=*/Brush.Tiling, /*TintColor=*/Brush.TintColor});
    Image::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Brush.DrawAs, /*ImageSize=*/Brush.ImageSize, /*Margin=*/Brush.Margin, /*Mirroring=*/Brush.Mirroring, /*OutlineSettings=*/Brush.OutlineSettings, /*ResourceObject=*/(MyTeamID == 0 ? nullptr : (MyTeamID == 1 ? nullptr : nullptr)), /*Tiling=*/Brush.Tiling, /*TintColor=*/Brush.TintColor});
    Image::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Brush.DrawAs, /*ImageSize=*/Brush.ImageSize, /*Margin=*/Brush.Margin, /*Mirroring=*/Brush.Mirroring, /*OutlineSettings=*/Brush.OutlineSettings, /*ResourceObject=*/(EnemyTeamID == 0 ? nullptr : (EnemyTeamID == 1 ? nullptr : nullptr)), /*Tiling=*/Brush.Tiling, /*TintColor=*/Brush.TintColor});
}

void UW_CPScoreWidget::EvaluateSound_RoundEnding(UB_ControlPointScoring* CPScoring) {
    /ShooterCore/ControlPoint/B_ControlPointScoring.B_ControlPointScoring::GetTeamScoreCP(MyTeamID);
    /ShooterCore/ControlPoint/B_ControlPointScoring.B_ControlPointScoring::GetTeamScoreCP(EnemyTeamId);
    if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=50ADBA8E-4BEF-0C96-E770-8AACA5E8009D) */) {
    } else {
        if (/* TODO[bpr-expr]: K2Node_CommutativeAssociativeBinaryOperator (guid=B21E92E9-47BA-53F1-2882-CB93243A74A2) */) {
            GameplayStatics::SpawnSound2D(this, nullptr, 1f, nullptr, 0f, 1f, nullptr, true, false);
            if (IsValid(GameplayStatics::SpawnSound2D(this, nullptr, 1f, nullptr, 0f, 1f, nullptr, true, false))) {
            }
        }
    }
}

