// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Credits/W_Credits
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraActivatableWidget.h"
#include "W_Credits.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_Credits : public ULyraActivatableWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double CurrentPosition = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double ScrollSpeed = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double EndPointOffset = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FTimerHandle ScrollTimerHandle;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FString StudioPeopleString;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FText StudioPeopleText;

    UFUNCTION(BlueprintCallable)
    UWidget* BP_GetDesiredFocusTarget();
    UFUNCTION(BlueprintCallable)
    void ScrollCredits();
    UFUNCTION(BlueprintCallable)
    void ToggleScrollTimer(bool EnableTimer);
    UFUNCTION(BlueprintCallable)
    void Reset();
    UFUNCTION(BlueprintCallable)
    void CaptureEndPoint();
};
