// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_Credits.h"

UWidget* UW_Credits::BP_GetDesiredFocusTarget() {
    return nullptr;
}

void UW_Credits::ScrollCredits() {
    CurrentPosition = ScrollBox::GetScrollOffset();
    ScrollBox::SetScrollOffset(/* TODO[bpr-expr]: K2Node_CommutativeAssociativeBinaryOperator (guid=4F10A4A5-45A6-F766-96AC-F0919A5109E3) */);
    if (KismetMathLibrary::GreaterEqual_DoubleDouble(ScrollBox::GetScrollOffset(), EndPointOffset)) {
        ToggleScrollTimer(false);
        Reset();
    }
}

void UW_Credits::ToggleScrollTimer(bool EnableTimer) {
    if (EnableTimer) {
        KismetSystemLibrary::K2_SetTimerDelegate(/* TODO[bpr-expr]: K2Node_CreateDelegate (guid=E753B25A-4B3D-8233-6067-CFA7D38CEC23) */, 0f, 0f, 0.01f, true, false);
        ScrollTimerHandle = KismetSystemLibrary::K2_SetTimerDelegate(/* TODO[bpr-expr]: K2Node_CreateDelegate (guid=E753B25A-4B3D-8233-6067-CFA7D38CEC23) */, 0f, 0f, 0.01f, true, false);
    }
}

void UW_Credits::Reset() {
    ScrollBox::SetScrollOffset(0f);
    [&]{ if (UFunction* F__ = this->FindFunction(TEXT("ResetVisibility"))) { this->ProcessEvent(F__, nullptr); } /* TODO[bpr-bpcall]: receiver for W_TapToggleActionBar::ResetVisibility -- swap `this` for the sub-widget reference. */ })(;
}

void UW_Credits::CaptureEndPoint() {
    EndPointOffset = KismetMathLibrary::BreakVector2D(GetDesiredSize());
}

