// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/Characters/Heroes/Abilities/W_CrouchTouchButton
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_CrouchTouchButton.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_CrouchTouchButton : public UUserWidget {
    GENERATED_BODY()
public:
};
