// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_DashCooldown.h"

void UW_DashCooldown::UpdateCooldownPercent(double Percent) {
    Image::GetDynamicMaterial();
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("AnimateArcFill"), Percent);
    Image::GetDynamicMaterial();
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("AnimateArcFill"), Percent);
}

void UW_DashCooldown::UpdateVisibility() {
    if (IsValid(CurrentHealthComponent)) {
    }
}

