// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Game/Dash/W_DashTouchButton
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_DashTouchButton.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_DashTouchButton : public UUserWidget {
    GENERATED_BODY()
public:
};
