// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Game/Dash/W_DashCooldown
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
class APawn;
class ULyraHealthComponent;

#include "W_DashCooldown.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_DashCooldown : public UUserWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FTimerHandle CooldownTimer;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double Duration = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double StartTime = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool Charging = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<APawn> CurrentPawn;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<ULyraHealthComponent> NewHealthComponent;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<ULyraHealthComponent> CurrentHealthComponent;

    UFUNCTION(BlueprintCallable)
    void UpdateCooldownPercent(double Percent);
    UFUNCTION(BlueprintCallable)
    void UpdateVisibility();
};
