// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/UserInterface/HUD/W_DebugWeaponSpreadWidget
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraReticleWidgetBase.h"
#include "W_DebugWeaponSpreadWidget.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_DebugWeaponSpreadWidget : public ULyraReticleWidgetBase {
    GENERATED_BODY()
public:
};
