// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/UserInterface/Notifications/EliminationFeed/W_EliminationFeed
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_EliminationFeed.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_EliminationFeed : public UUserWidget {
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintCallable)
    void UpdateDisplayVisibility();
};
