// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_EliminationFeedEntryWidget.h"

void UW_EliminationFeedEntryWidget::SetTeamColors() {
    TextBlock::GetDynamicFontMaterial();
    Image::GetDynamicMaterial();
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("Animate_ActiveToInactive"), (AttackerTeamId == 0 ? 0f : (AttackerTeamId == 1 ? 1f : 0f)));
    Image::GetDynamicMaterial();
    Image::GetDynamicMaterial();
    Image::GetDynamicMaterial();
    Image::GetDynamicMaterial();
    Image::GetDynamicMaterial();
    Image::GetDynamicMaterial();
    Image::GetDynamicMaterial();
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("Animate_ActiveToInactive"), (AttackerTeamId == 0 ? 0f : (AttackerTeamId == 1 ? 1f : 0f)));
    TextBlock::GetDynamicFontMaterial();
    Image::GetDynamicMaterial();
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("Animate_ActiveToInactive"), (AttackeeTeamId == 0 ? 0f : (AttackeeTeamId == 1 ? 1f : 0f)));
}

void UW_EliminationFeedEntryWidget::SetWeaponIconAndNameText(const FText& AttackerName, const FText& AttackeeName, const FGameplayTagContainer& InstigatorTags) {
    TextBlock::SetText(AttackerName);
    TextBlock::SetText(AttackeeName);
    WidgetSwitcher::SetActiveWidget((BlueprintGameplayTagLibrary::HasTag(TEXT("(TagName=\"GameplayEffect.DamageType.Pistol\")"), InstigatorTags, false) ? Pistol : (BlueprintGameplayTagLibrary::HasTag(TEXT("(TagName=\"GameplayEffect.DamageType.Rifle\")"), InstigatorTags, false) ? Rifle : (BlueprintGameplayTagLibrary::HasTag(TEXT("(TagName=\"GameplayEffect.DamageType.Shotgun\")"), InstigatorTags, false) ? Shotgun : (BlueprintGameplayTagLibrary::HasTag(TEXT("(TagName=\"GameplayEffect.DamageType.Grenade\")"), InstigatorTags, false) ? Grenade : (BlueprintGameplayTagLibrary::HasTag(TEXT("(TagName=\"GameplayEffect.DamageType.Melee\")"), InstigatorTags, false) ? Melee : (BlueprintGameplayTagLibrary::HasTag(TEXT("(TagName=\"Gameplay.Damage.SelfDestruct\")"), InstigatorTags, false) ? SelfElimination : SelfElimination)))))));
}

