// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_EliminationFeed.h"

void UW_EliminationFeed::UpdateDisplayVisibility() {
    SetVisibility((/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=31D400C0-4931-C657-DFB1-6081EB6FDEA0) */ ? TEXT("Visible") : TEXT("Collapsed")));
}

