// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Game/Emote/W_EmoteTouchButton
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_EmoteTouchButton.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_EmoteTouchButton : public UUserWidget {
    GENERATED_BODY()
public:
};
