// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Settings/Extensions/Enum/W_EnumOptionDetailsEntry
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_EnumOptionDetailsEntry.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_EnumOptionDetailsEntry : public UUserWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FSlateColor SelectedColor;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FSlateColor DefaultColor;

};
