// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Settings/Extensions/Enum/W_EnumOptionExtension
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameSettingDetailExtension.h"
#include "W_EnumOptionExtension.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_EnumOptionExtension : public UGameSettingDetailExtension {
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintCallable)
    void RebuildOptions(UObject* Setting);
};
