// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_EnumOptionExtension.h"

void UW_EnumOptionExtension::RebuildOptions(UObject* Setting) {
    DynamicEntryBox::Reset(false);
    if (auto* AsGameSettingValueDiscrete = Cast<GameSettingValueDiscrete>(Setting)) {
        for (auto& Element : GameSettingValueDiscrete::GetDiscreteOptions()) {
            DynamicEntryBox::BP_CreateEntryOfClass(nullptr);
            [&]{ if (UFunction* F__ = this->FindFunction(TEXT("SetupEntry"))) { struct { auto Selected; auto Text; } P__ { KismetMathLibrary::EqualEqual_IntInt(/* TODO[bpr-expr]: K2Node_MacroInstance (guid=FF0F5C5E-4B9F-27A5-90C9-A2AA3431A7C4) */, GameSettingValueDiscrete::GetDiscreteOptionIndex()), /* TODO[bpr-expr]: K2Node_MacroInstance (guid=FF0F5C5E-4B9F-27A5-90C9-A2AA3431A7C4) */ }; this->ProcessEvent(F__, &P__); } /* TODO[bpr-bpcall]: receiver + arg types/order for W_EnumOptionDetailsEntry::SetupEntry */ })(;
        }
    }
}

