// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_ExperienceTile.h"

void UW_ExperienceTile::SetUserFacingExperience(ULyraUserFacingExperienceDefinition* NewExperience) {
    MyUserFacingExperience = NewExperience;
    [&]{ if (UFunction* F__ = this->FindFunction(TEXT("UpdateTileText"))) { struct { auto ExperienceDescription; auto ExperienceTitle; auto MapTitle; } P__ { TileDescription, TileTitle, TileSubTitle }; this->ProcessEvent(F__, &P__); } /* TODO[bpr-bpcall]: receiver + arg types/order for W_LyraExperienceTileButton::UpdateTileText */ })(;
    [&]{ if (UFunction* F__ = this->FindFunction(TEXT("UpdateTileArt"))) { struct { auto TileArt; } P__ { TileIcon }; this->ProcessEvent(F__, &P__); } /* TODO[bpr-bpcall]: receiver + arg types/order for W_LyraExperienceTileButton::UpdateTileArt */ })(;
}

FEventReply UW_ExperienceTile::OnFocusReceived(const FGeometry& MyGeometry, const FocusEvent& InFocusEvent) {
    return WidgetBlueprintLibrary::SetUserFocus(ExperienceTileButton, WidgetBlueprintLibrary::Handled(), false);
}

