// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_ExperienceSelectionScreen.h"

UWidget* UW_ExperienceSelectionScreen::BP_GetDesiredFocusTarget() {
    return QuickplayButton;
}

