// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_ExperienceList.h"

FEventReply UW_ExperienceList::OnFocusReceived(const FGeometry& MyGeometry, const FocusEvent& InFocusEvent) {
    return WidgetBlueprintLibrary::SetUserFocus(ExperienceScroller, WidgetBlueprintLibrary::Handled(), false);
}

