// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/FrontEnd/W_FrontEndHUDLayout
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraHUDLayout.h"
#include "W_FrontEndHUDLayout.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_FrontEndHUDLayout : public ULyraHUDLayout {
    GENERATED_BODY()
public:
};
