// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Settings/W_GameSettingsDetailView
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameSettingDetailView.h"
#include "W_GameSettingsDetailView.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_GameSettingsDetailView : public UGameSettingDetailView {
    GENERATED_BODY()
public:
};
