// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Settings/Screens/Gamma/W_GammaEditor
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraActivatableWidget.h"
#include "W_GammaEditor.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_GammaEditor : public ULyraActivatableWidget {
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintCallable)
    UWidget* BP_GetDesiredFocusTarget();
};
