// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /TopDownArena/GameplayCues/W_GetReady
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraActivatableWidget.h"
#include "W_GetReady.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_GetReady : public ULyraActivatableWidget {
    GENERATED_BODY()
public:
};
