// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Weapons/Grenade/W_GrenadeCooldown
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_GrenadeCooldown.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_GrenadeCooldown : public UUserWidget {
    GENERATED_BODY()
public:
};
