// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_Healthbar.h"

void UW_Healthbar::SetDynamicMaterials() {
    Image::GetDynamicMaterial();
    BarBorderMID = Image::GetDynamicMaterial();
    Image::GetDynamicMaterial();
    BarFillMID = Image::GetDynamicMaterial();
    Image::GetDynamicMaterial();
    BarGlowMID = Image::GetDynamicMaterial();
}

void UW_Healthbar::InitializeBarVisuals() {
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("Health_Current"), 1f);
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("Health_Updated"), 1f);
    CommonNumericTextBlock::InterpolateToValue(1f, 4f, 0f, /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=D7B79A3D-445F-D59F-6014-00BED4955E02) */);
    ResetAnimatedState();
}

void UW_Healthbar::ResetAnimatedState() {
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("Animate_Damage"), 0f);
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("Animate_DamageFade"), 0f);
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("Animate_Glow_AlphaChange"), 0f);
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("Animate_Glow_ColorChange"), 0f);
}

