// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Hud/W_Healthbar
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
class UMaterialInstanceDynamic;
class UTimelineComponent;

#include "W_Healthbar.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_Healthbar : public UUserWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UMaterialInstanceDynamic> BarBorderMID;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UMaterialInstanceDynamic> BarFillMID;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UMaterialInstanceDynamic> BarGlowMID;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double NormalizedHealth = 0.0;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<UTimelineComponent> NewVar_0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double HealthOldValue = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double HealthNewValue = 0.0;

    UFUNCTION(BlueprintCallable)
    void SetDynamicMaterials();
    UFUNCTION(BlueprintCallable)
    void InitializeBarVisuals();
    UFUNCTION(BlueprintCallable)
    void ResetAnimatedState();
};
