// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_HorizontalTabList.h"

void UW_HorizontalTabList::UpdateTabStyles(UCommonButtonBase* ButtonWidget) {
    HorizontalBox::AddChildToHorizontalBox(ButtonWidget);
    HorizontalBoxSlot::SetPadding(TabButtonPadding);
    CommonButtonBase::SetMinDimensions(0, MinTabWidth);
    if (UseButtonStyle) {
        CommonButtonBase::SetStyle(ButtonStyle);
    }
    RefreshNextPreviousVisibility();
}

void UW_HorizontalTabList::DebugCreateTabsForDesigner() {
    PanelWidget::ClearChildren();
    // TODO[bpr-unsupported]: K2Node_MacroInstance (guid=675ECEFB-4DDF-64F6-C54E-87BB28687E9D) — manual port required.
    // Manual: Unrecognized BP node class 'K2Node_MacroInstance'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
}

