// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Menu/Experiences/W_HostSessionScreen
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraActivatableWidget.h"
class UCommonActivatableWidget;
class ULyraUserFacingExperienceDefinition;

#include "W_HostSessionScreen.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_HostSessionScreen : public ULyraActivatableWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    uint8 OnlineMode = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<ULyraUserFacingExperienceDefinition> SelectedExperience;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool BotsEnabled = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UCommonActivatableWidget> SpinnerWidget;

    UFUNCTION(BlueprintCallable)
    void UpdateOnlineModeText();
    UFUNCTION(BlueprintCallable)
    UCommonSession_HostSessionRequest* CreateHostingRequest();
    UFUNCTION(BlueprintCallable)
    void UpdateBotsEnabledText();
    UFUNCTION(BlueprintCallable)
    UWidget* BP_GetDesiredFocusTarget();
};
