// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_HostSessionScreen.h"

void UW_HostSessionScreen::UpdateOnlineModeText() {
    TextBlock::SetText(nullptr);
}

UCommonSession_HostSessionRequest* UW_HostSessionScreen::CreateHostingRequest() {
    if (IsValid(SelectedExperience)) {
    }
    return nullptr;
}

void UW_HostSessionScreen::UpdateBotsEnabledText() {
    if (BotsEnabled) {
        TextBlock::SetText(nullptr);
    } else {
        TextBlock::SetText(nullptr);
    }
}

UWidget* UW_HostSessionScreen::BP_GetDesiredFocusTarget() {
    return BotsToggleButton;
}

