// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterExplorer/UserInterface/W_InventoryTile
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_InventoryTile.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_InventoryTile : public UUserWidget, public IUserObjectListEntry {
    GENERATED_BODY()
public:
};
