// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterExplorer/UserInterface/W_InteractionPrompt
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_InteractionPrompt.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_InteractionPrompt : public UUserWidget, public IIndicatorWidgetInterface {
    GENERATED_BODY()
public:
};
