// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterExplorer/UserInterface/W_InventoryScreen
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "CommonActivatableWidget.h"
#include "W_InventoryScreen.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_InventoryScreen : public UCommonActivatableWidget {
    GENERATED_BODY()
public:
};
