// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterExplorer/UserInterface/W_InventoryGrid
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
class ULyraInventoryManagerComponent;

#include "W_InventoryGrid.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_InventoryGrid : public UUserWidget {
    GENERATED_BODY()
public:
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<ULyraInventoryManagerComponent> NewVar_0;

};
