// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterExplorer/UserInterface/W_ItemAcquiredList
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_ItemAcquiredList.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_ItemAcquiredList : public UUserWidget {
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintCallable)
    void UpdateDisplayVisibility();
};
