// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterExplorer/UserInterface/W_ItemAcquiredToastRow
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
class UItemAcquiredToastEntry;

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnToastExpired, UItemAcquiredToastEntry*, ItemPtr);

#include "W_ItemAcquiredToastRow.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_ItemAcquiredToastRow : public UUserWidget, public IUserObjectListEntry {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FOnToastExpired OnToastExpired;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UItemAcquiredToastEntry> ItemPtr;

    UFUNCTION(BlueprintCallable)
    void SetIcon(UTexture2D* Texture);
};
