// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_ItemAcquiredList.h"

void UW_ItemAcquiredList::UpdateDisplayVisibility() {
    SetVisibility((/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=D0BEFD83-456F-3C65-2495-03BF99393F01) */ ? TEXT("Visible") : TEXT("Collapsed")));
}

