// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Settings/Screens/W_KeyAlreadyBoundWarning
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "KeyAlreadyBoundWarning.h"
#include "W_KeyAlreadyBoundWarning.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_KeyAlreadyBoundWarning : public UKeyAlreadyBoundWarning {
    GENERATED_BODY()
public:
};
