// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterMaps/System/Playlists/W_LoadingScreen_ControlPoint
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_LoadingScreen_ControlPoint.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_LoadingScreen_ControlPoint : public UUserWidget {
    GENERATED_BODY()
public:
};
