// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Foundation/LoadingScreen/W_LoadingScreenReasonDebugText
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_LoadingScreenReasonDebugText.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_LoadingScreenReasonDebugText : public UUserWidget {
    GENERATED_BODY()
public:
};
