// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Menu/W_LyraFrontEnd
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraActivatableWidget.h"
#include "W_LyraFrontEnd.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_LyraFrontEnd : public ULyraActivatableWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool bWaitingForLoginInput = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool bWaitingForPlayerInitialize = false;

    UFUNCTION(BlueprintCallable)
    UWidget* BP_GetDesiredFocusTarget();
};
