// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Menu/W_LyraStartup
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraActivatableWidget.h"
#include "W_LyraStartup.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_LyraStartup : public ULyraActivatableWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool bWaitingForPlayerInitialize = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool bWaitingForLoginInput = false;

    UFUNCTION(BlueprintCallable)
    void HandleUserInitialize(UCommonUserInfo* UserInfo, bool bSuccess, const FText& Error, uint8 RequestedPrivilege, uint8 OnlineContext);
    UFUNCTION(BlueprintCallable)
    void SetListenForLoginInput(bool bShouldListen);
    UFUNCTION(BlueprintCallable)
    void SwitchToPressStart();
    UFUNCTION(BlueprintCallable)
    void SwitchToFullMenu();
    UFUNCTION(BlueprintCallable)
    UWidget* BP_GetDesiredFocusTarget();
};
