// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_LyraButton.h"

void UW_LyraButton::UpdateTextAndStyle(uint8 InputType) {
    UpdateStyle(/* TODO[bpr-expr]: K2Node_EnumEquality (guid=9E72D58C-4CCD-8EC8-62A8-148CAC6627C2) */);
    UpdateTextStyle();
}

void UW_LyraButton::SetControllerStyle(const TSubclassOf<UCommonButtonStyle>& ControllerInputStyle) {
    ControllerInputStyle = ControllerInputStyle;
    UpdateStyle(CommonUIExtensions::IsOwningPlayerUsingGamepad(nullptr));
}

void UW_LyraButton::UpdateStyle(bool UsingGamepad) {
    if (UsingGamepad) {
    }
}

void UW_LyraButton::SetMouseKeyboardStyle(const TSubclassOf<UCommonButtonStyle>& ControllerInputStyle) {
    DefaultStyle = ControllerInputStyle;
    UpdateStyle(CommonUIExtensions::IsOwningPlayerUsingGamepad(nullptr));
}

void UW_LyraButton::UpdateContentAlignment() {
    if (auto* AsBorderSlot = Cast<BorderSlot>(ContentWidget::GetContentSlot())) {
        BorderSlot::SetHorizontalAlignment(ContentAlignment);
    }
}

void UW_LyraButton::SetContentAlignment(uint8 ContentAlignment) {
    ContentAlignment = ContentAlignment;
    UpdateContentAlignment();
}

void UW_LyraButton::UpdateTextStyle() {
    CommonTextBlock::SetStyle(GetCurrentTextStyleClass());
}

double UW_LyraButton::GetPressProgress() {
    return PressProgress;
}

