// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Settings/W_LyraSettingScreen
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraSettingScreen.h"
#include "W_LyraSettingScreen.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_LyraSettingScreen : public ULyraSettingScreen {
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintCallable)
    void RegisterTopLevelTab(FName SettingDevName);
};
