// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_LyraStartup.h"

void UW_LyraStartup::HandleUserInitialize(UCommonUserInfo* UserInfo, bool bSuccess, const FText& Error, uint8 RequestedPrivilege, uint8 OnlineContext) {
    if (bSuccess) {
        if (bWaitingForPlayerInitialize) {
            bWaitingForPlayerInitialize = false;
            SwitchToFullMenu();
        }
    }
}

void UW_LyraStartup::SetListenForLoginInput(bool bShouldListen) {
    bWaitingForLoginInput = bShouldListen;
    if (/* TODO[bpr-expr]: K2Node_VariableSet (guid=B1AF4498-44C1-C7EA-7AD0-EA9451742CC4) */) {
        CommonUserSubsystem::ListenForLoginKeyInput(PrimaryLoginKeys, EmptyKeys, nullptr);
    } else {
        CommonUserSubsystem::ListenForLoginKeyInput(EmptyKeys, EmptyKeys, nullptr);
    }
}

void UW_LyraStartup::SwitchToPressStart() {
    SetListenForLoginInput(true);
    bWaitingForPlayerInitialize = true;
}

void UW_LyraStartup::SwitchToFullMenu() {
    DeactivateWidget();
    SetListenForLoginInput(false);
}

UWidget* UW_LyraStartup::BP_GetDesiredFocusTarget() {
    return PressStartButton;
}

