// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Foundation/Buttons/W_LyraButtonTab
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraTabButtonBase.h"
#include "W_LyraButtonTab.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_LyraButtonTab : public ULyraTabButtonBase {
    GENERATED_BODY()
public:
};
