// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Menu/W_LyraTileButton
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraButtonBase.h"
class UTexture;

#include "W_LyraTileButton.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_LyraTileButton : public ULyraButtonBase {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    double PressProgress = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    Text Text;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    bool IsDisabled = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    Text Description;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    TObjectPtr<UTexture> KeyArtTexture;

    UFUNCTION(BlueprintCallable)
    void UpdateTextStyle();
    UFUNCTION(BlueprintCallable)
    double GetPressProgress();
    UFUNCTION(BlueprintCallable)
    void ResetMaterials();
    UFUNCTION(BlueprintCallable)
    void UpdateTileArt();
};
