// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_LyraMenuButton.h"

void UW_LyraMenuButton::UpdateTextStyle() {
    TextBlock::SetFont(Font);
    TextBlock::SetTextTransformPolicy(TextCase);
}

double UW_LyraMenuButton::GetPressProgress() {
    return PressProgress;
}

void UW_LyraMenuButton::ResetMaterials() {
    StopAnimation(OnPressed);
    Border::GetDynamicMaterial();
    TextBlock::GetDynamicFontMaterial();
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("Hover_Animate"), 0f);
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("Pressed_Animate"), 0f);
}

void UW_LyraMenuButton::UpdateButtonStyles() {
    SetVisibility((UseImageOverlays ? TEXT("HitTestInvisible") : TEXT("Collapsed")));
    Border::SetBrush(ButtonBorderBrush);
    SetVisibility((UseScaleChangeSpacers ? TEXT("HitTestInvisible") : TEXT("Collapsed")));
    HorizontalBoxSlot::SetPadding(/Script/SlateCore.Margin{/*Bottom=*/HitTestPadding_Y, /*Left=*/HitTestPadding_X, /*Right=*/HitTestPadding_X, /*Top=*/HitTestPadding_Y});
    OverlaySlot::SetPadding(InputPadding);
    OverlaySlot::SetHorizontalAlignment(InputHorzAlignment);
    OverlaySlot::SetVerticalAlignment(InputVertAlignment);
    if (UseIconOverride) {
        WidgetSwitcher::SetActiveWidget(IconOvr);
        Image::SetBrush(IconBrush);
        SetRenderTransform(/Script/UMG.WidgetTransform{/*Angle=*/0f, /*Scale=*/KismetMathLibrary::MakeVector2D((FlipIconXDimension ? -1f : 1f), 1f), /*Shear=*/TEXT("(X=0.000000,Y=0.000000)"), /*Translation=*/TEXT("(X=0.000000,Y=0.000000)")});
    }
}

