// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Menu/Experiences/W_LyraSessionButton
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraButtonBase.h"
#include "W_LyraSessionButton.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_LyraSessionButton : public ULyraButtonBase {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    bool IsDisabled = false;

    UFUNCTION(BlueprintCallable)
    void SetTexts(const FText& GameMode, const FText& MapName, const FText& Ping, const FText& Players, const FText& MaxPlayers);
    UFUNCTION(BlueprintCallable)
    void ResetMaterials();
    UFUNCTION(BlueprintCallable)
    void ResetFontMaterials(UTextBlock* Text);
    UFUNCTION(BlueprintCallable)
    void SetMapImage(UTexture* MapImage);
};
