// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Hud/W_LyraGameMenu
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraActivatableWidget.h"
#include "W_LyraGameMenu.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_LyraGameMenu : public ULyraActivatableWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    softobject FrontEndMapReference;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FPrimaryAssetId FrontEndExperienceReference;

    UFUNCTION(BlueprintCallable)
    UWidget* BP_GetDesiredFocusTarget();
};
