// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Foundation/Buttons/W_LyraButton
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraButtonBase.h"
class UCommonButtonStyle;

#include "W_LyraButton.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_LyraButton : public ULyraButtonBase {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Style")
    TSubclassOf<UCommonButtonStyle> DefaultStyle;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Style")
    TSubclassOf<UCommonButtonStyle> ControllerInputStyle;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Style")
    uint8 ContentAlignment = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    uint8 TextJustification = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    uint8 TextTransformPolicy = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double PressProgress = 0.0;

    UFUNCTION(BlueprintCallable)
    void UpdateTextAndStyle(uint8 InputType);
    UFUNCTION(BlueprintCallable)
    void SetControllerStyle(const TSubclassOf<UCommonButtonStyle>& ControllerInputStyle);
    UFUNCTION(BlueprintCallable)
    void UpdateStyle(bool UsingGamepad);
    UFUNCTION(BlueprintCallable)
    void SetMouseKeyboardStyle(const TSubclassOf<UCommonButtonStyle>& ControllerInputStyle);
    UFUNCTION(BlueprintCallable)
    void UpdateContentAlignment();
    UFUNCTION(BlueprintCallable)
    void SetContentAlignment(uint8 ContentAlignment);
    UFUNCTION(BlueprintCallable)
    void UpdateTextStyle();
    UFUNCTION(BlueprintCallable)
    double GetPressProgress();
};
