// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Menu/W_LyraMenuButton
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraButtonBase.h"
#include "W_LyraMenuButton.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_LyraMenuButton : public ULyraButtonBase {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    double TextLeftRightPadding = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    double HitTestPadding_X = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    double HitTestPadding_Y = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    double PressProgress = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    FSlateFontInfo Font;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    FSlateBrush ButtonBorderBrush;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    FSlateBrush IconBrush;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    uint8 TextCase = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    bool FlipIconXDimension = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    bool IsDisabled = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    bool UseImageOverlays = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    bool UseScaleChangeSpacers = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    bool UseIconOverride = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    uint8 InputHorzAlignment = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    uint8 InputVertAlignment = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Button")
    FMargin InputPadding;

    UFUNCTION(BlueprintCallable)
    void UpdateTextStyle();
    UFUNCTION(BlueprintCallable)
    double GetPressProgress();
    UFUNCTION(BlueprintCallable)
    void ResetMaterials();
    UFUNCTION(BlueprintCallable)
    void UpdateButtonStyles();
};
