// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_MatchDecided_Message.h"

void UW_MatchDecided_Message::SetTeamMaterials() {
    TextBlock::SetFont(SlateFontBlueprintLibrary::MakeSlateFontInfo((Team == 0 ? nullptr : (Team == 1 ? nullptr : nullptr)), Font.FontObject, Font.LetterSpacing, 1f, Font.OutlineSettings, Font.Size, 0f, Font.TypefaceFontName, TEXT("False"), TEXT("False")));
    Image::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Brush.DrawAs, /*ImageSize=*/Brush.ImageSize, /*Margin=*/Brush.Margin, /*Mirroring=*/Brush.Mirroring, /*OutlineSettings=*/Brush.OutlineSettings, /*ResourceObject=*/(Team == 0 ? nullptr : (Team == 1 ? nullptr : nullptr)), /*Tiling=*/Brush.Tiling, /*TintColor=*/Brush.TintColor});
    Image::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Brush.DrawAs, /*ImageSize=*/Brush.ImageSize, /*Margin=*/Brush.Margin, /*Mirroring=*/Brush.Mirroring, /*OutlineSettings=*/Brush.OutlineSettings, /*ResourceObject=*/(Team == 0 ? nullptr : (Team == 1 ? nullptr : nullptr)), /*Tiling=*/Brush.Tiling, /*TintColor=*/Brush.TintColor});
    Image::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Brush.DrawAs, /*ImageSize=*/Brush.ImageSize, /*Margin=*/Brush.Margin, /*Mirroring=*/Brush.Mirroring, /*OutlineSettings=*/Brush.OutlineSettings, /*ResourceObject=*/(Team == 0 ? nullptr : (Team == 1 ? nullptr : nullptr)), /*Tiling=*/Brush.Tiling, /*TintColor=*/Brush.TintColor});
    Image::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Brush.DrawAs, /*ImageSize=*/Brush.ImageSize, /*Margin=*/Brush.Margin, /*Mirroring=*/Brush.Mirroring, /*OutlineSettings=*/Brush.OutlineSettings, /*ResourceObject=*/(Team == 0 ? nullptr : (Team == 1 ? nullptr : nullptr)), /*Tiling=*/Brush.Tiling, /*TintColor=*/Brush.TintColor});
    Image::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Brush.DrawAs, /*ImageSize=*/Brush.ImageSize, /*Margin=*/Brush.Margin, /*Mirroring=*/Brush.Mirroring, /*OutlineSettings=*/Brush.OutlineSettings, /*ResourceObject=*/(Team == 0 ? nullptr : (Team == 1 ? nullptr : nullptr)), /*Tiling=*/Brush.Tiling, /*TintColor=*/Brush.TintColor});
}

