// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/ControlPoint/UI/W_MatchScoreBoard_CP
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraActivatableWidget.h"
#include "W_MatchScoreBoard_CP.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_MatchScoreBoard_CP : public ULyraActivatableWidget {
    GENERATED_BODY()
public:
};
