// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/GameplayCues/W_MatchDecided_Message
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_MatchDecided_Message.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_MatchDecided_Message : public UUserWidget, public II_GameplayCueWidget_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 Team = 0;

    UFUNCTION(BlueprintCallable)
    void SetTeamMaterials();
};
