// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Elimination/UI/W_MatchScoreBoard_Elimination
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraActivatableWidget.h"
#include "W_MatchScoreBoard_Elimination.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_MatchScoreBoard_Elimination : public ULyraActivatableWidget {
    GENERATED_BODY()
public:
};
