// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Game/Melee/W_MeleeTouchButton
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_MeleeTouchButton.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_MeleeTouchButton : public UUserWidget {
    GENERATED_BODY()
public:
};
