// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_Nameplate.h"

void UW_Nameplate::SetTeamVisuals() {
    Image::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Brush.DrawAs, /*ImageSize=*/Brush.ImageSize, /*Margin=*/Brush.Margin, /*Mirroring=*/Brush.Mirroring, /*OutlineSettings=*/Brush.OutlineSettings, /*ResourceObject=*/(TeamId == 0 ? nullptr : (TeamId == 1 ? nullptr : nullptr)), /*Tiling=*/Brush.Tiling, /*TintColor=*/Brush.TintColor});
    TextBlock::GetDynamicFontMaterial();
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("Animate_ActiveToInactive"), (TeamId == 0 ? 0f : (TeamId == 1 ? 1f : 0f)));
    Image::GetDynamicMaterial();
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("Animate_ActiveToInactive"), (TeamId == 0 ? 0f : (TeamId == 1 ? 1f : 0f)));
    if (IsValid(LyraHealthComponent::FindHealthComponent(Pawn))) {
    }
}

void UW_Nameplate::UpdateVisibility() {
    if (/* TODO[bpr-expr]: K2Node_CommutativeAssociativeBinaryOperator (guid=B9E804B9-45F4-CCA7-F109-7CBF6C11E367) */) {
        SetVisibility(TEXT("Collapsed"));
    } else {
        if (ShowTeamNamesOnly) {
            LyraTeamSubsystem::CompareTeams(Pawn, GetOwningPlayer());
        }
    }
}

