// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Menu/Experiences/W_NonInteractiveSpinner
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraActivatableWidget.h"
#include "W_NonInteractiveSpinner.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_NonInteractiveSpinner : public ULyraActivatableWidget {
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintCallable)
    UWidget* BP_GetDesiredFocusTarget();
};
