// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_NonInteractiveSpinner.h"

UWidget* UW_NonInteractiveSpinner::BP_GetDesiredFocusTarget() {
    return this;
}

