// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Hud/W_OnScreenJoystick_Left
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "W_OnScreenJoystick_Right_C.h"
#include "W_OnScreenJoystick_Left.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_OnScreenJoystick_Left : public UW_OnScreenJoystick_Right_C {
    GENERATED_BODY()
public:
};
