// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Hud/W_OnScreenJoystick_Right
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraJoystickWidget.h"
#include "W_OnScreenJoystick_Right.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_OnScreenJoystick_Right : public ULyraJoystickWidget {
    GENERATED_BODY()
public:
};
