// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Hud/W_OpenMenuTouchButton
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
class UInputAction;

#include "GameplayTagContainer.h"

#include "W_OpenMenuTouchButton.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_OpenMenuTouchButton : public UUserWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FTimerHandle CooldownTimer;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double Duration = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double StartTime = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool Charging = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Config")
    TObjectPtr<UInputAction> AssociatedAction;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Config")
    FGameplayTag DurationMessageTag;

};
