// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/W_OverallUILayout
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "PrimaryGameLayout.h"
#include "W_OverallUILayout.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_OverallUILayout : public UPrimaryGameLayout {
    GENERATED_BODY()
public:
};
