// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/PerfStats/W_PerfStatContainer_TextOnly
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraPerfStatContainerBase.h"
#include "W_PerfStatContainer_TextOnly.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_PerfStatContainer_TextOnly : public ULyraPerfStatContainerBase {
    GENERATED_BODY()
public:
};
