// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/PerfStats/W_PerfStatGraph
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraPerfStatGraph.h"
#include "W_PerfStatGraph.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_PerfStatGraph : public ULyraPerfStatGraph {
    GENERATED_BODY()
public:
};
