// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_PlayerTile.h"

void UW_PlayerTile::Configure(ULyraPlayerState* PlayerState) {
    TextBlock::SetText(KismetTextLibrary::Conv_StringToText(PlayerState::GetPlayerName()));
    MonitorTeamChange(PlayerState);
    /TopDownArena/UserInterface/Player/W_Powerup_Stat.W_Powerup_Stat::Configure(PlayerState, TEXT("(AttributeName=\"BombsRemaining\",Attribute=/Script/TopDownArenaRuntime.TopDownArenaAttributeSet:BombsRemaining,AttributeOwner=\"/Script/CoreUObject.Class'/Script/TopDownArenaRuntime.TopDownArenaAttributeSet'\")"), TEXT("/TopDownArena/UserInterface/Player/Texture/T_Bombs.T_Bombs"));
    /TopDownArena/UserInterface/Player/W_Powerup_Stat.W_Powerup_Stat::Configure(PlayerState, TEXT("(AttributeName=\"BombRange\",Attribute=/Script/TopDownArenaRuntime.TopDownArenaAttributeSet:BombRange,AttributeOwner=\"/Script/CoreUObject.Class'/Script/TopDownArenaRuntime.TopDownArenaAttributeSet'\")"), TEXT("/TopDownArena/UserInterface/Player/Texture/T_Range.T_Range"));
    /TopDownArena/UserInterface/Player/W_Powerup_Stat.W_Powerup_Stat::Configure(PlayerState, TEXT("(AttributeName=\"MovementSpeed\",Attribute=/Script/TopDownArenaRuntime.TopDownArenaAttributeSet:MovementSpeed,AttributeOwner=\"/Script/CoreUObject.Class'/Script/TopDownArenaRuntime.TopDownArenaAttributeSet'\")"), TEXT("/TopDownArena/UserInterface/Player/Texture/T_Speed.T_Speed"));
}

