// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /TopDownArena/UserInterface/Player/W_Powerup_Stat
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
class AActor;
class UAbilityAsync_WaitAttributeChanged;

#include "W_Powerup_Stat.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_Powerup_Stat : public UUserWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FGameplayAttribute Attribute;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UAbilityAsync_WaitAttributeChanged> AsyncAttributeChanged;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<AActor> AbilityTarget;

    UFUNCTION(BlueprintCallable)
    void Configure(AActor* AbilityTarget, const FGameplayAttribute& Attribute, const softobject& DisplayAsset);
    UFUNCTION(BlueprintCallable)
    void UpdateText(double Value);
};
