// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/UserInterface/HUD/W_QuickBarSlot
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraTaggedWidget.h"
class UInputAction;
class ULyraQuickBarComponent;

#include "W_QuickBarSlot.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_QuickBarSlot : public ULyraTaggedWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 SlotIndex = 0;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<ULyraQuickBarComponent> QuickBarComponent;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool IsEmpty = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool IsSelected = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UInputAction> SlotInputAction;

    UFUNCTION(BlueprintCallable)
    void UpdateSlot(ULyraInventoryItemInstance* Item);
    UFUNCTION(BlueprintCallable)
    void UpdateComponentRef(ULyraQuickBarComponent* QuickBarComponent);
    UFUNCTION(BlueprintCallable)
    void UpdateIsSelected();
    UFUNCTION(BlueprintCallable)
    void UpdateTotalAmmoLeft(ULyraQuickBarComponent* QuickBarComponent);
    UFUNCTION(BlueprintCallable)
    void IsThisTheActiveQuickbarSlot(bool& IsActive, bool& IsActive);
    UFUNCTION(BlueprintCallable)
    FEventReply On_SelectionBorder_MouseButtonDown_0(const FGeometry& MyGeometry, const FPointerEvent& MouseEvent);
};
