// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_QuickBarSlot.h"

void UW_QuickBarSlot::UpdateSlot(ULyraInventoryItemInstance* Item) {
    if (IsValid(Item)) {
    }
}

void UW_QuickBarSlot::UpdateComponentRef(ULyraQuickBarComponent* QuickBarComponent) {
    if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=5D067FAE-4423-F63F-1B37-ADA526D8C510) */) {
        QuickBarComponent = QuickBarComponent;
        if (IsValid(/* TODO[bpr-expr]: K2Node_VariableSet (guid=8F02A261-4398-6E52-4BB7-AC9CCBFB2E66) */)) {
        }
    }
}

void UW_QuickBarSlot::UpdateIsSelected() {
    if (IsEmpty) {
    } else {
        if (IsThisTheActiveQuickbarSlot()) {
            IsSelected = true;
            PlayAnimationForward(InactiveToActive, 1f, false);
        } else {
            if (IsSelected) {
                if (IsAnimationPlaying(InactiveToActive)) {
                    StopAnimation(InactiveToActive);
                    IsSelected = false;
                    PlayAnimationForward(ActiveToInactive, 1f, false);
                }
            }
        }
    }
}

void UW_QuickBarSlot::UpdateTotalAmmoLeft(ULyraQuickBarComponent* QuickBarComponent) {
    LyraQuickBarComponent::GetSlots();
    if (/* TODO[bpr-expr]: K2Node_CallArrayFunction (guid=1362A1CE-4401-F5D2-16C4-B598010AFBC1) */) {
        if (IsEmpty) {
        } else {
            CommonNumericTextBlock::SetCurrentValue(KismetMathLibrary::Conv_IntToDouble(/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=339C902F-45C2-6A99-B67D-A4AAAF56ACF0) */));
        }
    }
}

void UW_QuickBarSlot::IsThisTheActiveQuickbarSlot(bool& IsActive, bool& IsActive) {
    if (IsValid(QuickBarComponent)) {
    }
    IsActive = nullptr;
    IsActive = nullptr;
    return;
}

FEventReply UW_QuickBarSlot::On_SelectionBorder_MouseButtonDown_0(const FGeometry& MyGeometry, const FPointerEvent& MouseEvent) {
    KismetSystemLibrary::PrintString(this, 2f, TEXT("slot pushed boom"), TEXT("None"), TEXT("(R=0.000000,G=0.660000,B=1.000000,A=1.000000)"), nullptr, true, true);
    EnhancedInputSubsystemInterface::InjectInputForAction(SlotInputAction, nullptr, EnhancedInputLibrary::MakeInputActionValueOfType(TEXT("Axis1D"), 1f, 0f, 0f), nullptr);
    return WidgetBlueprintLibrary::Handled();
}

