// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_Replay_ScrubBar.h"

FEventReply UW_Replay_ScrubBar::OnMouseButtonDown_0(const FGeometry& MyGeometry, const FPointerEvent& MouseEvent) {
    LyraReplaySubsystem::GetReplayLengthInSeconds();
    LyraReplaySubsystem::SeekInActiveReplay(/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=6442CF0C-4EAE-850C-6C1A-D2ABDC40F8EF) */);
    return WidgetBlueprintLibrary::Handled();
}

