// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/UserInterface/HUD/W_Reticle_AmmoBar
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraReticleWidgetBase.h"
class ULyraQuickBarComponent;

#include "W_Reticle_AmmoBar.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_Reticle_AmmoBar : public ULyraReticleWidgetBase {
    GENERATED_BODY()
public:
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<ULyraQuickBarComponent> QuickBar;

};
