// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Weapons/Shotgun/W_Reticle_Shotgun
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraReticleWidgetBase.h"
class UAsyncAction_ListenForGameplayMessage;

#include "W_Reticle_Shotgun.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_Reticle_Shotgun : public ULyraReticleWidgetBase {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UAsyncAction_ListenForGameplayMessage> AsyncAction;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UAsyncAction_ListenForGameplayMessage> AsyncActionElimination;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double SpreadRadiusScaler = 0.0;

};
