// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Game/Respawn/W_RespawnTimer
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
class UAsyncAction_ListenForGameplayMessage;
class UAudioComponent;

#include "W_RespawnTimer.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_RespawnTimer : public UUserWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FTimerHandle CooldownTimer;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double Duration = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double StartTime = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool Respawning = false;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<UAudioComponent> CountdownAudio;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UAsyncAction_ListenForGameplayMessage> RespawnCompletedAsyncAction;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UAsyncAction_ListenForGameplayMessage> RespawnDurationAsyncAction;

    UFUNCTION(BlueprintCallable)
    void UpdateRespawnText();
    UFUNCTION(BlueprintCallable)
    void OnTimerFinished();
};
