// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Weapons/Rifle/W_Reticle_Rifle
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraReticleWidgetBase.h"
class UAsyncAction_ListenForGameplayMessage;

#include "W_Reticle_Rifle.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_Reticle_Rifle : public ULyraReticleWidgetBase {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UAsyncAction_ListenForGameplayMessage> AsyncAction;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UAsyncAction_ListenForGameplayMessage> AsyncActionElimination;

};
