// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/UserInterface/Replays/W_Replay_ScrubBar
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_Replay_ScrubBar.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_Replay_ScrubBar : public UUserWidget {
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintCallable)
    FEventReply OnMouseButtonDown_0(const FGeometry& MyGeometry, const FPointerEvent& MouseEvent);
};
