// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_RespawnTimer.h"

void UW_RespawnTimer::UpdateRespawnText() {
    TimeUntilRespawn = /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=275A49EA-45AC-66FF-1C9C-4E838BDE7DEA) */;
    if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=A52471F7-495F-2A9C-816C-AA809E861D3C) */) {
        Image::GetDynamicMaterial();
        Image::GetDynamicMaterial();
        MaterialInstanceDynamic::SetScalarParameterValue(TEXT("AnimateArcFill"), /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=A0995E54-48A4-747B-43C0-25BB1210CC6A) */);
        CommonNumericTextBlock::SetCurrentValue(KismetMathLibrary::Conv_IntToDouble(KismetMathLibrary::FCeil(TimeUntilRespawn)));
        if (IsValid(CountdownAudio)) {
        }
    } else {
        Respawning = false;
        CommonNumericTextBlock::SetCurrentValue(0f);
        PlayAnimationForward(Outro, 1f, false);
        BindToAnimationFinished(Outro, /* TODO[bpr-expr]: K2Node_CreateDelegate (guid=7C53724B-447F-65CB-7D6E-E1BDE327210C) */);
    }
}

void UW_RespawnTimer::OnTimerFinished() {
    SetVisibility(TEXT("Collapsed"));
    KismetSystemLibrary::K2_ClearTimer(TEXT("UpdateRespawnText"), nullptr);
    if (IsValid(CountdownAudio)) {
    }
}

