// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Menu/Replays/W_ReplayListEntry
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
class ULyraReplayListEntry;

#include "W_ReplayListEntry.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_ReplayListEntry : public UUserWidget, public IUserObjectListEntry {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<ULyraReplayListEntry> AsLyraReplayListEntry;

};
