// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/UserInterface/Replays/W_Replay_PlayerSelector
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_Replay_PlayerSelector.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_Replay_PlayerSelector : public UUserWidget {
    GENERATED_BODY()
public:
};
