// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_ReplayBrowserScreen.h"

UWidget* UW_ReplayBrowserScreen::BP_GetDesiredFocusTarget() {
    return RefreshButton;
}

