// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /TopDownArena/UserInterface/W_RoundTimer
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraTaggedWidget.h"
class UB_TopDownArena_GameComponent_Base;

#include "W_RoundTimer.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_RoundTimer : public ULyraTaggedWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UB_TopDownArena_GameComponent_Base> TopDownArenaMode;

};
