// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Settings/Screens/SafeZone/W_SafeZoneEditor
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraSafeZoneEditor.h"
#include "W_SafeZoneEditor.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_SafeZoneEditor : public ULyraSafeZoneEditor {
    GENERATED_BODY()
public:
};
