// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/UserInterface/ScoreBoard/PlayerRow/W_SB_PlayerIcon
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
class ULyraPlayerState;

#include "W_SB_PlayerIcon.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_SB_PlayerIcon : public UUserWidget, public ITakesLyraPlayerState_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<ULyraPlayerState> PlayerState;

};
