// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/UserInterface/ScoreBoard/PlayerRow/W_SB_PlayerStat
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
class ULyraPlayerState;

#include "GameplayTagContainer.h"

#include "W_SB_PlayerStat.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_SB_PlayerStat : public UUserWidget, public ITakesLyraPlayerState_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<ULyraPlayerState> AssociatedPlayerState;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FGameplayTag StatTag;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    double StatWidth = 0.0;

};
