// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_SB_PlayerList.h"

UWidget* UW_SB_PlayerList::BP_GetDesiredFocusTarget() {
    return nullptr;
}

void UW_SB_PlayerList::PassesFilter(APlayerState* TestPS, bool& Passes, bool& Passes) {
    if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=32117B15-4C1C-65C1-AE03-479088017C99) */) {
        return true;
    } else {
        LyraTeamSubsystem::FindTeamFromActor(TestPS);
        return /* TODO[bpr-expr]: K2Node_CommutativeAssociativeBinaryOperator (guid=2F3A1A84-4B63-7316-1726-368880C75A36) */;
    }
    Passes = nullptr;
    Passes = nullptr;
    return;
}

void UW_SB_PlayerList::PollPlayerStates() {
    for (auto& Element : DynamicEntryBoxBase::GetAllEntries()) {
        if (/* TODO[bpr-expr]: K2Node_CallArrayFunction (guid=2BC584A0-44B1-629A-0419-B99742BEA5C4) */) {
            if (IsValid(/* TODO[bpr-expr]: K2Node_GetArrayItem (guid=1948BFA7-4C8D-9FB1-1F98-AAAA79745C6A) */)) {
            }
        }
    }
    if (IsValid(PlayerState)) {
    }
}

void UW_SB_PlayerList::SortPlayerList() {
    for (auto& Element : PlayerStates) {
        CurrentTarget = /* TODO[bpr-expr]: K2Node_MacroInstance (guid=EBA3E6C4-4DD4-A43E-AD79-30A67C1F0AE3) */;
        CurrentElimination = LyraPlayerState::GetStatTagStackCount(TEXT("(TagName=\"ShooterGame.Score.Eliminations\")"));
        InsertIndex = /* TODO[bpr-expr]: K2Node_CallArrayFunction (guid=F50F197C-4532-3C19-0002-7FBC545E8717) */;
        for (auto& Element : SortedPlayerStates) {
            if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=AD1A3D6C-424D-D787-B478-0899960A1884) */) {
                InsertIndex = /* TODO[bpr-expr]: K2Node_MacroInstance (guid=77140CC5-49E1-F52A-E194-A3B259142E18) */;
            }
        }
        // TODO[bpr-unsupported]: K2Node_CallArrayFunction (guid=F1A1065D-41B0-B0C1-B824-E398548F2E77) — manual port required.
        // Manual: Unrecognized BP node class 'K2Node_CallArrayFunction'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
    }
}

