// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/UserInterface/ScoreBoard/W_SB_PlayerList
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "CommonActivatableWidget.h"
class APlayerState;
class ULyraPlayerState;
class UW_BasePlayerRow;

#include "W_SB_PlayerList.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_SB_PlayerList : public UCommonActivatableWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<TObjectPtr<APlayerState>> NewPlayerStates;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<TObjectPtr<ULyraPlayerState>> PlayerStates;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 TeamIdFilter = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TSubclassOf<UW_BasePlayerRow> PlayerRowClass;

    UFUNCTION(BlueprintCallable)
    UWidget* BP_GetDesiredFocusTarget();
    UFUNCTION(BlueprintCallable)
    void PassesFilter(APlayerState* TestPS, bool& Passes, bool& Passes);
    UFUNCTION(BlueprintCallable)
    void PollPlayerStates();
    UFUNCTION(BlueprintCallable)
    void SortPlayerList();
};
