// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Elimination/UI/W_SB_PlayerRow_TDM
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "W_BasePlayerRow_C.h"
#include "W_SB_PlayerRow_TDM.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_SB_PlayerRow_TDM : public UW_BasePlayerRow_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 TeamId = 0;

    UFUNCTION(BlueprintCallable)
    void UpdateIndividualScoreWidget(UTextBlock* Widget, const FGameplayTag& ScoreTag);
    UFUNCTION(BlueprintCallable)
    TArray<UWidget*> GetPlayerStateAwareChildren();
    UFUNCTION(BlueprintCallable)
    void SetRowColor(bool IsOddNumberedRow);
};
