// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/UserInterface/ScoreBoard/W_SB_TeamStat
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "GameplayTagContainer.h"

#include "W_SB_TeamStat.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_SB_TeamStat : public UUserWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 TeamId = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FGameplayTag StatId;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool IsTDMScoring = false;

    UFUNCTION(BlueprintCallable)
    void SetTeamStyle();
};
