// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_SB_TeamStat.h"

void UW_SB_TeamStat::SetTeamStyle() {
    TextBlock::SetText((TeamId == 0 ? nullptr : (TeamId == 1 ? nullptr : nullptr)));
    TextBlock::SetColorAndOpacity(/Script/SlateCore.SlateColor{/*ColorUseRule=*/TEXT("UseColor_Specified"), /*SpecifiedColor=*/(TeamId == 0 ? nullptr : (TeamId == 1 ? TEXT("(R=1.000000,G=0.539480,B=0.318547,A=0.100000)") : TEXT("(R=0.283149,G=0.982251,B=0.973446,A=0.100000)")))});
    TextBlock::SetColorAndOpacity(/Script/SlateCore.SlateColor{/*ColorUseRule=*/TEXT("UseColor_Specified"), /*SpecifiedColor=*/(TeamId == 0 ? nullptr : (TeamId == 1 ? TEXT("(R=1.000000,G=0.539480,B=0.318547,A=0.600000)") : TEXT("(R=0.283149,G=0.982251,B=0.973446,A=0.600000)")))});
    TextBlock::SetColorAndOpacity(/Script/SlateCore.SlateColor{/*ColorUseRule=*/TEXT("UseColor_Specified"), /*SpecifiedColor=*/(TeamId == 0 ? nullptr : (TeamId == 1 ? TEXT("(R=1.000000,G=0.539480,B=0.318547,A=0.400000)") : TEXT("(R=0.283149,G=0.982251,B=0.973446,A=0.400000)")))});
    TextBlock::SetColorAndOpacity(/Script/SlateCore.SlateColor{/*ColorUseRule=*/TEXT("UseColor_Specified"), /*SpecifiedColor=*/(TeamId == 0 ? nullptr : (TeamId == 1 ? TEXT("(R=1.000000,G=0.539480,B=0.318547,A=1.000000)") : TEXT("(R=0.283149,G=0.982251,B=0.973446,A=1.000000)")))});
    Image::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Brush.DrawAs, /*ImageSize=*/Brush.ImageSize, /*Margin=*/Brush.Margin, /*Mirroring=*/Brush.Mirroring, /*OutlineSettings=*/Brush.OutlineSettings, /*ResourceObject=*/(TeamId == 0 ? nullptr : (TeamId == 1 ? nullptr : nullptr)), /*Tiling=*/Brush.Tiling, /*TintColor=*/Brush.TintColor});
    Border::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Background.DrawAs, /*ImageSize=*/Background.ImageSize, /*Margin=*/Background.Margin, /*Mirroring=*/Background.Mirroring, /*OutlineSettings=*/Background.OutlineSettings, /*ResourceObject=*/(TeamId == 0 ? nullptr : (TeamId == 1 ? nullptr : nullptr)), /*Tiling=*/Background.Tiling, /*TintColor=*/Background.TintColor});
    Border::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Background.DrawAs, /*ImageSize=*/Background.ImageSize, /*Margin=*/Background.Margin, /*Mirroring=*/Background.Mirroring, /*OutlineSettings=*/Background.OutlineSettings, /*ResourceObject=*/(TeamId == 0 ? nullptr : (TeamId == 1 ? nullptr : nullptr)), /*Tiling=*/Background.Tiling, /*TintColor=*/Background.TintColor});
    Image::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Brush.DrawAs, /*ImageSize=*/Brush.ImageSize, /*Margin=*/Brush.Margin, /*Mirroring=*/Brush.Mirroring, /*OutlineSettings=*/Brush.OutlineSettings, /*ResourceObject=*/(TeamId == 0 ? nullptr : (TeamId == 1 ? nullptr : nullptr)), /*Tiling=*/Brush.Tiling, /*TintColor=*/Brush.TintColor});
    Image::GetDynamicMaterial();
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("RotationSpeed"), -2f);
}

