// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_ScoreBoard_HeaderRow_CP.h"

void UW_ScoreBoard_HeaderRow_CP::SetTeamStyle() {
    TextBlock::SetColorAndOpacity(/Script/SlateCore.SlateColor{/*ColorUseRule=*/TEXT("UseColor_Specified"), /*SpecifiedColor=*/(TeamId == 0 ? nullptr : (TeamId == 1 ? TEXT("(R=1.000000,G=0.539480,B=0.318547,A=0.400000)") : TEXT("(R=0.283149,G=0.982251,B=0.973446,A=0.400000)")))});
    Border::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Background.DrawAs, /*ImageSize=*/Background.ImageSize, /*Margin=*/Background.Margin, /*Mirroring=*/Background.Mirroring, /*OutlineSettings=*/Background.OutlineSettings, /*ResourceObject=*/(TeamId == 0 ? nullptr : (TeamId == 1 ? nullptr : nullptr)), /*Tiling=*/Background.Tiling, /*TintColor=*/Background.TintColor});
}

