// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_ScoreWidget_Elimination.h"

void UW_ScoreWidget_Elimination::UpdateAllyTeamScore(UB_TeamDeathMatchScoring* TDMScoring) {
    /ShooterCore/Elimination/B_TeamDeathMatchScoring.B_TeamDeathMatchScoring::GetTeamScore(MyTeamID);
    if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=4F82ACE7-473C-7B21-836A-9A94222ABAE6) */) {
        PctToTargetScore = 0f;
    } else {
        PctToTargetScore = /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=48E9A83B-4B94-BBF0-5931-BCBA52F28987) */;
    }
    CommonNumericTextBlock::SetCurrentValue(KismetMathLibrary::Conv_IntToDouble(/ShooterCore/Elimination/B_TeamDeathMatchScoring.B_TeamDeathMatchScoring::GetTeamScore(MyTeamID)));
    CommonNumericTextBlock::SetCurrentValue(KismetMathLibrary::Conv_IntToDouble(/ShooterCore/Elimination/B_TeamDeathMatchScoring.B_TeamDeathMatchScoring::GetTeamScore(MyTeamID)));
    Image::GetDynamicMaterial();
    Image::GetDynamicMaterial();
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("AnimateArcFill"), PctToTargetScore);
}

void UW_ScoreWidget_Elimination::UpdateEnemyTeamScore(UB_TeamDeathMatchScoring* TDMScoring) {
    /ShooterCore/Elimination/B_TeamDeathMatchScoring.B_TeamDeathMatchScoring::GetTeamScore(EnemyTeamID);
    if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=E02B874D-4D98-D88E-573E-3C9C15E3F380) */) {
        PctToTargetScore = 0f;
    } else {
        PctToTargetScore = /* TODO[bpr-expr]: K2Node_PromotableOperator (guid=7553C3C4-4347-65FF-D2E9-038BC3784430) */;
    }
    CommonNumericTextBlock::SetCurrentValue(KismetMathLibrary::Conv_IntToDouble(/ShooterCore/Elimination/B_TeamDeathMatchScoring.B_TeamDeathMatchScoring::GetTeamScore(EnemyTeamID)));
    CommonNumericTextBlock::SetCurrentValue(KismetMathLibrary::Conv_IntToDouble(/ShooterCore/Elimination/B_TeamDeathMatchScoring.B_TeamDeathMatchScoring::GetTeamScore(EnemyTeamID)));
    Image::GetDynamicMaterial();
    Image::GetDynamicMaterial();
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("AnimateArcFill"), PctToTargetScore);
}

void UW_ScoreWidget_Elimination::UpdateTeamStyles() {
    TextBlock::SetColorAndOpacity(/Script/SlateCore.SlateColor{/*ColorUseRule=*/TEXT("UseColor_Specified"), /*SpecifiedColor=*/(MyTeamID == 0 ? nullptr : (MyTeamID == 1 ? TEXT("(R=1.000000,G=0.496933,B=0.318547,A=0.600000)") : TEXT("(R=0.283149,G=0.887923,B=0.822786,A=0.600000)")))});
    TextBlock::SetColorAndOpacity(/Script/SlateCore.SlateColor{/*ColorUseRule=*/TEXT("UseColor_Specified"), /*SpecifiedColor=*/(EnemyTeamID == 0 ? nullptr : (EnemyTeamID == 1 ? TEXT("(R=1.000000,G=0.496933,B=0.318547,A=0.600000)") : TEXT("(R=0.283149,G=0.887923,B=0.822786,A=0.600000)")))});
    TextBlock::SetColorAndOpacity(/Script/SlateCore.SlateColor{/*ColorUseRule=*/TEXT("UseColor_Specified"), /*SpecifiedColor=*/(MyTeamID == 0 ? nullptr : (MyTeamID == 1 ? TEXT("(R=1.000000,G=0.496933,B=0.318547,A=1.000000)") : TEXT("(R=0.283149,G=0.887923,B=0.822786,A=1.000000)")))});
    TextBlock::SetColorAndOpacity(/Script/SlateCore.SlateColor{/*ColorUseRule=*/TEXT("UseColor_Specified"), /*SpecifiedColor=*/(EnemyTeamID == 0 ? nullptr : (EnemyTeamID == 1 ? TEXT("(R=1.000000,G=0.496933,B=0.318547,A=1.000000)") : TEXT("(R=0.283149,G=0.887923,B=0.822786,A=1.000000)")))});
    Image::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Brush.DrawAs, /*ImageSize=*/Brush.ImageSize, /*Margin=*/Brush.Margin, /*Mirroring=*/Brush.Mirroring, /*OutlineSettings=*/Brush.OutlineSettings, /*ResourceObject=*/(MyTeamID == 0 ? nullptr : (MyTeamID == 1 ? nullptr : nullptr)), /*Tiling=*/Brush.Tiling, /*TintColor=*/Brush.TintColor});
    Image::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Brush.DrawAs, /*ImageSize=*/Brush.ImageSize, /*Margin=*/Brush.Margin, /*Mirroring=*/Brush.Mirroring, /*OutlineSettings=*/Brush.OutlineSettings, /*ResourceObject=*/(EnemyTeamID == 0 ? nullptr : (EnemyTeamID == 1 ? nullptr : nullptr)), /*Tiling=*/Brush.Tiling, /*TintColor=*/Brush.TintColor});
    Image::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Brush.DrawAs, /*ImageSize=*/Brush.ImageSize, /*Margin=*/Brush.Margin, /*Mirroring=*/Brush.Mirroring, /*OutlineSettings=*/Brush.OutlineSettings, /*ResourceObject=*/(MyTeamID == 0 ? nullptr : (MyTeamID == 1 ? nullptr : nullptr)), /*Tiling=*/Brush.Tiling, /*TintColor=*/Brush.TintColor});
    Image::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Brush.DrawAs, /*ImageSize=*/Brush.ImageSize, /*Margin=*/Brush.Margin, /*Mirroring=*/Brush.Mirroring, /*OutlineSettings=*/Brush.OutlineSettings, /*ResourceObject=*/(EnemyTeamID == 0 ? nullptr : (EnemyTeamID == 1 ? nullptr : nullptr)), /*Tiling=*/Brush.Tiling, /*TintColor=*/Brush.TintColor});
    Image::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Brush.DrawAs, /*ImageSize=*/Brush.ImageSize, /*Margin=*/Brush.Margin, /*Mirroring=*/Brush.Mirroring, /*OutlineSettings=*/Brush.OutlineSettings, /*ResourceObject=*/(MyTeamID == 0 ? nullptr : (MyTeamID == 1 ? nullptr : nullptr)), /*Tiling=*/Brush.Tiling, /*TintColor=*/Brush.TintColor});
    Image::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Brush.DrawAs, /*ImageSize=*/Brush.ImageSize, /*Margin=*/Brush.Margin, /*Mirroring=*/Brush.Mirroring, /*OutlineSettings=*/Brush.OutlineSettings, /*ResourceObject=*/(EnemyTeamID == 0 ? nullptr : (EnemyTeamID == 1 ? nullptr : nullptr)), /*Tiling=*/Brush.Tiling, /*TintColor=*/Brush.TintColor});
    Image::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Brush.DrawAs, /*ImageSize=*/Brush.ImageSize, /*Margin=*/Brush.Margin, /*Mirroring=*/Brush.Mirroring, /*OutlineSettings=*/Brush.OutlineSettings, /*ResourceObject=*/(MyTeamID == 0 ? nullptr : (MyTeamID == 1 ? nullptr : nullptr)), /*Tiling=*/Brush.Tiling, /*TintColor=*/Brush.TintColor});
    Image::SetBrush(/Script/SlateCore.SlateBrush{/*DrawAs=*/Brush.DrawAs, /*ImageSize=*/Brush.ImageSize, /*Margin=*/Brush.Margin, /*Mirroring=*/Brush.Mirroring, /*OutlineSettings=*/Brush.OutlineSettings, /*ResourceObject=*/(EnemyTeamID == 0 ? nullptr : (EnemyTeamID == 1 ? nullptr : nullptr)), /*Tiling=*/Brush.Tiling, /*TintColor=*/Brush.TintColor});
}

void UW_ScoreWidget_Elimination::UpdateStyleSides() {
    Border::GetDynamicMaterial();
    MaterialInstanceDynamic::SetScalarParameterValue(TEXT("InverseGradient"), (MyTeamID == 0 ? 0f : (MyTeamID == 1 ? 1f : 0f)));
}

void UW_ScoreWidget_Elimination::UpdateClock(double Time) {
    TextBlock::SetText([&]{ FFormatNamedArguments Args;
    Args.Add(TEXT("min"), KismetMathLibrary::FMod(Time, 60f));
    Args.Add(TEXT("sec"), KismetTextLibrary::Conv_DoubleToText(0, 2, 0, 2, TEXT("HalfToEven"), KismetMathLibrary::FMod(Time, 60f), false, true));
    return FText::Format(NSLOCTEXT("BPR", "FormatText", ""), Args); }());
    CurrentTime = KismetMathLibrary::Conv_Int64ToInt(KismetMathLibrary::FFloor64(Time));
    if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=D659D792-48A7-E734-9E1D-9A95AB4022F5) */) {
        if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=847CC0B4-4E47-64F9-59F8-ABB1B2EDD133) */) {
            if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=DEA722B8-49FD-5886-2B27-FB90DD32D60E) */) {
            } else {
                // TODO[bpr-unsupported]: K2Node_Composite (guid=70933C6F-4D02-AC96-6CCC-B396F6A16F5C) — manual port required.
                // Manual: Unrecognized BP node class 'K2Node_Composite'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
                PreviousTime = CurrentTime;
            }
        }
    }
}

void UW_ScoreWidget_Elimination::EvaluateSound_RoundEnding(UB_TeamDeathMatchScoring* TDMScoring) {
    /ShooterCore/Elimination/B_TeamDeathMatchScoring.B_TeamDeathMatchScoring::GetTeamScore(MyTeamID);
    /ShooterCore/Elimination/B_TeamDeathMatchScoring.B_TeamDeathMatchScoring::GetTeamScore(EnemyTeamID);
    if (/* TODO[bpr-expr]: K2Node_PromotableOperator (guid=50ADBA8E-4BEF-0C96-E770-8AACA5E8009D) */) {
    } else {
        if (/* TODO[bpr-expr]: K2Node_CommutativeAssociativeBinaryOperator (guid=B21E92E9-47BA-53F1-2882-CB93243A74A2) */) {
            GameplayStatics::SpawnSound2D(this, nullptr, 1f, nullptr, 0f, 1f, nullptr, true, false);
            if (IsValid(GameplayStatics::SpawnSound2D(this, nullptr, 1f, nullptr, 0f, 1f, nullptr, true, false))) {
            }
        }
    }
}

