// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Elimination/UI/W_ScoreWidget_Elimination
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraTaggedWidget.h"
class UB_TeamDeathMatchScoring;

#include "W_ScoreWidget_Elimination.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_ScoreWidget_Elimination : public ULyraTaggedWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UB_TeamDeathMatchScoring> TDMScoring;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 MyTeamID = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 EnemyTeamID = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 PreviousTime = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 PreviousScoreLeft = 0;

    UFUNCTION(BlueprintCallable)
    void UpdateAllyTeamScore(UB_TeamDeathMatchScoring* TDMScoring);
    UFUNCTION(BlueprintCallable)
    void UpdateEnemyTeamScore(UB_TeamDeathMatchScoring* TDMScoring);
    UFUNCTION(BlueprintCallable)
    void UpdateTeamStyles();
    UFUNCTION(BlueprintCallable)
    void UpdateStyleSides();
    UFUNCTION(BlueprintCallable)
    void UpdateClock(double Time);
    UFUNCTION(BlueprintCallable)
    void EvaluateSound_RoundEnding(UB_TeamDeathMatchScoring* TDMScoring);
};
