// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/Elimination/UI/W_ScoreBoard_HeaderRow_EliminationMode
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_ScoreBoard_HeaderRow_EliminationMode.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_ScoreBoard_HeaderRow_EliminationMode : public UUserWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 TeamId = 0;

    UFUNCTION(BlueprintCallable)
    void SetTeamStyle();
};
