// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Settings/Editors/W_SettingsListEntry_Action
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameSettingListEntrySetting_Action.h"
#include "W_SettingsListEntry_Action.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_SettingsListEntry_Action : public UGameSettingListEntrySetting_Action {
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintCallable)
    UWidget* GetPrimaryGamepadFocusWidget();
};
