// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Settings/Editors/W_SettingsListEntry_Discrete
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameSettingListEntrySetting_Discrete.h"
#include "W_SettingsListEntry_Discrete.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_SettingsListEntry_Discrete : public UGameSettingListEntrySetting_Discrete {
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintCallable)
    UWidget* GetPrimaryGamepadFocusWidget();
};
