// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Settings/Editors/W_SettingsListEntry_Scalar
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameSettingListEntrySetting_Scalar.h"
#include "W_SettingsListEntry_Scalar.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_SettingsListEntry_Scalar : public UGameSettingListEntrySetting_Scalar {
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintCallable)
    UWidget* GetPrimaryGamepadFocusWidget();
};
