// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_SettingsListEntry_SubCollection.h"

UWidget* UW_SettingsListEntry_SubCollection::GetPrimaryGamepadFocusWidget() {
    return Button_Navigate;
}

