// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Settings/W_SettingsPanel
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameSettingPanel.h"
#include "W_SettingsPanel.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_SettingsPanel : public UGameSettingPanel {
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintCallable)
    void OnSettingScreenAnim();
};
