// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Settings/Editors/W_SettingsListEntry_Header
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameSettingListEntry_Setting.h"
#include "W_SettingsListEntry_Header.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_SettingsListEntry_Header : public UGameSettingListEntry_Setting {
    GENERATED_BODY()
public:
};
