// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_SettingsListEntry_KBMBinding.h"

UWidget* UW_SettingsListEntry_KBMBinding::GetPrimaryGamepadFocusWidget() {
    return Button_PrimaryKey;
}

