// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_SettingsListEntry_Discrete.h"

UWidget* UW_SettingsListEntry_Discrete::GetPrimaryGamepadFocusWidget() {
    return Rotator_SettingValue;
}

