// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_SettingsPanel.h"

void UW_SettingsPanel::OnSettingScreenAnim() {
    PlayAnimationForward(OnParentScreenActivated, 1f, false);
}

