// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Settings/Editors/W_SettingsListEntry_SubCollection
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameSettingListEntrySetting_Navigation.h"
#include "W_SettingsListEntry_SubCollection.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_SettingsListEntry_SubCollection : public UGameSettingListEntrySetting_Navigation {
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintCallable)
    UWidget* GetPrimaryGamepadFocusWidget();
};
