// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Menu/Experiences/W_SessionBrowserEntry
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "CommonTabListWidgetBase.h"
class UCommonActivatableWidget;
class UCommonSession_SearchResult;

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnButtonClicked, UCommonSession_SearchResult*, SessionEntry);

#include "W_SessionBrowserEntry.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_SessionBrowserEntry : public UCommonTabListWidgetBase, public IUserObjectListEntry {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FOnButtonClicked OnButtonClicked;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UCommonSession_SearchResult> SessionEntry;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UCommonActivatableWidget> JoiningProgressWidget;

};
