// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Settings/Extensions/Subtitle/W_Settings_SubtitlePreview
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "GameSettingDetailExtension.h"
#include "W_Settings_SubtitlePreview.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_Settings_SubtitlePreview : public UGameSettingDetailExtension {
    GENERATED_BODY()
public:
};
