// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_SettingsListEntry_Action.h"

UWidget* UW_SettingsListEntry_Action::GetPrimaryGamepadFocusWidget() {
    return Button_Action;
}

