// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Menu/Experiences/W_SessionBrowserScreen
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraActivatableWidget.h"
class UCommonSession_SearchSessionRequest;

#include "W_SessionBrowserScreen.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_SessionBrowserScreen : public ULyraActivatableWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<UCommonSession_SearchSessionRequest> SearchRequest;

    UFUNCTION(BlueprintCallable)
    UWidget* BP_GetDesiredFocusTarget();
};
