// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/UserInterface/W_ShooterHUDLayout
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraHUDLayout.h"
#include "W_ShooterHUDLayout.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_ShooterHUDLayout : public ULyraHUDLayout {
    GENERATED_BODY()
public:
};
