// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/UserInterface/Replays/W_ShooterReplayHUD
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraHUDLayout.h"
#include "W_ShooterReplayHUD.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_ShooterReplayHUD : public ULyraHUDLayout {
    GENERATED_BODY()
public:
};
