// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Foundation/Widgets/SimpleProgressBar/W_SimpleProgressBar
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "MaterialProgressBar.h"
#include "W_SimpleProgressBar.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_SimpleProgressBar : public UMaterialProgressBar {
    GENERATED_BODY()
public:
};
