// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/PerfStats/W_SingleTextStat
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraPerfStatWidgetBase.h"
#include "W_SingleTextStat.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_SingleTextStat : public ULyraPerfStatWidgetBase {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display")
    FText StatDisplayName;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display")
    FText StatValueFormat;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display")
    int32 FractionalDigits = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display")
    double ValuePaddingWidth = 0.0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Display")
    double ScaleFactor = 0.0;

};
