// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Foundation/Subtitles/W_SubtitleDisplayHost
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "CommonUserWidget.h"
#include "W_SubtitleDisplayHost.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_SubtitleDisplayHost : public UCommonUserWidget {
    GENERATED_BODY()
public:
};
