// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_TapToggleActionBar.h"

bool UW_TapToggleActionBar::GetCurrentVisibility() {
    return /* TODO[bpr-expr]: K2Node_EnumInequality (guid=B3FF8A58-4A8A-E10A-B684-79A00C7B1388) */;
}

void UW_TapToggleActionBar::ResetVisibility() {
    SetVisibility(TEXT("Collapsed"));
}

