// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Credits/W_TapToggleActionBar
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "CommonUserWidget.h"
#include "W_TapToggleActionBar.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_TapToggleActionBar : public UCommonUserWidget {
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintCallable)
    bool GetCurrentVisibility();
    UFUNCTION(BlueprintCallable)
    void ResetVisibility();
};
