// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/UserInterface/HUD/W_Temp_ReticleDot
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraReticleWidgetBase.h"
#include "W_Temp_ReticleDot.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_Temp_ReticleDot : public ULyraReticleWidgetBase {
    GENERATED_BODY()
public:
};
