// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /TopDownArena/UserInterface/W_TopDownPlayers
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_TopDownPlayers.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_TopDownPlayers : public UUserWidget {
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintCallable)
    TSubclassOf<UUserWidget> OnGetWidgetClassForData_0(UObject* DataItem);
    UFUNCTION(BlueprintCallable)
    void OnConfigureWidgetForData_0(UUserWidget* Widget, UObject* DataItem);
};
