// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /TopDownArena/UserInterface/W_TopDownArenaHUDLayout
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraHUDLayout.h"
#include "W_TopDownArenaHUDLayout.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_TopDownArenaHUDLayout : public ULyraHUDLayout {
    GENERATED_BODY()
public:
};
