// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Hud/W_TouchRegion_Base
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraTouchRegion.h"
#include "W_TouchRegion_Base.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_TouchRegion_Base : public ULyraTouchRegion {
    GENERATED_BODY()
public:
};
