// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Menu/W_TouchCloseButton
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "CommonUserWidget.h"
#include "W_TouchCloseButton.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_TouchCloseButton : public UCommonUserWidget {
    GENERATED_BODY()
public:
};
