// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_UserLoginButton.h"

void UW_UserLoginButton::SetListenForLoginInput(bool ShouldListen) {
    WaitingForLoginInput = ShouldListen;
    if (/* TODO[bpr-expr]: K2Node_VariableSet (guid=B5598409-4401-A2BA-A34C-DAACDF071CA8) */) {
        CommonUserSubsystem::ListenForLoginKeyInput(EmptyKeys, SecondaryLoginKeys, /Script/CommonUser.CommonUserInitializeParams{/*ControllerId=*/-1, /*LocalPlayerIndex=*/1, /*OnUserInitializeComplete=*//* TODO[bpr-expr]: K2Node_CreateDelegate (guid=EF6A31FA-417A-783A-EB27-03BA93CCE636) */, /*OnlineContext=*/TEXT("Game"), /*RequestedPrivilege=*/TEXT("CanPlay"), /*bCanCreateNewLocalPlayer=*/true, /*bCanUseGuestLogin=*/true, /*bSuppressLoginErrors=*/TEXT("False")});
    } else {
        CommonUserSubsystem::ListenForLoginKeyInput(EmptyKeys, EmptyKeys, nullptr);
    }
}

void UW_UserLoginButton::HandleUserInitialize(UCommonUserInfo* UserInfo, bool bSuccess, const FText& Error, uint8 RequestedPrivilege, uint8 OnlineContext) {
    RefreshLoginState();
}

void UW_UserLoginButton::RefreshLoginState() {
    if (IsPlayerLoggedIn()) {
        SetOwningPlayer(GameplayStatics::GetPlayerController(this, PlayerNumber, nullptr));
        LyraButtonBase::SetButtonText(KismetSystemLibrary::MakeLiteralText(nullptr));
        SetListenForLoginInput(false);
    } else {
        SetOwningPlayer(GameplayStatics::GetPlayerController(this, 0, nullptr));
        LyraButtonBase::SetButtonText(KismetSystemLibrary::MakeLiteralText(nullptr));
        SetListenForLoginInput(true);
    }
}

bool UW_UserLoginButton::IsPlayerLoggedIn() {
    return KismetSystemLibrary::IsValid(GameplayStatics::GetPlayerController(this, PlayerNumber, nullptr));
}

