// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/UserInterface/ScoreBoard/W_UserConnectionStatus
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
class ULyraPlayerState;

#include "W_UserConnectionStatus.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_UserConnectionStatus : public UUserWidget, public ITakesLyraPlayerState_C {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<ULyraPlayerState> AssociatedPlayerState;

};
