// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Menu/W_UserLoginButton
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_UserLoginButton.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_UserLoginButton : public UUserWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 PlayerNumber = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FText PlayerStatusText;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool WaitingForLoginInput = false;

    UFUNCTION(BlueprintCallable)
    void SetListenForLoginInput(bool ShouldListen);
    UFUNCTION(BlueprintCallable)
    void HandleUserInitialize(UCommonUserInfo* UserInfo, bool bSuccess, const FText& Error, uint8 RequestedPrivilege, uint8 OnlineContext);
    UFUNCTION(BlueprintCallable)
    void RefreshLoginState();
    UFUNCTION(BlueprintCallable)
    bool IsPlayerLoggedIn();
};
