// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /Game/UI/Menu/W_UserWatermark
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_UserWatermark.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_UserWatermark : public UUserWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    int32 PlayerNumber = 0;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    FText PlayerStatusText;

};
