// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/GameplayCues/W_WaitingForPlayers_Message
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "W_WaitingForPlayers_Message.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_WaitingForPlayers_Message : public UUserWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    bool CountdownStarted = false;

};
