// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.

#include "W_WeaponReticleHost.h"

void UW_WeaponReticleHost::ClearExistingWidgets() {
    for (auto& Element : SpawnedWidgets) {
        PanelWidget::RemoveChild(/* TODO[bpr-expr]: K2Node_MacroInstance (guid=FBCCC107-46D7-2556-06F5-BE845BD5F735) */);
    }
    // TODO[bpr-unsupported]: K2Node_CallArrayFunction (guid=C9F56F9C-4E1E-BA8C-6F85-5793B83E8D8E) — manual port required.
    // Manual: Unrecognized BP node class 'K2Node_CallArrayFunction'. Manual port required; if this is a common pattern, add an entry to UnsupportedTreatment.cpp's table.
}

