// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/UserInterface/HUD/W_WeaponReticleHost
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraWeaponUserInterface.h"
class APawn;
class ULyraHealthComponent;
class UUserWidget;

#include "W_WeaponReticleHost.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_WeaponReticleHost : public ULyraWeaponUserInterface {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TArray<TObjectPtr<UUserWidget>> SpawnedWidgets;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<APawn> CurrentPawn;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<ULyraHealthComponent> CurrentHealthComponent;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<ULyraHealthComponent> NewHealthComponent;

    UFUNCTION(BlueprintCallable)
    void ClearExistingWidgets();
};
