// AUTO-GENERATED by bp-reader transpile. Do not edit — re-run to regenerate.
// Source BP: /ShooterCore/UserInterface/HUD/W_WeaponAmmoAndName
// BPIR version: 1

#pragma once

#include "CoreMinimal.h"
#include "LyraTaggedWidget.h"
class ULyraInventoryItemInstance;
class ULyraQuickBarComponent;

#include "W_WeaponAmmoAndName.generated.h"

UCLASS(MinimalAPI, Blueprintable)
class UW_WeaponAmmoAndName : public ULyraTaggedWidget {
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Default")
    TObjectPtr<ULyraInventoryItemInstance> InventoryItem;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Default")
    TObjectPtr<ULyraQuickBarComponent> QuickBar;

};
